### ISSUE TITLE
[Finchley.M9] NoClassDefFoundError: DirectChannel - TracingChannelInterceptor.java

### ISSUE THREAD

**Issue by strikecr** [spring-cloud/spring-cloud-sleuth#1017]
Hello,

I'm experimenting following issue using spring-cloud Finchley.M9 that includes spring-cloud-sleuth-spring-cloud-sleuth-core-2.0.0.M9.jar. I think it is very related to this one, https://github.com/spring-cloud/spring-cloud-sleuth/issues/976, solving the issue on spring-cloud-sleuth 1.3.4.BUILD-SNAPSHOT. As far I understand, Finchley release includes Spring Cloud Sleuth | 2.0.0.RELEASE.

`2018-06-27 17:39:12.741 ERROR [clarity-rest-all,b4a38b1a15ab251e,b4a38b1a15ab251e,false] 24069 --- [nio-8080-exec-2] o.s.w.s.m.StompSubProtocolHandler        : Failed to send client message to application via MessageChannel in session 4wbxiwl4. Sending STOMP ERROR to client.

org.springframework.messaging.MessageDeliveryException: Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; **nested exception is java.lang.NoClassDefFoundError: org/springframework/integration/channel/DirectChannel**
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:132) ~[spring-messaging-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:105) ~[spring-messaging-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageFromClient(StompSubProtocolHandler.java:282) ~[spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:312) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.delegateMessages(AbstractSockJsSession.java:386) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.handleMessage(WebSocketServerSockJsSession.java:195) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.sockjs.transport.handler.SockJsWebSocketHandler.handleTextMessage(SockJsWebSocketHandler.java:93) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:113) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:42) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:84) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:81) [spring-websocket-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:394) [tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119) [tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495) [tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294) [tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133) [tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82) [tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) [tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) [tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) [tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: java.lang.NoClassDefFoundError: org/springframework/integration/channel/DirectChannel
	at **org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.isDirectChannel(TracingChannelInterceptor.java:146) ~[spring-cloud-sleuth-core-2.0.0.M9.jar:2.0.0.M9]**
	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.preSend(TracingChannelInterceptor.java:139) ~[spring-cloud-sleuth-core-2.0.0.M9.jar:2.0.0.M9]
	at org.springframework.messaging.support.AbstractMessageChannel$ChannelInterceptorChain.applyPreSend(AbstractMessageChannel.java:161) ~[spring-messaging-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:115) ~[spring-messaging-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 32 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.integration.channel.DirectChannel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_161]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_161]
	... 36 common frames omitted`

This is the code on TracingChannelInterceptor.java:146
`	private boolean isDirectChannel(MessageChannel channel) {
		return DirectChannel.class
				.isAssignableFrom(AopUtils.getTargetClass(channel));
	}`

I think it could be a bug, but maybe I'm wrong on the spring-cloud version that I should use.

Regards

**Comment by marcingrzejszczak** [comment]
We already have `Finchley.RELEASE`
