### ISSUE TITLE
Flickering test

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#104]
We have a flickering test that also needs to be refactored

```

Results :
Failed tests: 
  TraceableExecutorServiceTests.test_whenTraceContextOfWorkerThreadIsNotClosed_thenException:80 
applicationEventPublisher.publishEvent(
    isA(org.springframework.cloud.sleuth.event.SpanReleasedEvent)
);
Wanted 11 times:
-> at org.springframework.cloud.sleuth.instrument.executor.TraceableExecutorServiceTests.test_whenTraceContextOfWorkerThreadIsNotClosed_thenException(TraceableExecutorServiceTests.java:80)
But was 10 times:
-> at org.springframework.cloud.sleuth.trace.DefaultTraceManager.close(DefaultTraceManager.java:139)

```

**Comment by marcingrzejszczak** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-sleuth/commit/6f7faf690582850ad74b98c3eb01fe3965da5194
