### ISSUE TITLE
NullPointerException of span when connection refused in netty httpclient

### ISSUE THREAD

**Issue by tcdongge** [spring-cloud/spring-cloud-sleuth#1072]
We're using spring cloud sleuth 2.01 with spring cloud gateway, when the target service is down, will cause this problem.
I think it is because when there is no response, didn't set the `span` in `TracingHttpClientInstrumentation#wrapHttpClientRequestSending`

`stacktrace is below`

```
java.lang.NullPointerException: null
	at brave.http.HttpHandler.handleFinish(HttpHandler.java:43)
	at brave.http.HttpClientHandler.handleReceive(HttpClientHandler.java:129)
	at org.springframework.cloud.sleuth.instrument.web.client.TracingHttpClientInstrumentation.lambda$wrapHttpClientRequestSending$2(TraceWebClientAutoConfiguration.java:406)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:262)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:86)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:86)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onError(FluxRetryPredicate.java:100)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:86)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:86)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:166)
	at reactor.ipc.netty.channel.ContextHandler.fireContextError(ContextHandler.java:272)
	at reactor.ipc.netty.channel.PooledClientContextHandler.operationComplete(PooledClientContextHandler.java:153)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.137.1:3600
		at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
		at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
		at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
		... 2 common frames omitted
	Caused by: java.net.ConnectException: Connection refused: no further information
		... 10 common frames omitted
```

**Comment by major2015** [comment]
```
java.lang.NullPointerException: null
	at brave.http.HttpHandler.handleFinish(HttpHandler.java:43) ~[brave-instrumentation-http-5.1.4.jar:na]
	at brave.http.HttpClientHandler.handleReceive(HttpClientHandler.java:129) ~[brave-instrumentation-http-5.1.4.jar:na]
	at org.springframework.cloud.sleuth.instrument.web.client.TracingHttpClientInstrumentation.lambda$wrapHttpClientRequestSending$2(TraceWebClientAutoConfiguration.java:406) ~[spring-cloud-sleuth-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:264) ~[reactor-core-3.1.9.RELEASE.jar:3.1.9.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:86) [spring-cloud-sleuth-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120) ~[reactor-core-3.1.9.RELEASE.jar:3.1.9.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:86) [spring-cloud-sleuth-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onError(FluxRetryPredicate.java:100) ~[reactor-core-3.1.9.RELEASE.jar:3.1.9.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:86) [spring-cloud-sleuth-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:86) [spring-cloud-sleuth-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:166) ~[reactor-core-3.1.9.RELEASE.jar:3.1.9.RELEASE]
	at reactor.ipc.netty.channel.ContextHandler.fireContextError(ContextHandler.java:276) ~[reactor-netty-0.7.9.RELEASE.jar:0.7.9.RELEASE]
	at reactor.ipc.netty.channel.PooledClientContextHandler.operationComplete(PooledClientContextHandler.java:155) ~[reactor-netty-0.7.9.RELEASE.jar:0.7.9.RELEASE]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_192]
	Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: LAPTOP-BMFSVH3E/192.168.20.43:8090
		at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_192]
		at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_192]
		at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:616) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
		... 2 common frames omitted
	Caused by: java.net.ConnectException: Connection refused: no further information
		... 10 common frames omitted
```

**Comment by major2015** [comment]
i use 2.0.1 cause the same exception @marcingrzejszczak
