### ISSUE TITLE
ClassCastException while using heterogenous spring boot versions

### ISSUE THREAD

**Issue by Andy2003** [spring-cloud/spring-cloud-sleuth#1081]
Using `spring-cloud-sleuth` `2.0.1-RELEASE` with gpc PubSub in an environment where some services are still using spring boot 1.5 results in this ClassCastException:

	An exception happened when we tried to retrieve the [x-cloud-trace-context] from message java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
		at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagation.doGet(MessageHeaderPropagation.java:123)
		at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagation.get(MessageHeaderPropagation.java:94)
		at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagation.get(MessageHeaderPropagation.java:38)
		at zipkin2.propagation.stackdriver.XCloudTraceContextExtractor.extract(XCloudTraceContextExtractor.java:49)
		at zipkin2.propagation.stackdriver.CompositeExtractor.extract(CompositeExtractor.java:37)
		at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.preSend(TracingChannelInterceptor.java:133)
		at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:589)
		at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:435)
		at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
		at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
		at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
		at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
		at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
		at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203)
		at org.springframework.cloud.gcp.pubsub.integration.inbound.PubSubInboundChannelAdapter.receiveMessage(PubSubInboundChannelAdapter.java:79)
		at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:403)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by marcingrzejszczak** [comment]
Spring Cloud Sleuth is not intended to be used with Spring Boot 1.5. 

You're saying that the messages are not compatible with each other? 

`x-cloud-trace-context` seems to be Stackdriver specific. I guess they should ensure the compatibility cc @saturnism

**Comment by adriancole** [comment]
sorry maybe obvious but is this coming from the 2.0 side?

**Comment by Andy2003** [comment]
@adriancole yes the issue occur in spring boot 2.0
@marcingrzejszczak the old services uses `spring-cloud-sleuth` `1.3.1.RELEASE` which is using `spring-boot` `1.5.9.RELEASE`.

After applying the fix of #1082 the old messages from the pub/sub could be consumed by `spring-cloud-stream`. The new messages are having the headers in the right format.

**Comment by marcingrzejszczak** [comment]
I understand that the fix solves the problem for you, but from our knowledge you're the first ones to have such a problem. Also, you haven't upgraded the other service to the latest Sleuth and Boot versions.

Another thing is that you own the way you send the `x-cloud-trace-context`. So either you've changed the format, or we have in Sleuth 2.x. Can you ensure that it's not the first case?

**Comment by Andy2003** [comment]
I have added 3 tests that reflect the current problem. The old messages have a JSON String under the key `nativeHeaders`.

I've updated all services, but there were old messages in the pub/sub not beeing delivered before the upgrade.

**Comment by marcingrzejszczak** [comment]
Cool, thanks.

Now coming back to the original question. Which component is sending those headers. Is it us or SC-GCP ? Cause like I mentioned - `x-cloud-trace-context` is a custom, GCP thing.

**Comment by Andy2003** [comment]
@marcingrzejszczak `spring-sleuth` was used by a down-ported `spring-cloud-gcp-starter-trace` (`1.0.0.RC1`). I don't know if the google guys did some adjustments for the header you mentioned. In our services there was no adjustment.

**Comment by marcingrzejszczak** [comment]
That's why we should fix the root problem which seems to be there in `spring-cloud-gcp-starter-trace`

**Comment by Andy2003** [comment]
Yes but also casting without `instanceOf` check is bad parctice.

**Comment by Andy2003** [comment]
my guess is that the deep structure serialisation was broken by the version we used: 
https://github.com/kiwigrid/spring-cloud-gcp/blob/spring-boot-1.5-support/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/integration/outbound/PubSubMessageHandler.java#L96
