### ISSUE TITLE
Build on JDK 11

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#1108]
Let's make the build work on JDK 11 as it is a long term release

**Comment by adriancole** [comment]
first few issues are on :spring-cloud-sleuth-core all caused by the same thing:

Java(TM) SE Runtime Environment 18.9 (build 11+28)

```
Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.client.serviceregistry.ServiceRegistryAutoConfiguration$ServiceRegistryEndpointConfiguration.serviceRegistryEndpoint
	at org.springframework.cloud.sleuth.instrument.messaging.JmsTracingConfigurationTest.tracesListener_annotationMessageListener(JmsTracingConfigurationTest.java:150)
Caused by: java.lang.IllegalArgumentException: Value must be alpha-numeric
	at org.springframework.cloud.sleuth.instrument.messaging.JmsTracingConfigurationTest.tracesListener_annotationMessageListener(JmsTracingConfigurationTest.java:150)
```

**Comment by marcingrzejszczak** [comment]
The build is working fine. Issue was related to Boot.
