### ISSUE TITLE
Deadlock with spring.data.jpa.repositories.bootstrap-mode=deferred

### ISSUE THREAD

**Issue by hdohlmann** [spring-cloud/spring-cloud-sleuth#1128]
Spring Boot 2.1.0.RELEASE
Spring Cloud Greenwich.M1 (also Finchley.SR2)

Create a project with both spring-boot-starter-data-jpa and spring-cloud-starter-zipkin.
Set the new `spring.data.jpa.repositories.bootstrap-mode=deferred`.
Deadlock during startup.

Created minimal sample as a mashup of spring initialir with jpa and zipkin together with a simple entity and repository.

Steps to reproduce:
Unpack attached project.
Run "mvn clean test"

Remove the `spring.data.jpa.repositories.bootstrap-mode=deferred` line in application.properties and rerun to see test completing with sleuth.

Keep the property and remove the spring-cloud.-starter-zipkin dependency in the pom to see test completing without sleuth.

Main thread locks in `LocalContainerEntityManagerFactoryBean(AbstractEntityManagerFactoryBean).getNativeEntityManagerFactory() line: 539 [return this.nativeEntityManagerFactoryFuture.get();]`

JPA setup thread locks in `DefaultListableBeanFactory(DefaultSingletonBeanRegistry).getSingleton(String, boolean) line: 179 [synchronized (this.singletonObjects) { ]`

JPA setup thread stack:
```Thread [task-1] (Suspended)	
	waiting for: ConcurrentHashMap<K,V>  (id=84)	
	DefaultListableBeanFactory(DefaultSingletonBeanRegistry).getSingleton(String, boolean) line: 179	
	DefaultListableBeanFactory(AbstractBeanFactory).isTypeMatch(String, ResolvableType) line: 493	
	DefaultListableBeanFactory.doGetBeanNamesForType(ResolvableType, boolean, boolean) line: 514	
	DefaultListableBeanFactory.getBeanNamesForType(Class<?>, boolean, boolean) line: 485	
	DefaultListableBeanFactory.getBeanNamesForType(ResolvableType) line: 462	
	DefaultListableBeanFactory.resolveNamedBean(ResolvableType, Object[], boolean) line: 1098	
	DefaultListableBeanFactory.resolveBean(ResolvableType, Object[], boolean) line: 407	
	DefaultListableBeanFactory.getBean(Class<T>, Object...) line: 341	
	DefaultListableBeanFactory.getBean(Class<T>) line: 335	
	LazyTraceThreadPoolTaskExecutor.tracing() line: 231	
	LazyTraceThreadPoolTaskExecutor.execute(Runnable) line: 60	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 498	
	ExecutorBeanPostProcessor$1(ExecutorMethodInterceptor<T>).invoke(MethodInvocation) line: 148	
	CglibAopProxy$CglibMethodInvocation(ReflectiveMethodInvocation).proceed() line: 186	
	CglibAopProxy$DynamicAdvisedInterceptor.intercept(Object, Method, Object[], MethodProxy) line: 688	
	ThreadPoolTaskExecutor$$EnhancerBySpringCGLIB$$a86302b9.execute(Runnable) line: not available	
	DataSourceInitializedPublisher$DataSourceSchemaCreatedPublisher.postProcessEntityManagerFactory(EntityManagerFactory) line: 201	
	LocalContainerEntityManagerFactoryBean(AbstractEntityManagerFactoryBean).buildNativeEntityManagerFactory() line: 411	
	1974379194.call() line: not available	
	TraceCallable<V>.call() line: 63	
	FutureTask<V>.run() line: 266	
	ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1149	
	ThreadPoolExecutor$Worker.run() line: 624	
	Thread.run() line: 748	
```
[deferred.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2557728/deferred.zip)

**Comment by hdohlmann** [comment]
Should I cross-report this with spring-data-jpa?

**Comment by marcingrzejszczak** [comment]
Does it work without Sleuth?

**Comment by hdohlmann** [comment]
Yes, it works splendidly without sleuth. 
Should have added that in the initial report, sorry. Try it by removing the spring-cloud-starter-zipkin dependency from the pom.

**Comment by marcingrzejszczak** [comment]
Related issue https://github.com/spring-projects/spring-boot/issues/15038

**Comment by yarodinD** [comment]
I have the same issue with a different setup: Spring Boot 2.1.1, spring-cloud-starter-sleuth from Greenwich.M3 release train and spring-session-data-redis 2.1.2.RELEASE.

As soon as I remove either sleuth or spring-session-data-redis, it works. Both at the same time, I get a thread lock.
[bug_thread dump_trace_sleuth.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/2647780/bug_thread.dump_trace_sleuth.txt)

**Comment by yarodinD** [comment]
Since the setup where I experience the problem is different from this tickets original description and since this ticket here is supposedly fixed, I created a new issue: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1154

**Comment by yarodinD** [comment]
Sorry, my setup was broken in another place, not related to sleuth. Ignore what I wrote.

**Comment by hdohlmann** [comment]
I can confirm that the attached sample now works using spring boot 2.1.2.RELEASE and spring cloud Greenwitch.RELEASE.

Unfortunately, in real-life projects, I get the following during startup:
`ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'spanBytesEncoder' defined in class path resource [org/springframework/cloud/sleuth/zipkin2/ZipkinBackwardsCompatibilityAutoConfiguration.class]: Unsatisfied dependency expressed through method 'spanBytesEncoder' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.sleuth.zipkin2.ZipkinProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

Followed by the following advise:
>***************************
>APPLICATION FAILED TO START
>***************************
>
>Description:
>
>Parameter 0 of method spanBytesEncoder in org.springframework.cloud.sleuth.zipkin2.ZipkinBackwardsCompatibilityAutoConfiguration required a bean of type 'org.springframework.cloud.sleuth.zipkin2.ZipkinProperties' that could not be found.
>
>
>Action:
>
>Consider defining a bean of type 'org.springframework.cloud.sleuth.zipkin2.ZipkinProperties' in your configuration.


Any ideas?

**Comment by marcingrzejszczak** [comment]
https://github.com/spring-cloud/spring-cloud-sleuth/issues/1191

**Comment by hdohlmann** [comment]
Thx :-)

**Comment by angcap** [comment]
Hi, 
i'm experiencing the deadlock with spring boot 2.3.4 and spring cloud Hoxton.SR8 release train.

A thread dump shows:
```
"scheduling-1" #24 prio=5 os_prio=0 cpu=1188,63ms elapsed=14,39s tid=0x00007fb12d5e4800 nid=0x7ffd waiting for monitor entry  [0x00007fb11e5f8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:986)
        - waiting to lock <0x0000000708c8d250> (a java.util.concurrent.ConcurrentHashMap)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:884)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:619)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:536)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:503)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:480)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:473)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1159)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:420)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
        at org.springframework.cloud.sleuth.instrument.async.LazyTraceThreadPoolTaskScheduler.spanNamer(LazyTraceThreadPoolTaskScheduler.java:428)
        at org.springframework.cloud.sleuth.instrument.async.LazyTraceThreadPoolTaskScheduler.execute(LazyTraceThreadPoolTaskScheduler.java:187)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.2/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.2/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.2/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.2/Method.java:566)
        at org.springframework.cloud.sleuth.instrument.async.ExecutorMethodInterceptor.invoke(ExecutorBeanPostProcessor.java:356)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler$$EnhancerBySpringCGLIB$$61bef91f.execute(<generated>)
        at org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher$DataSourceSchemaCreatedPublisher.postProcessEntityManagerFactory(DataSourceInitializedPublisher.java:199)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:412)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean$$Lambda$841/0x00000008006cf840.call(Unknown Source)
        at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:71)
        at java.util.concurrent.FutureTask.run(java.base@11.0.2/FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.2/ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)

   Locked ownable synchronizers:
        - <0x00000007172f2120> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

[On github](https://github.com/angcap/sleuthdeadlock.git) i've published my application to help reproduce the issue.

**Comment by bdbogjoe** [comment]
same issue here with Hoxton SR9 and spring boot 2.3.4, any work around ?
