### ISSUE TITLE
sending traces and spans to zikpin fails on frame size

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-sleuth#113]
Hi,
i have configured my application to send spans to zipkin query  in the following way:
```yml
spring:
    zipkin:
        host: localhost
        port: 9411
sample:
  zipkin:
    enabled: true
```

And I have the zipkin in my pom:
```xml
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin</artifactId>
</dependency>
```

This is the exception I see in the log:
```
2016-01-17 09:53:29 WARN  [trace=,span=] pool-9-thread-1 SpanProcessingThread:131 - Logging spans failed. 7 spans are lost!
org.apache.thrift.transport.TTransportException: Frame size (1213486160) larger than max length (16384000)!
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:137) ~[libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101) ~[libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84) ~[libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378) ~[libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:297) ~[libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:204) ~[libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69) ~[libthrift-0.9.0.jar:0.9.0]
	at com.twitter.zipkin.gen.scribe$Client.recv_Log(scribe.java:74) ~[brave-spancollector-scribe-3.2.0.jar:?]
	at com.twitter.zipkin.gen.scribe$Client.Log(scribe.java:61) ~[brave-spancollector-scribe-3.2.0.jar:?]
	at com.github.kristofa.brave.scribe.SpanProcessingThread.log(SpanProcessingThread.java:128) [brave-spancollector-scribe-3.2.0.jar:?]
	at com.github.kristofa.brave.scribe.SpanProcessingThread.log(SpanProcessingThread.java:110) [brave-spancollector-scribe-3.2.0.jar:?]
	at com.github.kristofa.brave.scribe.SpanProcessingThread.call(SpanProcessingThread.java:96) [brave-spancollector-scribe-3.2.0.jar:?]
	at com.github.kristofa.brave.scribe.SpanProcessingThread.call(SpanProcessingThread.java:36) [brave-spancollector-scribe-3.2.0.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
2016-01-17 09:53:49 WARN  [trace=,span=] pool-9-thread-1 TIOStreamTransport:112 - Error closing output stream.
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116) ~[?:1.8.0_45]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[?:1.8.0_45]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_45]
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_45]
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158) ~[?:1.8.0_45]
	at org.apache.thrift.transport.TIOStreamTransport.close(TIOStreamTransport.java:110) [libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.transport.TSocket.close(TSocket.java:194) [libthrift-0.9.0.jar:0.9.0]
	at org.apache.thrift.transport.TFramedTransport.close(TFramedTransport.java:89) [libthrift-0.9.0.jar:0.9.0]
	at com.github.kristofa.brave.scribe.ScribeClientProvider.close(ScribeClientProvider.java:96) [brave-spancollector-scribe-3.2.0.jar:?]
	at com.github.kristofa.brave.scribe.ScribeClientProvider.exception(ScribeClientProvider.java:75) [brave-spancollector-scribe-3.2.0.jar:?]
	at com.github.kristofa.brave.scribe.SpanProcessingThread.log(SpanProcessingThread.java:124) [brave-spancollector-scribe-3.2.0.jar:?]
	at com.github.kristofa.brave.scribe.SpanProcessingThread.log(SpanProcessingThread.java:110) [brave-spancollector-scribe-3.2.0.jar:?]
	at com.github.kristofa.brave.scribe.SpanProcessingThread.call(SpanProcessingThread.java:96) [brave-spancollector-scribe-3.2.0.jar:?]
	at com.github.kristofa.brave.scribe.SpanProcessingThread.call(SpanProcessingThread.java:36) [brave-spancollector-scribe-3.2.0.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
```

**Comment by adriancole** [comment]
looks like you are sending pretty huge spans! 7 spans are 16MiB?

**Comment by adriancole** [comment]
This is an implementation detail of brave's scribe span collector, which
the SNAPSHOT version of sleuth doesn't use.

It may be possible to work around this issue by custom configuration. I'd
look around/ raise issue on brave just in case someone else ran into this.

https://github.com/openzipkin/brave/blob/master/brave-spancollector-scribe/src/main/java/com/github/kristofa/brave/scribe

**Comment by ezraroi** [comment]
Hi @adriancole,
I am just using the spring sleuth to create and collect my spans... I am not doing anything special, just a service receiving a request and passing to a database and back to the client. Why the spans can come be so huge?

**Comment by dsyer** [comment]
See #82 to follow the debate about verbose spans. I don't think there is anything to do here (and we probably won't be using Brave, and certainly not Thrift, any more), so I'm going to close this one.

**Comment by ezraroi** [comment]
@dsyer , so the way spring-sleuth will collect spans will be different in the next milestone? 
Can I currently configure it not to use brave scribe span collector but somethings else?

**Comment by dsyer** [comment]
That's the gist of it yes. If you don't want to use Brave you can still use Zipkin with the spring-cloud-sleuth-stream (on the client) and spring-cloud-stream-zipkin (on the server). But if your spans are really several MB each then you are not going to want all that data in the backend.

**Comment by ezraroi** [comment]
It ia very interesting why the spans are so big,  as i have very simple use case,  such as the example.  Somehow the spans becomes so big,  I will try to understand why they become so huge,  as i didn't do anything actively.

**Comment by adriancole** [comment]
@ezraroi the short of it is that implicitly they were becoming big. Very likely you have some large headers. The next release of sleuth will result in far less data, with no configuration needed on your part to make that so.

**Comment by ezraroi** [comment]
@adriancole thanks,  the direction of the next release sounds great.  I don't think i have large headers as i make requests with a client i wrote so i send minimal http headers.  Will try find out what it is and will report if i will find anything

**Comment by adriancole** [comment]
ack. sometimes it is implicit stuff added by a client or server. Ex I found
Accept-Language, pretty monsterous. Happy hunting!

**Comment by ezraroi** [comment]
Hi @dsyer , I didn't understand your suggestion. I currently used in my micro service the `spring-cloud-sleuth-zipkin` which uses Brave. From the docs I see I can use the `spring-cloud-sleuth-stream` on my service, but I didn't find the project `spring-cloud-stream-zipkin`. Does the `spring-cloud-stream-zipkin` subscribes to the event broker and pulls the message I sent with the `spring-cloud-sleuth-stream` and sends them to Zipkin Collector?

**Comment by dsyer** [comment]
The `spring-cloud-sleuth-stream` library is part of Spring Cloud Sleuth. It is easy to locate (e.g. here it is on github: https://github.com/spring-cloud/spring-cloud-sleuth/tree/master/spring-cloud-sleuth-stream). Yes, you have the architecture mostly correct (`spring-cloud-stream-zipkin` is the consumer), but if you look at the implementation you will see that it sends the span data straight to the `SpanStore` (there is no separate collector).

**Comment by ezraroi** [comment]
Thanks @dsyer
