### ISSUE TITLE
Logback-spring.xml springProperty issue

### ISSUE THREAD

**Issue by destebanm** [spring-cloud/spring-cloud-sleuth#1207]
Hi!
I am trying to include sleuth in my spring boot projects. 

In my first try I am getting an error related with logs. As soon as I include:

	       <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
			<version>2.1.0.RELEASE</version>
		</dependency>

I am getting this error:

```
Exception in thread "main" java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [appenderRef_IS_UNDEFINED]. Did you define it below instead of above in the configuration file?
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [appenderRef_IS_UNDEFINED]. Did you define it below instead of above in the configuration file?
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:82)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:117)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:293)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:266)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:229)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:202)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:191)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:105)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:71)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at es.openbank.LogsApplication.main(LogsApplication.java:16)
```
This is my logback-spring.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

	<include resource="org/springframework/boot/logging/logback/defaults.xml" />
	<springProperty scope="context" name="APP_NAME"
		source="spring.application.name" />
	<springProperty name="consoleAppenderPattern" source="logging.pattern.console" />
	<springProperty name="markersConfidentialName"
		source="logging.filter.markers.confidential.name" />
	<springProperty name="markersConfidentialOnMatch"
		source="logging.filter.markers.confidential.onMatch" />
	**<springProperty name="appenderRef" scope="context" source="logging.appender-ref" />**

	<!-- Appenders -->

	<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>${consoleAppenderPattern}</pattern>
			<charset>UTF-8</charset>
		</encoder>
	</appender>

	<appender name="JSON" class="ch.qos.logback.core.ConsoleAppender">
		<!-- encoder is required -->
		<encoder
			class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
			<!-- <jsonGeneratorDecorator -->
			<!-- class="net.logstash.logback.decorate.PrettyPrintingJsonGeneratorDecorator" 
				/> -->
			<providers>
				<timestamp />
				<mdc />
				<context />
				<logLevel />
				<loggerName />
				<threadName />
				<message />
				<arguments />
				<stackTrace />
				<tags />
			</providers>
		</encoder>
	</appender>

	<!-- It enables to show CONFIDENTIAL logs no matter the configured log level -->
	<turboFilter class="ch.qos.logback.classic.turbo.MarkerFilter">
		<Marker>${markersConfidentialName}</Marker>
		<OnMatch>${markersConfidentialOnMatch}</OnMatch>
	</turboFilter>

	<!-- Profiles -->
	<springProfile name="default">
		<logger name="es.dem" additivity="false">
			<level value="DEBUG" />
			<appender-ref ref='${**appenderRef**}' />
		</logger>
		<root level="TRACE">
			<appender-ref ref='${appenderRef}' />
		</root>
	</springProfile>

	<springProfile name="dev,test,qa,stg">
		<logger name="es.dem" additivity="false">
			<level value="DEBUG" />
			<appender-ref ref='${appenderRef}' />
		</logger>
		<root level="INFO">
			<appender-ref ref='${appenderRef}' />
		</root>
	</springProfile>
	<springProfile name="ocu,prod">
		<root level="WARN">
			<appender-ref ref='${appenderRef}' />
		</root>
	</springProfile>

</configuration>
```

As you can see **appenderRef** is a property. If I use "CONSOLE"/"JSON" explicitly  instead of using a variable everything works fine.

Why sleuth is causing this issue??

Thanks!

**Comment by marcingrzejszczak** [comment]
Can you upload a sample that replicates the issue somewhere at GitHub?

**Comment by destebanm** [comment]
I had to create a bootstrap.yaml file.

```
logging:
  appender-ref: JSON
  pattern:
    console: date=%d{yyyy-MM-dd HH:mm:ss.SSS} | projectVersion=%X{projectVersion} | level=%5p | marker=%-17marker |thread=%-20.20thread | traceId=%X{traceId} | spanId=%X{spanId} | clientId=%X{clientId} | class=%class{15}.%L | message="%m"%n
```
Then, It started to work, but if use application.properties or application.yml ...

Is there any way to get it working without bootstrap.yaml?

Thanks!

**Comment by marcingrzejszczak** [comment]
It's described in the documentation.

![image](https://user-images.githubusercontent.com/3297437/52707116-4074d600-2f87-11e9-8f97-33d9bb551f90.png)

**Comment by msmsimondean** [comment]
I'm getting the same issue.  The behaviour only happens when `org.springframework.cloud:spring-cloud-starter-zipkin` is on the class path.  Seems odd that Cloud/Sleuth changes a built-in behaviour of Spring Boot?

**Comment by judomu** [comment]
I had the same issue and resolved it by using a defaultValue in the meantime:

```
  <springProperty name="variablename" source="application.variablename" defaultValue="unknown" />
```

This still seems like a bad workaround and is not well documented imho. Any error caused by logback failure is hard to fix.
