### ISSUE TITLE
NPE when a connection is refused with Spring Cloud Gateway and tracing enabled

### ISSUE THREAD

**Issue by gasparetto** [spring-cloud/spring-cloud-sleuth#1224]
An NPE is thrown when a connection is refused with Spring Cloud Gateway and tracing is enabled.

We are using Spring 2.1.3.RELEASE with cloud dependencies Greenwich.RELEASE.

The application is a simple API gateway (spring-cloud-starter-gateway) with distributed tracing enable (spring-cloud-starter-sleuth). When the target service of the gateway is down an NPE is thrown with this stacktrace:

```
java.lang.NullPointerException: null
    at org.springframework.cloud.sleuth.instrument.web.client.HttpClientBeanPostProcessor$AbstractTracingDoOnHandler.handle(HttpClientBeanPostProcessor.java:210) ~[spring-cloud-sleuth-core-2.1.0.RELEASE.jar:2.1.0.RELEASE]
    at org.springframework.cloud.sleuth.instrument.web.client.HttpClientBeanPostProcessor$TracingDoOnErrorRequest.accept(HttpClientBeanPostProcessor.java:174) ~[spring-cloud-sleuth-core-2.1.0.RELEASE.jar:2.1.0.RELEASE]
    at org.springframework.cloud.sleuth.instrument.web.client.HttpClientBeanPostProcessor$TracingDoOnErrorRequest.accept(HttpClientBeanPostProcessor.java:161) ~[spring-cloud-sleuth-core-2.1.0.RELEASE.jar:2.1.0.RELEASE]
    at reactor.netty.http.client.HttpClientDoOnError$OnErrorTcpClient.lambda$connect$0(HttpClientDoOnError.java:200) ~[reactor-netty-0.8.5.RELEASE.jar:0.8.5.RELEASE]

```

I've prepared a minimal sample.
[gwtest.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2915310/gwtest.zip)

$ mvn spring-boot:run
then
$ curl http://localhost:8080/api/v1/myroute

**Comment by marcingrzejszczak** [comment]
Hi @gasparetto . Thanks for the sample, it was trivial to reproduce the case thanks to it.
