### ISSUE TITLE
Trace headers not available in Tomcat access log

### ISSUE THREAD

**Issue by thanus** [spring-cloud/spring-cloud-sleuth#1329]
It seems that the Sleuth Trace/Spans are not available in the Tomcat access log. This only seems to be the case in the first initial application that receives a request. To give an example of this, I took the project from Spring Guides https://spring.io/guides/gs/routing-and-filtering / https://github.com/spring-guides/gs-routing-and-filtering. This project has a Netflix Zuul Gateway that sends requests to a Books application. In my [fork](https://github.com/thanus/gs-routing-and-filtering) of this project I use Spring boot 2.1.3.RELEASE and Spring Cloud Greenwich.SR1.

Access logs are configured for both applications with the following properties. A custom pattern is used to add the Sleuth Trace headers:

```yml
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.prefix=access
# set accesslog path
#server.tomcat.accesslog.directory=
server.tomcat.accesslog.pattern='{ "clientip":"%h", "log_date":"%t", "rawrequest_str":"%r", "response_int":%s, "bytes_int":%B, "response_time_int":%D, "referrer_stn":"%{Referer}i", "agent_stn":"%{User-agent}i", "X-B3-TraceId":"%{X-B3-TraceId}i", "X-B3-SpanId":"%{X-B3-SpanId}i", "X-B3-ParentSpanId":"%{X-B3-ParentSpanId}i" }'
```

#### Gateway access log
```
'{ "clientip":"0:0:0:0:0:0:0:1", "log_date":"[05/Apr/2019:19:10:16 +0200]", "rawrequest_str":"GET /books/available HTTP/1.1", "response_int":200, "bytes_int":27, "response_time_int":205, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"-", "X-B3-SpanId":"-", "X-B3-ParentSpanId":"-" }'
'{ "clientip":"0:0:0:0:0:0:0:1", "log_date":"[05/Apr/2019:19:10:17 +0200]", "rawrequest_str":"GET /books/available HTTP/1.1", "response_int":200, "bytes_int":27, "response_time_int":7, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"-", "X-B3-SpanId":"-", "X-B3-ParentSpanId":"-" }'
'{ "clientip":"0:0:0:0:0:0:0:1", "log_date":"[05/Apr/2019:19:10:18 +0200]", "rawrequest_str":"GET /books/available HTTP/1.1", "response_int":200, "bytes_int":27, "response_time_int":6, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"-", "X-B3-SpanId":"-", "X-B3-ParentSpanId":"-" }'
'{ "clientip":"0:0:0:0:0:0:0:1", "log_date":"[05/Apr/2019:19:10:18 +0200]", "rawrequest_str":"GET /books/available HTTP/1.1", "response_int":200, "bytes_int":27, "response_time_int":10, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"-", "X-B3-SpanId":"-", "X-B3-ParentSpanId":"-" }'
```
As you can see the trace headers are empty: ` "X-B3-TraceId":"-", "X-B3-SpanId":"-", "X-B3-ParentSpanId":"-"` .

#### Simplefilter log (filter which basically logs the request in the gateway)
```
2019-04-05 19:10:16.623  INFO [-,e60907f3e137cccc,e60907f3e137cccc,false] 2146 --- [nio-8080-exec-1] hello.filters.pre.SimpleFilter           : GET request to http://localhost:8080/books/available
2019-04-05 19:10:17.368  INFO [-,64c924996acb4b7e,64c924996acb4b7e,false] 2146 --- [nio-8080-exec-2] hello.filters.pre.SimpleFilter           : GET request to http://localhost:8080/books/available
2019-04-05 19:10:18.083  INFO [-,f7a8250457d486c0,f7a8250457d486c0,false] 2146 --- [nio-8080-exec-3] hello.filters.pre.SimpleFilter           : GET request to http://localhost:8080/books/available
2019-04-05 19:10:18.840  INFO [-,06842a6aa982bb25,06842a6aa982bb25,false] 2146 --- [nio-8080-exec-4] hello.filters.pre.SimpleFilter           : GET request to http://localhost:8080/books/available
```
The trace headers are available here and I would expect the same headers in the gateway access log.

#### Book access log
```
'{ "clientip":"127.0.0.1", "log_date":"[05/Apr/2019:19:10:16 +0200]", "rawrequest_str":"GET /available HTTP/1.1", "response_int":200, "bytes_int":16, "response_time_int":67, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"e60907f3e137cccc", "X-B3-SpanId":"38e3977f2a64047c", "X-B3-ParentSpanId":"e60907f3e137cccc" }'
'{ "clientip":"127.0.0.1", "log_date":"[05/Apr/2019:19:10:17 +0200]", "rawrequest_str":"GET /available HTTP/1.1", "response_int":200, "bytes_int":16, "response_time_int":2, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"64c924996acb4b7e", "X-B3-SpanId":"1723e6468c175dcd", "X-B3-ParentSpanId":"64c924996acb4b7e" }'
'{ "clientip":"127.0.0.1", "log_date":"[05/Apr/2019:19:10:18 +0200]", "rawrequest_str":"GET /available HTTP/1.1", "response_int":200, "bytes_int":16, "response_time_int":2, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"f7a8250457d486c0", "X-B3-SpanId":"b5a3249ccf73b72e", "X-B3-ParentSpanId":"f7a8250457d486c0" }'
'{ "clientip":"127.0.0.1", "log_date":"[05/Apr/2019:19:10:18 +0200]", "rawrequest_str":"GET /available HTTP/1.1", "response_int":200, "bytes_int":16, "response_time_int":2, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"06842a6aa982bb25", "X-B3-SpanId":"899e2ffec895f751", "X-B3-ParentSpanId":"06842a6aa982bb25" }'
```
The trace headers are available in the Book's access log, these are forwarded by the gateway.
So it looks like when the incoming request contains the trace headers, these are also available in the access log. This is not the case with the gateway, as this is the first application that receives the request. 

Could it be that at the moment an access log is created, no Trace has been created by Sleuth? There is also a similar issue https://github.com/spring-cloud/spring-cloud-sleuth/issues/1131 but with Netty access log.

### _Workaround_
Now I have a workaround where the Trace headers are available in the first application that receives the request, based on the blog of [inject-sleuth-header-on-first-request-with-tomcat](https://blog.lgohlke.de/sleuth/tomcat/spring-cloud/spring-boot/2017/11/26/inject-sleuth-header-on-first-request-with-tomcat.html). See branch `tracing-accesslog-workaround` of fork. A custom Tomcat valve (SleuthValve) is used to create a new span when the incoming request doesn't have a TraceId.

```java
class SleuthValve extends ValveBase {
  private final Tracer tracer;

  SleuthValve(Tracer tracer) {
    this.tracer = tracer;
  }

  @Override
  public void invoke(Request request, Response response) throws IOException, ServletException {
    enrichWithSleuthHeaderWhenMissing(tracer, request);

    Valve next = getNext();
    if (null == next) {
      // no next valve
      return;
    }
    next.invoke(request, response);
  }

  private static void enrichWithSleuthHeaderWhenMissing(final Tracer tracer, final Request request) {
    String header = request.getHeader("X-B3-TraceId");

    if (null == header) {
      org.apache.coyote.Request coyoteRequest = request.getCoyoteRequest();
      MimeHeaders mimeHeaders = coyoteRequest.getMimeHeaders();

      Span span = tracer.newTrace();

      addHeader(mimeHeaders, "X-B3-TraceId", span.context().traceIdString());
      addHeader(mimeHeaders, "X-B3-SpanId", span.context().traceIdString());
    }
  }

  private static void addHeader(MimeHeaders mimeHeaders, String traceIdName, String value) {
    MessageBytes messageBytes = mimeHeaders.addValue(traceIdName);
    messageBytes.setString(value);
  }
}
```

```java
@Configuration
public class AccessLogSleuthConfiguration implements WebServerFactoryCustomizer<TomcatServletWebServerFactory> {

  private final SleuthValve sleuthValve;

  public AccessLogSleuthConfiguration(SleuthValve sleuthValve) {
    this.sleuthValve = sleuthValve;
  }

  @Override
  public void customize(TomcatServletWebServerFactory factory) {
    factory.addContextCustomizers(context -> context.getPipeline().addValve(sleuthValve));
  }

}
```

#### Gateway access log
```
'{ "clientip":"0:0:0:0:0:0:0:1", "log_date":"[05/Apr/2019:19:18:20 +0200]", "rawrequest_str":"GET /books/available HTTP/1.1", "response_int":200, "bytes_int":27, "response_time_int":186, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"c70efc5d25b70730", "X-B3-SpanId":"c70efc5d25b70730", "X-B3-ParentSpanId":"-" }'
'{ "clientip":"0:0:0:0:0:0:0:1", "log_date":"[05/Apr/2019:19:18:21 +0200]", "rawrequest_str":"GET /books/available HTTP/1.1", "response_int":200, "bytes_int":27, "response_time_int":7, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"c337d4c36da9e186", "X-B3-SpanId":"c337d4c36da9e186", "X-B3-ParentSpanId":"-" }'
'{ "clientip":"0:0:0:0:0:0:0:1", "log_date":"[05/Apr/2019:19:18:22 +0200]", "rawrequest_str":"GET /books/available HTTP/1.1", "response_int":200, "bytes_int":27, "response_time_int":6, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"9b441be7bdf1559e", "X-B3-SpanId":"9b441be7bdf1559e", "X-B3-ParentSpanId":"-" }'
'{ "clientip":"0:0:0:0:0:0:0:1", "log_date":"[05/Apr/2019:19:18:23 +0200]", "rawrequest_str":"GET /books/available HTTP/1.1", "response_int":200, "bytes_int":27, "response_time_int":5, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"f079246af5fbba84", "X-B3-SpanId":"f079246af5fbba84", "X-B3-ParentSpanId":"-" }'
```

#### SimpleFilter log
```
2019-04-05 19:18:20.546  INFO [-,c70efc5d25b70730,c70efc5d25b70730,false] 2526 --- [nio-8080-exec-1] hello.filters.pre.SimpleFilter           : GET request to http://localhost:8080/books/available
2019-04-05 19:18:21.296  INFO [-,c337d4c36da9e186,c337d4c36da9e186,false] 2526 --- [nio-8080-exec-2] hello.filters.pre.SimpleFilter           : GET request to http://localhost:8080/books/available
2019-04-05 19:18:21.997  INFO [-,9b441be7bdf1559e,9b441be7bdf1559e,false] 2526 --- [nio-8080-exec-3] hello.filters.pre.SimpleFilter           : GET request to http://localhost:8080/books/available
2019-04-05 19:18:23.586  INFO [-,f079246af5fbba84,f079246af5fbba84,false] 2526 --- [nio-8080-exec-4] hello.filters.pre.SimpleFilter           : GET request to http://localhost:8080/books/available
```

#### Book access log
```
'{ "clientip":"127.0.0.1", "log_date":"[05/Apr/2019:19:18:20 +0200]", "rawrequest_str":"GET /available HTTP/1.1", "response_int":200, "bytes_int":16, "response_time_int":59, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"c70efc5d25b70730", "X-B3-SpanId":"ff0ff504dbf88036", "X-B3-ParentSpanId":"c70efc5d25b70730" }'
'{ "clientip":"127.0.0.1", "log_date":"[05/Apr/2019:19:18:21 +0200]", "rawrequest_str":"GET /available HTTP/1.1", "response_int":200, "bytes_int":16, "response_time_int":2, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"c337d4c36da9e186", "X-B3-SpanId":"c9942540270d5b92", "X-B3-ParentSpanId":"c337d4c36da9e186" }'
'{ "clientip":"127.0.0.1", "log_date":"[05/Apr/2019:19:18:22 +0200]", "rawrequest_str":"GET /available HTTP/1.1", "response_int":200, "bytes_int":16, "response_time_int":2, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"9b441be7bdf1559e", "X-B3-SpanId":"12cd013e5ad7bc0d", "X-B3-ParentSpanId":"9b441be7bdf1559e" }'
'{ "clientip":"127.0.0.1", "log_date":"[05/Apr/2019:19:18:23 +0200]", "rawrequest_str":"GET /available HTTP/1.1", "response_int":200, "bytes_int":16, "response_time_int":2, "referrer_stn":"-", "agent_stn":"insomnia/6.3.2", "X-B3-TraceId":"f079246af5fbba84", "X-B3-SpanId":"df0cddef94547799", "X-B3-ParentSpanId":"f079246af5fbba84" }'
```
Is this a good solution to make the trace headers available in the access log? It would be nice if Sleuth can take care of this.

**Comment by worldtiki** [comment]
Any movement on this? :)

I'm sure @thanus will be happy to contribute a change with this fix.

**Comment by marcingrzejszczak** [comment]
If anybody's interesting in doing a PR with this then please be my guest. I wonder if Brave would be interesting in having the valve instrumentation in their repo cc @adriancole ?

**Comment by amexboy** [comment]
```
@Component
public class AddTraceIDToHeaderFilter implements Filter {


    public static final String TRACE_ID_HEADER_NAME = "X-B3-TraceId";

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {


        HttpServletResponse httpRes = (HttpServletResponse) response;
        TraceContext traceContext = (TraceContext) request.getAttribute(TraceContext.class.getName());

        if (traceContext != null && httpRes.getHeader(TRACE_ID_HEADER_NAME) == null) {
            httpRes.addHeader(TRACE_ID_HEADER_NAME, traceContext.traceIdString());
        }

        chain.doFilter(request, response);
    }
}

```

This is the solution I am using currently.

**Comment by tomaszc** [comment]
This problem applies also to Jetty access-logs

**Comment by madjaye** [comment]
Hi, just wondering if there has been any movement on this? The SleuthValve workaround seems to fall over when it comes to POST requests for me. I am seeing a NPE being thrown pretty deep in the stack. GET requests on the other hand seem to work just fine. 
I am on:
- Spring Boot 2.4.3
- Spring Cloud 2020.0.1
- Spring Cloud Sleuth 3.0.1
- logback-core/logback-access 1.2.3
- logback-encoder 6.0.

```
java.lang.NullPointerException: null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at org.springframework.security.web.firewall.StrictHttpFirewall.lambda$static$1(StrictHttpFirewall.java:122)
	at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest.validateAllowedHeaderValue(StrictHttpFirewall.java:738)
	at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest.access$000(StrictHttpFirewall.java:605)
	at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest$1.nextElement(StrictHttpFirewall.java:647)
	at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest$1.nextElement(StrictHttpFirewall.java:637)
	at org.springframework.http.server.ServletServerHttpRequest.getHeaders(ServletServerHttpRequest.java:148)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:153)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:158)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:131)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:170)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.cloud.sleuth.instrument.web.servlet.TracingFilter.doFilter(TracingFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:129)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.cloud.sleuth.instrument.web.servlet.TracingFilter.doFilter(TracingFilter.java:89)
	at org.springframework.cloud.sleuth.autoconfig.instrument.web.LazyTracingFilter.doFilter(TraceWebServletConfiguration.java:121)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
	at uk.co.bar.foo.SleuthValve.invoke(SleuthValve.java:29)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Anyone else using the workaround seeing anything similar? Does anyone have something working for POST requests?

**Comment by madjaye** [comment]
> Anyone else using the workaround seeing anything similar? Does anyone have something working for POST requests?

Apologies, looks like the issue was actually caused by attempting to also set a `parentSpanId` (which in this context is `null`) to the `MimeHeaders`. So it is actually working fine.

**Comment by marcingrzejszczak** [comment]
So is this still a problem or not?

**Comment by madjaye** [comment]
It is not a problem in that the `SleuthValve` workaround described by @thanus above works (with some tweaks to make it work with latest dependency versions). But the original "problem" does still exist...

**Comment by marcingrzejszczak** [comment]
I'm so sorry that it took me that long. Please check out 3.1.0-SNAPSHOT version https://github.com/spring-cloud/spring-cloud-sleuth/commit/2dd82624e597d1dd39104fcd428701dc6d672be6
