### ISSUE TITLE
Google Stackdriver Trace drops spans without name

### ISSUE THREAD

**Issue by TYsewyn** [spring-cloud/spring-cloud-sleuth#1337]
When enabling debug logging for the `zipkin2` package we get see following error:
```
Dropped 18 spans due to StatusRuntimeException(INVALID_ARGUMENT: TraceSpan.name for TraceSpan.span_id 1829621750604935860 cannot be empty.)
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: TraceSpan.name for TraceSpan.span_id 1829621750604935860 cannot be empty.
at io.grpc.Status.asRuntimeException(Status.java:526)
at zipkin2.reporter.stackdriver.internal.AwaitableUnaryClientCallListener.onClose(AwaitableUnaryClientCallListener.java:96)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

A first quick check is pointing to the following:
- `TracingChannelInterceptor`, where the `beforeHandle` method is starting a consumer span without a name.
- `TraceLoadBalancerFeignClient`, where the started `fallbackSpan` in the `execute` method doesn't have a name.
- `MonoWebFilterTrace`, where a new child span is started without a name if there was already one in the context.

What would be the sane defaults for these created spans? I'll create a new PR with the changes once I know these.

**Comment by adriancole** [comment]
this should be an issue on the zipkin-grpc repo

**Comment by TYsewyn** [comment]
@marcingrzejszczak @adriancole What is the added benefit to start and immediately finish a consumer span in `TracingChannelInterceptor`? 🤔
See https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptor.java#L306 and

![image](https://user-images.githubusercontent.com/6283320/56589373-5f29c580-65e5-11e9-9b27-54121cac1c31.png)

**Comment by devinsba** [comment]
Message tracing works differently because of the one-to-many, we need to enable other consumers to also work on the same span. So we don't reuse the span, we just mark that we touched it and create a child where work is done.

**Comment by adriancole** [comment]
agree with brian. what's probably not intuitive is that we are fitting
the messaging model even if we don't have visibility into the
separation of consumption vs processing (because the consumer layer
isn't instrumented). It is important to model consistently for tooling
even if we have to "fake it" sometimes.
