### ISSUE TITLE
Spring Cloud Sleuth in combination with custom keystore & truststore?

### ISSUE THREAD

**Issue by bbzg** [spring-cloud/spring-cloud-sleuth#1369]
When using Spring Cloud Sleuth in combination with a custom keystore & truststore, I get the following exception:

```
org.springframework.ws.client.WebServiceIOException: I/O error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:561)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:383)
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:373)
        ...
```

I use `SSLContext.setDefault(context);` to set a custom SSL context on Spring startup. I need to do this because I have a third party client that requires a custom keystore & truststore.

I have been trying to figure out how to configure WebServiceTemplate in combination with Spring Cloud Sleuth to not throw an exception, but as far as I can tell this does not seem to be supported(?)

It seems like there is something happening in the Sleuth filters that makes the request fail with a custom keystore & truststore.

Our configuration :
* `mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Greenwich.RELEASE'`
* `implementation 'org.springframework.cloud:spring-cloud-starter-sleuth'`
* `implementation 'org.springframework.cloud:spring-cloud-gcp-starter-trace'`

Hopefully this is not a bug in Spring Cloud Sleuth, just a misconfiguration on our part, but it might be a bug, so that's why I posted it here instead of on StackOverflow.

Thank you!

**Comment by bbzg** [comment]
After digging around a bit more, I learned that I could use this method:

```
    WebServiceGatewaySupport client = // Client already exists
    KeyManagerFactory keyManagerFactory = // set up using keystore
    TrustManagerFactory trustManagerFactory = // set up using truststore

    // Configure a HttpsUrlConnectionMessageSender to handle SSL instead of a default SSLContext
    HttpsUrlConnectionMessageSender messageSender = new HttpsUrlConnectionMessageSender();
    messageSender.setKeyManagers(keyManagerFactory.getKeyManagers());
    messageSender.setTrustManagers(trustManagerFactory.getTrustManagers());
    client.setMessageSender(messageSender);
```

All this probably has little to do with Sleuth, but for passers through it might come in handy for other reasons.

This is where I found the answer: https://zoltanaltfatter.com/2016/04/30/soap-over-https-with-client-certificate-authentication/
