### ISSUE TITLE
After Mono.timeout() is called, IllegalStateException happens

### ISSUE THREAD

**Issue by kktn-FW** [spring-cloud/spring-cloud-sleuth#1470]
Hi all,

I'm using Spring Cloud Sleuth and [Spring Webflux](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux) in the same application.

As I wrote in the title, after [Mono.timeout()](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#timeout-java.time.Duration-reactor.core.publisher.Mono-) is called, when the application receives another request immediately, `IllegalStateException` happens. According to error messages, it seems that spring-cloud-sleuth-core causes this issue.
These are error messages.

```
2019-10-16 16:34:10.608 ERROR [frontend,075ca41282392e78,075ca41282392e78,false] 19278 --- [     parallel-4] reactor.core.publisher.Operators         : Operator called default onErrorDroppedIDLE

java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-4
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:77) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.Mono.block(Mono.java:1494) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.data.redis.connection.ReactiveRedisConnection.close(ReactiveRedisConnection.java:60) ~[spring-data-redis-2.1.10.RELEASE.jar:2.1.10.RELEASE]
        at org.springframework.data.redis.core.ReactiveRedisTemplate.lambda$doInConnection$3(ReactiveRedisTemplate.java:198) ~[spring-data-redis-2.1.10.RELEASE.jar:2.1.10.RELEASE]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.cancel(FluxDoFinally.java:145) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.cancel(MonoReduceSeed.java:96) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:167) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.cancel(FluxDoOnEach.java:102) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.Operators.terminate(Operators.java:1044) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.cancel(FluxFlatMap.java:979) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.unsubscribeEntry(FluxFlatMap.java:304) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.unsubscribeEntry(FluxFlatMap.java:182) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FlatMapTracker.unsubscribe(FluxFlatMap.java:1039) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.cancel(FluxFlatMap.java:324) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.cancel(MonoCollectList.java:146) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:167) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.Operators.terminate(Operators.java:1044) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.MonoZip$ZipInner.cancel(MonoZip.java:365) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.MonoZip$ZipCoordinator.cancel(MonoZip.java:256) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxFilter$FilterSubscriber.cancel(FluxFilter.java:184) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:167) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.Operators.terminate(Operators.java:1044) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:180) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.cancel(FluxPeekFuseable.java:153) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:167) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1867) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:292) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:70) [spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]

```

```
2019-10-16 16:34:10.632 ERROR [frontend,075ca41282392e78,26b2089190f36382,false] 19278 --- [     parallel-4] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-4
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:77) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.Mono.block(Mono.java:1494) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.data.redis.connection.ReactiveRedisConnection.close(ReactiveRedisConnection.java:60) ~[spring-data-redis-2.1.10.RELEASE.jar:2.1.10.RELEASE]
        at org.springframework.data.redis.core.ReactiveRedisTemplate.lambda$doInConnection$3(ReactiveRedisTemplate.java:198) ~[spring-data-redis-2.1.10.RELEASE.jar:2.1.10.RELEASE]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.cancel(FluxDoFinally.java:145) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.cancel(MonoReduceSeed.java:96) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:167) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.cancel(FluxDoOnEach.java:102) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.Operators.terminate(Operators.java:1044) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.cancel(FluxFlatMap.java:979) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.unsubscribeEntry(FluxFlatMap.java:304) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.unsubscribeEntry(FluxFlatMap.java:182) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FlatMapTracker.unsubscribe(FluxFlatMap.java:1039) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.cancel(FluxFlatMap.java:324) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.cancel(MonoCollectList.java:146) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:167) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.Operators.terminate(Operators.java:1044) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.MonoZip$ZipInner.cancel(MonoZip.java:365) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.MonoZip$ZipCoordinator.cancel(MonoZip.java:256) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxFilter$FilterSubscriber.cancel(FluxFilter.java:184) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:167) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.Operators.terminate(Operators.java:1044) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:180) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.cancel(FluxPeekFuseable.java:153) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:167) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1867) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:292) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) ~[reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27) [reactor-core-3.2.11.RELEASE.jar:3.2.11.RELEASE]
        at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:70) ~[spring-cloud-sleuth-core-2.1.4.RELEASE.jar:2.1.4.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]

```

I verified that if I didn't import `spring-cloud-starter-sleuth`, this error didn't happen.

My environments are following.
- org.springframework.boot:spring-boot-starter-actuator -> 2.1.7.RELEASE
- org.springframework.boot:spring-boot-starter-webflux -> 2.1.7.RELEASE
- org.springframework.cloud:spring-cloud-starter-sleuth -> 2.1.4.RELEASE
  - org.springframework.cloud:spring-cloud-sleuth-core:2.1.4.RELEASE 

I would appreciate it if you could give me some advices or fix this issue.

**Comment by robotmrv** [comment]
@kktn-FW , it seems this is Spring Data Redis issue  
please see https://jira.spring.io/browse/DATAREDIS-965 and https://jira.spring.io/browse/DATAREDIS-999
it appears with Sleuth because it instruments all reactor publishers with `reactor.core.publisher.Hooks#onEachOperator` which "overrides" `block()` from `ReactiveRedisConnection.close`.  
As WA for operations with Redis you can apply `reactor.core.publisher.Mono#cancelOn` operator with elastic scheduler.

**Comment by kktn-FW** [comment]
@robotmrv Thank you very much for your advice. I will check Spring Data Redis. For now, I'll close this issue.
