### ISSUE TITLE
Zipkin Exception "bean named 'output' that could not be found"

### ISSUE THREAD

**Issue by FWinkler79** [spring-cloud/spring-cloud-sleuth#1472]
I am using ...
**Spring Boot:** 2.2.0.RELEASE
**Spring Cloud:** Hoxton.M3
... and the following dependencies to run an RSocket server that integrates with Eureka and with a running Zipkin instance (from a docker image):

```xml
 <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-amqp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-rsocket</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-bus</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zipkin</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream-binder-rabbit</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope> <!-- See: https://projectlombok.org/setup/maven -->
    </dependency>
```

When I start the server, I get the following errors:
```
2019-10-17 18:53:21.321  WARN [rsocket-server,,,] 14045 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionInitializer' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'output' available
2019-10-17 18:53:21.322  INFO [rsocket-server,,,] 14045 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2019-10-17 18:53:21.345  WARN [rsocket-server,,,] 14045 --- [pool-8-thread-1] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eurekaRibbonClientConfiguration': Unsatisfied dependency expressed through field 'clientConfig'; nested exception is org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaClientConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
2019-10-17 18:53:21.814  WARN [rsocket-server,,,] 14045 --- [ender@4687366b}] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eurekaRibbonClientConfiguration': Unsatisfied dependency expressed through field 'clientConfig'; nested exception is org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaClientConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
2019-10-17 18:53:21.815  WARN [rsocket-server,,,] 14045 --- [ender@4687366b}] z.r.AsyncReporter$BoundedAsyncReporter   : Spans were dropped due to exceptions. All subsequent errors will be logged at FINE level.
2019-10-17 18:53:21.816  WARN [rsocket-server,,,] 14045 --- [ender@4687366b}] z.r.AsyncReporter$BoundedAsyncReporter   : Dropped 0 spans due to UnsatisfiedDependencyException(Error creating bean with name 'eurekaRibbonClientConfiguration': Unsatisfied dependency expressed through field 'clientConfig'; nested exception is org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaClientConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!))

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eurekaRibbonClientConfiguration': Unsatisfied dependency expressed through field 'clientConfig'; nested exception is org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaClientConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:397) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1429) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:136) ~[spring-cloud-context-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:101) ~[spring-cloud-context-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getContext(SpringClientFactory.java:131) ~[spring-cloud-netflix-ribbon-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.context.named.NamedContextFactory.getInstance(NamedContextFactory.java:145) ~[spring-cloud-context-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getInstance(SpringClientFactory.java:121) ~[spring-cloud-netflix-ribbon-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getLoadBalancer(SpringClientFactory.java:65) ~[spring-cloud-netflix-ribbon-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.getLoadBalancer(RibbonLoadBalancerClient.java:193) ~[spring-cloud-netflix-ribbon-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.choose(RibbonLoadBalancerClient.java:88) ~[spring-cloud-netflix-ribbon-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.choose(RibbonLoadBalancerClient.java:78) ~[spring-cloud-netflix-ribbon-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.sleuth.zipkin2.sender.LoadBalancerClientZipkinLoadBalancer.instance(LoadBalancerClientZipkinLoadBalancer.java:43) ~[spring-cloud-sleuth-zipkin-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration$1.zipkinUrl(ZipkinRestTemplateSenderConfiguration.java:71) ~[spring-cloud-sleuth-zipkin-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateWrapper.doExecute(ZipkinRestTemplateSenderConfiguration.java:174) ~[spring-cloud-sleuth-zipkin-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:644) ~[spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender.post(RestTemplateSender.java:129) ~[spring-cloud-sleuth-zipkin-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender$HttpPostCall.doExecute(RestTemplateSender.java:142) ~[spring-cloud-sleuth-zipkin-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender$HttpPostCall.doExecute(RestTemplateSender.java:132) ~[spring-cloud-sleuth-zipkin-2.2.0.M3.jar:2.2.0.M3]
	at zipkin2.Call$Base.execute(Call.java:380) ~[zipkin-2.17.0.jar:na]
	at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:285) ~[zipkin-reporter-2.10.3.jar:na]
	at zipkin2.reporter.AsyncReporter$Flusher.run(AsyncReporter.java:354) ~[zipkin-reporter-2.10.3.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaClientConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:208) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:276) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:636) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 32 common frames omitted

2019-10-17 18:53:21.822  WARN [rsocket-server,,,] 14045 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'reactorServerResourceFactory': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'tracing': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
2019-10-17 18:53:21.835  INFO [rsocket-server,,,] 14045 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-10-17 18:53:21.835  INFO [rsocket-server,,,] 14045 --- [           main] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application RSOCKET-SERVER with eureka with status DOWN
2019-10-17 18:53:21.896 ERROR [rsocket-server,,,] 14045 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'output' that could not be found.


Action:

Consider defining a bean named 'output' in your configuration.
```

This works in `Hoxton.M1` but fails in `Hoxton.M3`.

A sample project showing this can be found [here](https://github.com/FWinkler79/SpringCloudPlatform/tree/Issue-Spring-Cloud-Hoxton-M3).

To reproduce:
1. start zipkin (`./scripts/startZipkin.sh`) - requires docker
1. start RabbitMQ (`./scripts/startRabbit.sh`) - requires docker
1. start `service-registry`
1. start `config-server`
1. start `rsocket-server`

**Comment by marcingrzejszczak** [comment]
Can you check with the latest snapshots to see if the problem is still there? Some work was done around rabbit and span sending in the meantime

**Comment by FWinkler79** [comment]
Thanks @marcingrzejszczak,

I just pulled up the versions in the issue branch to the latest snapshots, but the problem still persists.
The output (when starting up the RSocket server) is:

```
2019-11-15 12:16:05.922  INFO [rsocket-server,,,] 18263 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$e9c47485] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-15 12:16:05.985  INFO [rsocket-server,,,] 18263 --- [           main] o.s.c.n.eureka.InstanceInfoFactory       : Setting initial instance status as: STARTING
2019-11-15 12:16:06.012  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
2019-11-15 12:16:06.127  INFO [rsocket-server,,,] 18263 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2019-11-15 12:16:06.127  INFO [rsocket-server,,,] 18263 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/Users/d056076/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-11-15 12:16:06.201  INFO [rsocket-server,,,] 18263 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2019-11-15 12:16:06.201  INFO [rsocket-server,,,] 18263 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2019-11-15 12:16:06.299  INFO [rsocket-server,,,] 18263 --- [           main] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2019-11-15 12:16:06.309  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2019-11-15 12:16:06.309  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2019-11-15 12:16:06.309  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2019-11-15 12:16:06.309  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : Application is null : false
2019-11-15 12:16:06.309  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2019-11-15 12:16:06.309  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2019-11-15 12:16:06.309  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2019-11-15 12:16:06.404  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : The response status is 200
2019-11-15 12:16:06.405  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : Not registering with Eureka server per configuration
2019-11-15 12:16:06.409  INFO [rsocket-server,,,] 18263 --- [           main] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1573816566408 with initial instances count: 1
2019-11-15 12:16:06.437  INFO [rsocket-server,,,] 18263 --- [           main] o.s.c.n.e.s.EurekaServiceRegistry        : Registering application RSOCKET-SERVER with eureka with status UP

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.0.RELEASE)

2019-11-15 12:16:06.476  INFO [rsocket-server,,,] 18263 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://c02x82h7jgh6.dhcp.wdf.sap.corp:1111/
2019-11-15 12:16:07.057  INFO [rsocket-server,,,] 18263 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=rsocket-server, profiles=[default], label=null, version=bdbc41cd0af51d3b2a64eb8f4483219df2a31ce3, state=null
2019-11-15 12:16:07.057  INFO [rsocket-server,,,] 18263 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: OriginTrackedCompositePropertySource {name='configService', propertySources=[MapPropertySource {name='configClient'}, OriginTrackedMapPropertySource {name='https://github.com/FWinkler79/SpringCloudPlatform-Configs.git/application.yml'}]}
2019-11-15 12:16:07.076  INFO [rsocket-server,,,] 18263 --- [           main] c.e.c.r.server.RsocketServerApplication  : No active profile set, falling back to default profiles: default
2019-11-15 12:16:07.472  WARN [rsocket-server,,,] 18263 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'bus-env' contains invalid characters, please migrate to a valid format.
2019-11-15 12:16:07.577  WARN [rsocket-server,,,] 18263 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'bus-refresh' contains invalid characters, please migrate to a valid format.
2019-11-15 12:16:07.616  WARN [rsocket-server,,,] 18263 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
2019-11-15 12:16:07.760  INFO [rsocket-server,,,] 18263 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=c9b902e3-b4e5-305b-a881-73d62d50a36a
2019-11-15 12:16:07.800  INFO [rsocket-server,,,] 18263 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2019-11-15 12:16:07.803  INFO [rsocket-server,,,] 18263 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
2019-11-15 12:16:07.805  INFO [rsocket-server,,,] 18263 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2019-11-15 12:16:07.928  INFO [rsocket-server,,,] 18263 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationChannelResolver' of type [org.springframework.integration.support.channel.BeanFactoryChannelResolver] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-15 12:16:07.932  INFO [rsocket-server,,,] 18263 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationDisposableAutoCreatedBeans' of type [org.springframework.integration.config.annotation.Disposables] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-15 12:16:07.949  INFO [rsocket-server,,,] 18263 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-15 12:16:07.955  INFO [rsocket-server,,,] 18263 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration$IntegrationJmxConfiguration' of type [org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration$IntegrationJmxConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-15 12:16:07.961  INFO [rsocket-server,,,] 18263 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration' of type [org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-15 12:16:07.964  INFO [rsocket-server,,,] 18263 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mbeanServer' of type [com.sun.jmx.mbeanserver.JmxMBeanServer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-15 12:16:07.989  INFO [rsocket-server,,,] 18263 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$e9c47485] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-15 12:16:07.992  INFO [rsocket-server,,,] 18263 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.sleuth.instrument.web.client.TraceWebClientAutoConfiguration$NettyConfiguration' of type [org.springframework.cloud.sleuth.instrument.web.client.TraceWebClientAutoConfiguration$NettyConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-15 12:16:08.741  INFO [rsocket-server,,,] 18263 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2019-11-15 12:16:08.846  INFO [rsocket-server,,,] 18263 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 22 endpoint(s) beneath base path '/actuator'
2019-11-15 12:16:09.031  INFO [rsocket-server,,,] 18263 --- [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : Looking up function 'null' with acceptedOutputTypes: []
2019-11-15 12:16:09.036  WARN [rsocket-server,,,] 18263 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionInitializer' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'output' available
2019-11-15 12:16:09.037  INFO [rsocket-server,,,] 18263 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2019-11-15 12:16:09.588  WARN [rsocket-server,,,] 18263 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'reactorServerResourceFactory': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'tracing': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
2019-11-15 12:16:09.603  INFO [rsocket-server,,,] 18263 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-11-15 12:16:09.603  INFO [rsocket-server,,,] 18263 --- [           main] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application RSOCKET-SERVER with eureka with status DOWN
2019-11-15 12:16:09.666 ERROR [rsocket-server,,,] 18263 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'output' that could not be found.


Action:

Consider defining a bean named 'output' in your configuration.
```

**Comment by marcingrzejszczak** [comment]
I have removed `starter-zipkin` from the classpath and the problem persists. The problem is related with Spring Cloud Stream / Function (`org/springframework/cloud/stream/function/FunctionConfiguration.class`) cc @olegz 

```
2019-11-20 11:32:05.148  WARN 13759 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionInitializer' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'output' available
```

**Comment by bibibiu2017** [comment]
I can confirm it is not a problem with Zipkin. It is a problem with cloud stream. I am on spring-boot 2.2.2 and spring cloud dependency Hoxton.RELEASE and experiencing the same issue. To solve it this is what I 
created a supplier bean. I think @marcingrzejszczak  is right.  
`Bean
    Supplier<String> output() {
        return () -> "¯\\_(ツ)_/¯";
    }`
