### ISSUE TITLE
BlockHound detects Blocking call inside zipkin2.reporter.AsyncReporter in NonBlocking Thread

### ISSUE THREAD

**Issue by robotmrv** [spring-cloud/spring-cloud-sleuth#1491]
My test WebFlux application detects blocking call in `zipkin2.reporter.AsyncReporter` 
Please take a look at https://github.com/robotmrv/sleuth-blocks  
TC
1. run application
2. curl http://localhost:8080/test 
3. check logs 
```
Blocking Call inside: jdk.internal.misc.Unsafe#park in Thread: Thread[reactor-http-nio-5,5,main]
java.lang.Error
	at com.example.demo.SleuthBlocksApplication.logBlocking(SleuthBlocksApplication.java:57)
	at reactor.blockhound.BlockHound$Builder.lambda$install$6(BlockHound.java:318)
	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:46)
	at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
	at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
	at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
	at zipkin2.reporter.ByteBoundedQueue.offer(ByteBoundedQueue.java:51)
	at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.report(AsyncReporter.java:244)
	at org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration$CompositeReporter.report(TraceAutoConfiguration.java:246)
	at org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration$CompositeReporter.report(TraceAutoConfiguration.java:225)
	at brave.internal.handler.ZipkinFinishedSpanHandler.handle(ZipkinFinishedSpanHandler.java:51)
	at brave.internal.handler.NoopAwareFinishedSpanHandler$Multiple.doHandle(NoopAwareFinishedSpanHandler.java:105)
	at brave.internal.handler.NoopAwareFinishedSpanHandler.handle(NoopAwareFinishedSpanHandler.java:59)
	at brave.RealSpan.finish(RealSpan.java:151)
	at brave.RealSpan.finish(RealSpan.java:143)
	at brave.http.HttpHandler.finishInNullScope(HttpHandler.java:73)
	at brave.http.HttpHandler.handleFinish(HttpHandler.java:64)
	at brave.http.HttpClientHandler.handleReceive(HttpClientHandler.java:188)
	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace$WebClientTracerSubscriber.handleReceive(TraceWebClientBeanPostProcessor.java:346)
	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace$WebClientTracerSubscriber.terminateSpan(TraceWebClientBeanPostProcessor.java:381)
	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace$WebClientTracerSubscriber.onNext(TraceWebClientBeanPostProcessor.java:313)
	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace$WebClientTracerSubscriber.onNext(TraceWebClientBeanPostProcessor.java:245)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2148)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:143)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:237)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8134)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:82)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
	at reactor.netty.http.client.HttpClientConnect$HttpObserver.onStateChange(HttpClientConnect.java:397)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:473)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:526)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:435)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:522)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:313)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:427)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by spencergibb** [comment]
Can you check against the latest Hoxton.SR6?

**Comment by robotmrv** [comment]
@spencergibb   
it reproduces with `Hoxton.SR6`

**Comment by marcingrzejszczak** [comment]
Sleuth is reusing Brave's `AsyncReporter`. Is it possible that `AsyncReporter` is not really that async? cc @adriancole

**Comment by adriancole** [comment]
it is complaining that it is entering a lock to write to an array. I don't know what blockhound is forbidding, but if it forbids use of java locks, then yeah this wouldn't work. @bsideup ?

**Comment by adriancole** [comment]
ps if someone wants to volunteer for this that can use the same senders (ex similar to zipkin-reporter-brave) feel free https://github.com/openzipkin/zipkin-reporter-java/issues/81

**Comment by adriancole** [comment]
also, my guess is reporting levels of this high level will overload any known storage backend, so curious also if non-demo environments have seen this in an environment that can process the data. We've never seen a report like this so far.

**Comment by robotmrv** [comment]
@adriancole  
Initially I found blocking calls on my dev environment, which is not very loaded, but it was less frequent.  
The demo app uses such request rate just to simplify reproduction.  
Anyway, I thought that the main reason of using webflux is to make applications with high throughput

**Comment by adriancole** [comment]
the default sample rate is 100/s I think? this only affects sampled spans.

**Comment by adriancole** [comment]
at any rate something is pie in the sky unless someone makes time to do an alternative. zipkin is a volunteer project and I don't know anyone who has time, but if you do feel free!

**Comment by adriancole** [comment]
also @bsideup I this this is miscategorizing https://github.com/reactor/BlockHound I think the intent is to ensure things don't stick. possibly the fact that the default format of json is slower to calculate size vs  proto for example.. if someone wanted to use a more efficient codec it would be better. in any case there's no risk of actual I/O, this is just being sensitive to the existence of a lock. There are a million things with higher priority such as all the bugs in the reactor tracing, context lost etc. I'd probably focus on deprioritizing this message as it is noise.

**Comment by adriancole** [comment]
>  Anyway, I thought that the main reason of using webflux is to make applications with high throughput

I'm not trying to be argumentative, but let's be clear that possibly most users accidentally use webflux for things that are very low throughput. Lots of content steer newbies directly into webflux.

The default reporter is basically bug free at this point. I've watch disruptor based impls in census collect strange bugs, reactive statsd things take months to make etc. If someone is using webflux doesn't mean they should inherit the most likely to break options. That said I wouldn't argue a "performance pack' should be impossible, and of course someone can do that now. You could make a disruptor to intermediate the existing span handler (ex one that wraps the first). This would be senseless without looking at span format (ex proto would make a lot more sense) and also, most importantly, the backend would need to ingest all of this.

promoting boundless sampling etc only makes sense big picture if the whole thing would work with that. Ex if we had a disruptor option, probably what we'd say in the javadoc that this only makes sense with infrastructure to absorb the traffic.. ex those using most saas won't be able to do that, hence be fine with the first.

anyway trying to add color to while finding something that can be saturated is fun engineering, it isn't necessarily going to end up useful if it just makes backends fall over faster or race to GC. a bigger picture thing would be nice, just yeah I remember the statsd micrometer thing taking months. No idea how much interest there is outside this thread, as we've tried to corrale interest in the past and no one stood forward.

hope the background helps prioritize and sincerely interested if someone wants to make a special-cased non-blocking reporter.. just they'd have to support the bugs, api drift etc in that as they arise.

**Comment by marcingrzejszczak** [comment]
let's close this ticket until we prove that this is actually an issue
