### ISSUE TITLE
java.lang.ClassCastException when getting nativeHeaders

### ISSUE THREAD

**Issue by yumingtao** [spring-cloud/spring-cloud-sleuth#1503]
Dependencies:
spring-cloud-seluth-2.1.1.RELEASE
spring-cloud-azure-eventhubs-stream-binder-1.1.0.RC5

It is a Azure eventhub demo, sent a message to eventhub and comsume it, but got below exception when comsuming data from eventhub. I debug it and find that when using sleuth, it will add nativeHeaders(eg.**{X-B3-TraceId=[915f7baedd220522], spanTraceId=[915f7baedd220522], X-B3-SpanId=[980d03a075f5d148], spanId=[980d03a075f5d148], X-B3-ParentSpanId=[915f7baedd220522], spanParentSpanId=[915f7baedd220522], X-B3-Sampled=[0], spanSampled=[0]}**) to the Meaasge object when send message to eventhub, and get exception in HeaderMethodArgumentResolver.getNativeHeaders when comsuming it.
I tried to use different spring-cloud-seluth and spring-cloud-stream version, but still have the issue, I must use spring-cloud-seluth for logging, so colud you please help to check it, thanks a lot.

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaders(HeaderMethodArgumentResolver.java:98) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaderValue(HeaderMethodArgumentResolver.java:85) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.resolveArgumentInternal(HeaderMethodArgumentResolver.java:69) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.annotation.support.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:100) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:147) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55) ~[spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]

The exception code in spring-messaging:
	@SuppressWarnings("unchecked")
	private Map<String, List<String>> getNativeHeaders(Message<?> message) {
		return (Map<String, List<String>>) message.getHeaders().get(
				NativeMessageHeaderAccessor.NATIVE_HEADERS);
	}

**Comment by marcingrzejszczak** [comment]
Is rc2 compatible with that version of spring cloud sleuth 2.2.1?

**Comment by yumingtao** [comment]
> Is rc2 compatible with that version of spring cloud sleuth 2.2.1?

You mean spring-cloud-azure-eventhubs-stream-binder-1.1.0.RC2 with spring-cloud-seluth-2.1.1.RELEASE? 

Yes I test it, it works well, I can change the azure dependency to 1.1.0.RC2, thank you.

And for using azure 1.1.0.RC5, I add an ChannelInterceptor and remove nativeHeaders in preSend() method as a workaround, I know it is not a good idea. But if is convenient, I want to know why it is incompatible for 1.1.0.RC5 and sleuth, thank a lot.

**Comment by marcingrzejszczak** [comment]
You should file the issue in their repo not here since they should be compatible with us not the other way round.

**Comment by chen-junl** [comment]
使用@StreamListener接收message消息的时候nativeHeaders会类型转换错误
sleuth版本3.1.1
` nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map, failedMessage=GenericMessage [payload=byte[8046], headers={ROCKET_MQ_FLAG=0, ROCKET_MQ_SYS_FLAG=1, ROCKET_MQ_QUEUE_ID=0, ROCKET_KEYS=guoyuan_1, b3=bfcdb2c19ef0cf56-cdadcbafa0bd3306-1, nativeHeaders={b3=[bfcdb2c19ef0cf56-e0ae6cf0e4e0b29c-1]}, ROCKET_TAGS=resource_guoyuan, ROCKET_MQ_BORN_TIMESTAMP=1675068604407, ROCKET_MQ_MESSAGE_ID=7F000001D81018B4AAC298F52BF30009, ROCKET_MQ_TOPIC=chenjl, METHOD=UPDATE, ROCKET_MQ_BORN_HOST=192.168.55.1, id=07e8bc20-fb08-0454-b52b-f04b1881fbe1, contentType=application/json, timestamp=1675068822634}]`
