### ISSUE TITLE
Getting weird proxy issue after adding sleuth dependency in pom

### ISSUE THREAD

**Issue by vikramadityasen** [spring-cloud/spring-cloud-sleuth#1506]
I am using spring boot 2.1.0 with spring cloud Greenwich.SR3. I am Getting below exception when I have added sleuth dependency into pom. I don't want to change the visibility of method because it is external jar I am using in project. 
Getting exception like:
Initialization of bean failed; nested exception is java.lang.IllegalStateException: Need to invoke method 'someMethod()' found on proxy for target class 'ImplementationClass' but cannot be delegated to target bean. Switch its visibility to package or protected.

**Comment by marcingrzejszczak** [comment]
When you created the issue you removed the following section:

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
>
> **Sample**
>If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Can you update your issue with the required details?

**Comment by vikramadityasen** [comment]
I am using spring boot 2.1.0 with spring cloud Greenwich.SR3. I am Getting below exception when I have added sleuth dependency into pom. I don't want to change the visibility of method because it is external jar I am using in project.
Getting exception like:
Initialization of bean failed; nested exception is java.lang.IllegalStateException: Need to invoke method 'someMethod()' found on proxy for target class 'ImplementationClass' but cannot be delegated to target bean. Switch its visibility to package or protected.

**Comment by marcingrzejszczak** [comment]
To begin with, please upgrade Boot and Cloud. 

Also can you paste the full stacktrace? I have no idea which class is failing, what is `someMethod()`, how is it called etc.

**Comment by vikramadityasen** [comment]
I have tried with upgraded versions but getting same issue. 

That method is private in external service (jar), which is called from our service. Below  is the complete stacktrace:

> java.lang.IllegalStateException: Need to invoke method 'loadCustomerGroupCaches' found on proxy for target class 'CommercialGroupUtilServiceImpl' but cannot be delegated to target bean. Switch its visibility to package or protected.
	at org.springframework.aop.support.AopUtils.selectInvocableMethod(AopUtils.java:137)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.createRunnable(ScheduledAnnotationBeanPostProcessor.java:511)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.processScheduled(ScheduledAnnotationBeanPostProcessor.java:378)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.lambda$null$1(ScheduledAnnotationBeanPostProcessor.java:359)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.lambda$postProcessAfterInitialization$2(ScheduledAnnotationBeanPostProcessor.java:359)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.postProcessAfterInitialization(ScheduledAnnotationBeanPostProcessor.java:358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:434)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1749)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
	... 54 common frames omitted

**Comment by marcingrzejszczak** [comment]
You shouldn't mark a private `@Scheduled` method. Please make it package scope or protected. If you don't want Sleuth to throw that exception you can set `spring.sleuth.scheduled.enabled` to `false` and not wrap such a bean.

**Comment by vikramadityasen** [comment]
Thanks! it is working after adding `spring.sleuth.scheduled.enabled=false`
