### ISSUE TITLE
Spring Cloud Sleuth has a required dependency on AspectJ

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-sleuth#1621]
Adding `spring-cloud-sleuth-core` to a Spring Boot application leads to the following:

```
Caused by: java.lang.NoClassDefFoundError: org/aspectj/weaver/tools/PointcutPrimitive
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.<clinit>(AspectJExpressionPointcut.java:91) ~[spring-aop-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getPointcut(ReflectiveAspectJAdvisorFactory.java:212) ~[spring-aop-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisor(ReflectiveAspectJAdvisorFactory.java:194) ~[spring-aop-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisors(ReflectiveAspectJAdvisorFactory.java:126) ~[spring-aop-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.aop.aspectj.annotation.BeanFactoryAspectJAdvisorsBuilder.buildAspectJAdvisors(BeanFactoryAspectJAdvisorsBuilder.java:110) ~[spring-aop-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:95) ~[spring-aop-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:101) ~[spring-aop-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:251) ~[spring-aop-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1141) ~[spring-beans-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1114) ~[spring-beans-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:506) ~[spring-beans-5.2.6.BUILD-20200423.171221-90.jar:5.2.6.BUILD-SNAPSHOT]
	... 36 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.aspectj.weaver.tools.PointcutPrimitive
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_232]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_232]
	... 47 common frames omitted
```

Debugging, this is related to the use of `@Aspect` that requires AspectJ. `TraceSchedulingAutoConfiguration` is opting-in for AspectJ but does not enforce that with a class check.

I think this should be revisited to either back-off or provide AspectJ by default. I've added a condition on my end to back-off if AspectJ isn't available.

**Comment by adriancole** [comment]
sorry what do you mean by back off.

**Comment by spencergibb** [comment]
Conditional on class some class from aspectj

**Comment by adriancole** [comment]
gotit (ps sorry about missing things, I forgot I set watch to releases only a couple months ago! 😊 )

**Comment by snicoll** [comment]
So there is a [class check condition on the bean method](https://github.com/spring-cloud/spring-cloud-sleuth/blob/6764f06c53e81e9844646c07995f8fade421c206/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/scheduling/TraceSchedulingAutoConfiguration.java#L51) but that's useless since the [class-level `@EnableAspectJAutoProxy`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/6764f06c53e81e9844646c07995f8fade421c206/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/scheduling/TraceSchedulingAutoConfiguration.java#L43) is going to trigger things before the condition gets a chance to be evaluated. 

If the intent was to back off if aspectJ is not present, then the condition should be moved elsewhere and a test where we simulate the removal of AspectJ (via a filtered `ClassLoader` for instance) should be added.

I should also note that this annotation is overriding what the AOP auto-configuration in Spring Boot does. Nothing wrong about doing that but it's doing that unilaterally in an auto-configuration so I don't think that was the original intent.

**Comment by adriancole** [comment]
mind raising a PR with the simplest way out, if that means deleting something works for me. If we have no test coverage to show that it is needed somehow, something will break and then we can add the missing tests.

**Comment by timtebeek** [comment]
Just opened up #1624 since the tests and fix were similar enough to https://github.com/spring-cloud/spring-cloud-sleuth/commit/fe63513b230768fa791f869b0bae10399deb73f9 to make this low effort, even though I've not used `TraceSchedulingAutoConfiguration` myself. So a slightly more stringent review might be needed to ensure the PR fixes the issue as desired. :)

**Comment by timtebeek** [comment]
This issue can likely be closed after https://github.com/spring-cloud/spring-cloud-sleuth/commit/75756fd0926fd842c592f3a4e02299433c1c711d ; The pull request that referenced this issue above was merged to master locally to fix up a last few checkstyle issues.

**Comment by adriancole** [comment]
we can close this as next release will take it. Thanks @timtebeek  and @snicoll
