### ISSUE TITLE
Flakey test: WebClientTests.shouldNotTagOnCancel

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#1635]
java.lang.AssertionError: 
The logs below show that the client didn't close the span and it was left until GC

Expecting empty but was:<[{"traceId":"35318d80e1b6e402","id":"35318d80e1b6e402","name":"foo","timestamp":1589528757331018,"localEndpoint":{"serviceName":"fooservice","ipv4":"192.168.16.3"},"annotations":[{"timestamp":1589528758291000,"value":"brave.flush"}]}]>
	at org.springframework.cloud.sleuth.instrument.web.client.integration.WebClientTests.shouldNotTagOnCancel(WebClientTests.java:390)

**Comment by adriancole** [comment]
First problem is that this test should be using a blocking handler IntegrationSpanHandler for example.

```
java.lang.AssertionError: 

Expecting empty but was:<TestSpanHandler{[{"traceId":"fed7b47544811a2a","id":"fed7b47544811a2a","name":"foo","timestamp":1589806347282028,"localEndpoint":{"serviceName":"fooservice"}}]}>
	at org.springframework.cloud.sleuth.instrument.web.client.integration.WebClientTests.shouldNotTagOnCancel(WebClientTests.java:368)
```
