### ISSUE TITLE
IndexOutOfBoundsException when setting custom sender

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#1637]
**Describe the bug**
@jennings1716 has been valiantly trying to use kinesis sender. If you follow the docs and override the bean it crashes

https://cloud.spring.io/spring-cloud-sleuth/reference/html/#overriding-the-auto-configuration-of-zipkin

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [zipkin2.reporter.Reporter]: Factory method 'reporter' threw exception; nested exception is java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 99 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_181]
	at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_181]
	at org.springframework.cloud.sleuth.zipkin2.ZipkinBackwardsCompatibilityAutoConfiguration$BackwardsCompatibilityConfiguration.reporter(ZipkinBackwardsCompatibilityAutoConfiguration.java:102) ~[spring-cloud-sleuth-zipkin-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 100 common frames omitted
```

Incidentally, if you also override the AsyncReporter, it is fine, but this is a bad experience also We will stop using AsyncReporter anyway so it is a bad idea to spaghetti around this bug.

**Sample**
set the sender as in the docs == crash, also set the async reporter == not crash

**Comment by marcingrzejszczak** [comment]
Is there an option to get a sample? I can't replicate this issue

**Comment by adriancole** [comment]
sorry I meant to say that if you want to reproduce it literally copy the part from the docs about the sender and not also override the reporter. This is quicker to the same failure vs using SQS dep.

Like so:
```java

  @Bean(ZipkinAutoConfiguration.SENDER_BEAN_NAME)
  MySender mySender() {
    return new MySender();
  }

  static class MySender extends Sender {

    private boolean spanSent = false;

    boolean isSpanSent() {
      return this.spanSent;
    }

    @Override
    public Encoding encoding() {
      return Encoding.JSON;
    }

    @Override
    public int messageMaxBytes() {
      return Integer.MAX_VALUE;
    }

    @Override
    public int messageSizeInBytes(List<byte[]> encodedSpans) {
      return encoding().listSizeInBytes(encodedSpans);
    }

    @Override
    public Call<Void> sendSpans(List<byte[]> encodedSpans) {
      this.spanSent = true;
      return Call.create(null);
    }

  }
```

**Comment by TYsewyn** [comment]
Hi @adriancole! Is this happening with `spring-cloud-sleuth-zipkin` or with the core dependency (and possibly another dep for eg. GCP tracing) and custom code?

**Comment by adriancole** [comment]
you can paste it into a basic project like this https://github.com/openzipkin/sleuth-webmvc-example (what I did was paste into the Frontend type then ran it)

**Comment by adriancole** [comment]
thanks!
