### ISSUE TITLE
NPE in WebClient on request cancel 

### ISSUE THREAD

**Issue by robotmrv** [spring-cloud/spring-cloud-sleuth#1688]
**Describe the bug**
Sleuth integration with WebClient produces NullPointerException in case of cancellation of a request. 

**Sample**
https://github.com/robotmrv/sleuth-webclient-npe

1. run application
```
java -Xmx64m -jar target/sleuth-webclient-npe-0.0.1-SNAPSHOT.jar
```
2. hit endpoint 
```
 curl http://localhost:8080/test
``` 
Expected Result: "timeOuted"     
Actual Result: request hangs and NPE in logs 

```
java.lang.NullPointerException: delegate.unwrap() == null
	at brave.http.HttpClientResponse$Adapter.<init>(HttpClientResponse.java:77) ~[brave-instrumentation-http-5.9.2.jar:na]
	at brave.http.HttpClientHandler.handleReceive(HttpClientHandler.java:184) ~[brave-instrumentation-http-5.9.2.jar:na]
	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace$WebClientTracerSubscriber.handleReceive(TraceWebClientBeanPostProcessor.java:363) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace$WebClientTracerSubscriber.terminateSpanOnCancel(TraceWebClientBeanPostProcessor.java:377) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace$WebClientTracerSubscriber$1.cancel(TraceWebClientBeanPostProcessor.java:303) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.cancel(ScopePassingSpanSubscriber.java:87) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1991) ~[reactor-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1887) ~[reactor-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace$WebClientTracerSubscriber.onSubscribe(TraceWebClientBeanPostProcessor.java:284) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:86) ~[reactor-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:163) ~[reactor-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:163) ~[reactor-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:64) ~[reactor-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:132) ~[reactor-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71) ~[spring-cloud-sleuth-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at reactor.core.publisher.MonoRetryPredicate.subscribe(MonoRetryPredicate.java:48) ~[reactor-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46) ~[reactor-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:332) ~[reactor-netty-0.8.19.RELEASE.jar:0.8.19.RELEASE]
	at reactor.core.publisher.MonoFlatMapMany.subscribe(MonoFlatMapMany.java:52) ~[reactor-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	...
```

*versions:*
spring-boot 2.1.15.RELEASE 
spring-cloud-dependencies Greenwich.SR6

This defect is present in 2.1.x branch and was fixed in 2.2.x branch (https://github.com/spring-cloud/spring-cloud-sleuth/pull/1548).  
Please backport it to the 2.1.x branch as it is impossible to use WebClient with enabled Sleuth integration

**Comment by marcingrzejszczak** [comment]
We are not maintaining 2.1.x branch anymore. Please upgrade to 2.2.x.
