### ISSUE TITLE
Spring Boot Web application does not start with spring-cloud-sleuth and spring-session-data-redis

### ISSUE THREAD

**Issue by mwinkels-onegini** [spring-cloud/spring-cloud-sleuth#1756]
**Describe the bug**
A Spring Boot Web application that uses both `spring-cloud-sleuth` and `spring-session-data-redis` throws an exception at start up and fails:
```
2020-10-21 16:33:27.217  WARN [,,,] 64681 --- [ioEventLoop-4-1] i.lettuce.core.protocol.DefaultEndpoint  : Unexpected exception during request: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'scopedTarget.defaultTraceSampler' defined in class path resource [org/springframework/cloud/sleuth/sampler/SamplerAutoConfiguration$RefreshScopedSamplerConfiguration.class]: Unsatisfied dependency expressed through method 'defaultTraceSampler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'spring.sleuth.sampler-org.springframework.cloud.sleuth.sampler.SamplerProperties': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'scopedTarget.defaultTraceSampler' defined in class path resource [org/springframework/cloud/sleuth/sampler/SamplerAutoConfiguration$RefreshScopedSamplerConfiguration.class]: Unsatisfied dependency expressed through method 'defaultTraceSampler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'spring.sleuth.sampler-org.springframework.cloud.sleuth.sampler.SamplerProperties': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	...
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:675) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at brave.sampler.Sampler$$EnhancerBySpringCGLIB$$99caf050.isSampled(<generated>) ~[brave-5.12.3.jar:na]
	at brave.Tracer.decorateContext(Tracer.java:279) ~[brave-5.12.3.jar:na]
	at brave.Tracer.newRootContext(Tracer.java:215) ~[brave-5.12.3.jar:na]
	at brave.Tracer.newTrace(Tracer.java:150) ~[brave-5.12.3.jar:na]
	at brave.Tracer.nextSpan(Tracer.java:502) ~[brave-5.12.3.jar:na]
	at io.lettuce.core.tracing.BraveTracing$BraveTracer.nextSpan(BraveTracing.java:267) ~[lettuce-core-5.3.4.RELEASE.jar:5.3.4.RELEASE]
	at io.lettuce.core.tracing.BraveTracing$BraveTracer.nextSpan(BraveTracing.java:274) ~[lettuce-core-5.3.4.RELEASE.jar:5.3.4.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:417) ~[lettuce-core-5.3.4.RELEASE.jar:5.3.4.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.write(CommandHandler.java:378) ~[lettuce-core-5.3.4.RELEASE.jar:5.3.4.RELEASE]
	...
Caused by: org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'spring.sleuth.sampler-org.springframework.cloud.sleuth.sampler.SamplerProperties': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	...
```
The exception occurs after a timeout.

**Sample**
The sample project is an empty project generated with Spring Initializr with `spring-session-data-redis`.
[sleuth-redis-session.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/5416713/sleuth-redis-session.zip)

**Comment by 727656494** [comment]
我也遇到了这个问题，使用@PostConstruct初始化redis + 使用zipkin就会造成redis超时，从而出现上面的错误；
换成CommandLineRunner方式初始化redis可以解决问题。

I also encountered this problem. Using @ postconstruct to initialize redis + using Zipkin will cause redis timeout, and the above error will appear;
The problem can be solved by initializing redis in commandlinerunner mode.


`Caused by: org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'spring.sleuth.sampler-org.springframework.cloud.sleuth.sampler.SamplerProperties': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
`

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysDictTypeServiceImpl': Invocation of init method failed; nested exception is org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
`

`Caused by: org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
`

**Comment by grtessman** [comment]
Just to add:  Seems like this works for me with Hoxton.RELEASE - Hoxton.SR4, but broke in Hoxton.SR5.

**Comment by marcingrzejszczak** [comment]
I fixed it. The fix will be available in Hoxton.SR10 and 2020.0.0-RC1
