### ISSUE TITLE
JMS ConnectionFactory wrapped into LazyXAConnectionFactory which doesn't work for JmsHealthIndicator, Weblogic runtime

### ISSUE THREAD

**Issue by pmihalcin** [spring-cloud/spring-cloud-sleuth#1834]
I have web application based on Spring Boot `2.1.0.RELEASE` and Spring Cloud Sleuth `2.1.7.RELEASE` (`mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR6'`).

When I deploy this application to Weblogic 12.2, it fails on `org.springframework.boot.actuate.jms.JmsHealthIndicator` with exception:

```
Caused by: java.lang.IllegalStateException: Unable to create indicator class org.springframework.boot.actuate.jms.JmsHealthIndicator for source interface javax.jms.ConnectionFactory
	at org.springframework.boot.actuate.autoconfigure.health.CompositeHealthIndicatorConfiguration.createHealthIndicator(CompositeHealthIndicatorConfiguration.java:64) ~[spring-boot-actuator-autoconfigure-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.actuate.autoconfigure.health.CompositeHealthIndicatorConfiguration.createHealthIndicator(CompositeHealthIndicatorConfiguration.java:45) ~[spring-boot-actuator-autoconfigure-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.actuate.autoconfigure.jms.JmsHealthIndicatorAutoConfiguration.jmsHealthIndicator(JmsHealthIndicatorAutoConfiguration.java:65) ~[spring-boot-actuator-autoconfigure-2.1.0.RELEASE.jar:2.1.0.RELEASE]
```
The reason for this failure is `org.springframework.cloud.sleuth.instrument.messaging.TracingConnectionFactoryBeanPostProcessor` which wraps `XAConnectionFactory` to `org.springframework.cloud.sleuth.instrument.messaging.LazyXAConnectionFactory#LazyXAConnectionFactory`.

`LazyXAConnectionFactory` can't be used for `JmsHealthIndicator` which expects `javax.jms.ConnectionFactory`.

When I add `spring.sleuth.messaging.jms.enabled=false`, application starts up properly.

Any idea how to overcome this issue?

Was it fixed in newer versions?

**Comment by pmihalcin** [comment]
This issue doesn't appear in Spring Cloud Sleuth `2.2.0.RELEASE` (`Hoxton.RELEASE`) and Spring Boot `2.2.1.RELEASE`. Sorry for the noise.
