### ISSUE TITLE
Warning on shutdown with Spring Cloud Gateway

### ISSUE THREAD

**Issue by trajano** [spring-cloud/spring-cloud-sleuth#1856]
**Describe the bug**

When I shut down the gateway, I get this warning when shutting down.

```
2021-02-22 20:59:43.118  WARN [gateway,,] 1 --- [extShutdownHook] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'reactorServerResourceFactory': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'braveTracer': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
```

There was another log entry which is ERROR that showed

```
2021-02-22 20:59:42.840 ERROR [gateway,,] 1 --- [or-http-epoll-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'braveTracer': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
Caused by: org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'braveTracer': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:233) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1273) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1234) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342) ~[spring-beans-5.3.3.jar:5.3.3]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1177) ~[spring-context-5.3.3.jar:5.3.3]
        at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.contextWithBeans(ReactorSleuth.java:142) ~[spring-cloud-sleuth-instrumentation-3.0.1.jar:3.0.1]
        at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$springContextSpanOperator$1(ReactorSleuth.java:170) ~[spring-cloud-sleuth-instrumentation-3.0.1.jar:3.0.1]
        at reactor.core.publisher.MonoLift.subscribeOrReturn(MonoLift.java:42) ~[reactor-core-3.4.2.jar:3.4.2]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4031) ~[reactor-core-3.4.2.jar:3.4.2]
        at reactor.core.publisher.Mono.subscribeWith(Mono.java:4161) ~[reactor-core-3.4.2.jar:3.4.2]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4017) ~[reactor-core-3.4.2.jar:3.4.2]
        at reactor.core.publisher.Mono.subscribe(Mono.java:3953) ~[reactor-core-3.4.2.jar:3.4.2]
        at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.lambda$registerClose$2(DefaultPooledConnectionProvider.java:326) ~[reactor-netty-core-1.0.3.jar:1.0.3]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1174) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:761) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:737) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:608) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.close(CombinedChannelDuplexHandler.java:505) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:77) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.close(CombinedChannelDuplexHandler.java:316) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannel.close(AbstractChannel.java:232) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
        at reactor.netty.http.client.HttpClientOperations.onInboundCancel(HttpClientOperations.java:270) ~[reactor-netty-http-1.0.3.jar:1.0.3]
        at reactor.netty.channel.FluxReceive.unsubscribeReceiver(FluxReceive.java:465) ~[reactor-netty-core-1.0.3.jar:1.0.3]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Sample**

Going to try and see if I can recreate the situation in an MVCE.  I am going to create it later.

- [x] Create MVCE

**Comment by tony-clarke-amdocs** [comment]
If you remove the sleuth dependency does the warning go away?

**Comment by trajano** [comment]
Actually it's a matter of going to start.spring.io then adding two dependencies

1. Spring Cloud Gateway
2. Spring Cloud Sleuth

Then run ./gradlew test

````
> Task :test
2021-02-22 22:14:55.788  WARN [,,] 6716 --- [extShutdownHook] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'reactorServerResourceFactory': org.springframework.beans.factory.BeanCre
ationNotAllowedException: Error creating bean with name 'braveTracer': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementat
ion!)
```

**Comment by trajano** [comment]
Switching to 
```
id 'org.springframework.boot' version '2.3.9.RELEASE'
```
and
```
set('springCloudVersion', "Hoxton.SR10")
```
removes the warning

**Comment by marcingrzejszczak** [comment]
So the problem is gone or not?

**Comment by trajano** [comment]
The problem is not present on the older version, but present on the current versions of Spring Cloud Gateway (2020.0.1) + Spring Boot (2.4.3),  In my case I downgraded and I get the logs showing the trace IDs as well, but with the current versions the trace IDs are missing and the bean creation warning is present.
