### ISSUE TITLE
NPE Issue with spring redis cluster mode

### ISSUE THREAD

**Issue by xingjungoh** [spring-cloud/spring-cloud-sleuth#1992]
When enable Sleuth together with **spring-session-data-redis** and **spring-boot-starter-data-redis (cluster mode)**, I'm not able to start my spring boot app due to **NPE**. Please advice on this issue.

I mange to start my app by disabling the sleuth redis.       **spring.sleuth.redis.enabled=false**

**Spring cloud version: Hoxton.SR10
spring-boot-starter-data-redis version: 2.3.8.RELEASE
spring-session-data-redis version: 2.3.1.RELEASE**

Spring boot redis config:
**spring.redis.cluster.nodes=@spring.redis.host@:@spring.redis.port@**

2021-07-09 14:00:00,038 WARN io.lettuce.core.protocol.DefaultEndpoint Unexpected exception during request: java.lang.NullPointerException
java.lang.NullPointerException: null
        at io.lettuce.core.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:426)
        at io.lettuce.core.protocol.CommandHandler.write(CommandHandler.java:378)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
        at io.lettuce.core.protocol.DefaultEndpoint.channelWriteAndFlush(DefaultEndpoint.java:392)
        at io.lettuce.core.protocol.DefaultEndpoint.writeToChannelAndFlush(DefaultEndpoint.java:332)
        at io.lettuce.core.protocol.DefaultEndpoint.write(DefaultEndpoint.java:162)
        at io.lettuce.core.protocol.DefaultEndpoint$RetryListener.requeueCommands(DefaultEndpoint.java:1002)
        at io.lettuce.core.protocol.DefaultEndpoint$RetryListener.lambda$potentiallyRequeueCommands$0(DefaultEndpoint.java:989)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by marcingrzejszczak** [comment]
Please check the latest 3.1.x snapshots. We've rewritten the lettuce instrumentation there.

**Comment by xingjungoh** [comment]
Retest with the following package but still facing the same NPE issue.

spring-cloud-starter-sleuth-3.1.0-20210707.192008-133.jar

**Comment by marcingrzejszczak** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by xingjungoh** [comment]
I created a new spring boot app and import with the spring-cloud-starter-sleuth-3.1.0-20210707.192008-133.jar (by installing the jar to local mvn repo). 
It seems like the sleuth feature is not enabled. Can advice on this?

https://github.com/xingjungoh/sleuth

**Comment by marcingrzejszczak** [comment]
You are using Boot `2.3.x` instead of Boot `2.6.0-SNAPSHOT`. You're using `Hoxton` cloud train instead of `2021.0.0-SNAPSHOT`. I don't understand why you're installing a concrete Sleuth version instead of just rely on the latest snapshots. Please update your project and try again.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by xingjungoh** [comment]
Hi. Sorry for late reply. I tested with Spring Boot 2.6.0-SNAPSHOT and cloud train of 2021.0.0-SNAPSHOT, it seems like the issue have been resolved given the above version. Thanks.

https://github.com/xingjungoh/sleuth
