### ISSUE TITLE
TraceableExecutorService should allow direct access to ExecutorService

### ISSUE THREAD

**Issue by jensmuellerjm** [spring-cloud/spring-cloud-sleuth#2007]
**Describe the bug**
Hello,
I have a spring boot application where I am using spring-cloud-sleuth for tracing. I have an ExecutorService for running multiple threads in my application. I am using a ThreadPoolExecutor as implementation of the ExecutorService.
When I have tracing enabled, Spring-cloud-sleuth is automatically wrapping the ThreadPoolExecutor behind a TraceableExecutorService. I am not able to access the original implementation of ExecutorService (ThreadPoolExecutor). This breaks the code during application startup, when dependencies are injected.
See the following example:

**Sample**
```
@Configuration
@Validated
class DemoConfig : Logging {

    @Bean("demo-name")
    fun createThreadPool(): ThreadPoolExecutor {
        return ThreadPoolExecutor(1, 4, 30, TimeUnit.SECONDS,
            ArrayBlockingQueue(4)
        )
    }

    @Bean
    fun createActiveTasksMetric(@Qualifier("demo-name") executor: ThreadPoolExecutor) = RegistrableMeters {
        val activeCount = executor.activeCount
        logger.info("Count is: $activeCount")
        null
    }
}

```
In Java 11 the ThreadPoolExecutor is automatically injected into createActiveTasksMetric and the code was running perfectly. Whereas in Java 16, I am getting the following error:
```
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'demo-name' is expected to be of type 'java.util.concurrent.ThreadPoolExecutor' but was actually of type 'org.springframework.cloud.sleuth.instrument.async.TraceableExecutorService'
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.checkBeanNotOfRequiredType(DefaultListableBeanFactory.java:1809)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1346)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 103 more
```

When I inject the ExecutorService instead of the ThreadPoolExecutor, a bean of TraceableExecutorService can be injected by Spring. But I do not have any option to access ThreadPoolExecutor. The ThreadPoolExecutor is protected behind the delegate.
```
  
    @Bean
    fun injectExecutor(@Qualifier("demo-name") executorService: ExecutorService) = RegistrableMeters {
        val traceableExecutorService = executorService as TraceableExecutorService
        // TraceableExecutorService does not allow access to ThreadPoolExecutor
        null
    }
```
The code is part of a Kotlin-project. But we are observing the same behaviour with Java.

***Versions:***
spring-cloud-sleuth:  org.springframework.cloud:spring-cloud-starter-sleuth:jar:3.0.2:compile
Spring-boot-starter: org.springframework.boot:spring-boot-starter-web:jar:2.4.3:compile

Working:
Java: jdk-11.45.27-ca-jdk11.0.10
Not working:
Java: openjdk 16.0.1 2021-04-20

**Comment by marcingrzejszczak** [comment]
Can you create a simple Java and Maven based project that I can play around with?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by ShreyasKaranth** [comment]
@marcingrzejszczak, I m also facing same issue. ThreadPoolExecutor Bean is wrapped to org.springframework.cloud.sleuth.instrument.async.TraceableExecutorService and application is not starting.
```
2022-12-15 15:10:54.882[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mngbootRabbitMqMultipleListnerApplication[0;39m [2m:[0;39m Starting SpringbootRabbitMqMultipleListnerApplication using Java 17 on shreyas-karanth with PID 29058 (/home/shreyas_karanth/workspace_UPI/Slueth/springbootRabbitMqMultipleListner/target/classes started by shreyas_karanth in /home/shreyas_karanth/workspace_UPI/Slueth/springbootRabbitMqMultipleListner)
[2m2022-12-15 15:10:54.884[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mngbootRabbitMqMultipleListnerApplication[0;39m [2m:[0;39m No active profile set, falling back to 1 default profile: "default"
[2m2022-12-15 15:10:55.526[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.cloud.context.scope.GenericScope    [0;39m [2m:[0;39m BeanFactory id=19761352-095d-35bf-a422-1ebf5a06ceb8
[2m2022-12-15 15:10:55.955[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.b.w.embedded.tomcat.TomcatWebServer [0;39m [2m:[0;39m Tomcat initialized with port(s): 8888 (http)
[2m2022-12-15 15:10:55.961[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.apache.catalina.core.StandardService  [0;39m [2m:[0;39m Starting service [Tomcat]
[2m2022-12-15 15:10:55.961[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36morg.apache.catalina.core.StandardEngine [0;39m [2m:[0;39m Starting Servlet engine: [Apache Tomcat/9.0.65]
[2m2022-12-15 15:10:56.066[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.a.c.c.C.[Tomcat].[localhost].[/]      [0;39m [2m:[0;39m Initializing Spring embedded WebApplicationContext
[2m2022-12-15 15:10:56.066[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mw.s.c.ServletWebServerApplicationContext[0;39m [2m:[0;39m Root WebApplicationContext: initialization completed in 1151 ms
[2m2022-12-15 15:10:56.320[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.restapi.Config                      [0;39m [2m:[0;39m ThreadPoolExecutor is created with CorePoolSize=10 and maxPoolSize=12 ,threadPoolExecutor=java.util.concurrent.ThreadPoolExecutor@1283ca23[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
[2m2022-12-15 15:10:56.322[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.restapi.Config                      [0;39m [2m:[0;39m TimeUnit.valueOf(keepAliveTimeUnit_ThreadPoolExecutor)=MILLISECONDS
[2m2022-12-15 15:10:56.346[0;39m [33m WARN [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mConfigServletWebServerApplicationContext[0;39m [2m:[0;39m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'requestListener': Unsatisfied dependency expressed through field 'executor'; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'threadPoolExecutor' is expected to be of type 'java.util.concurrent.ThreadPoolExecutor' but was actually of type 'org.springframework.cloud.sleuth.instrument.async.TraceableExecutorService'
[2m2022-12-15 15:10:56.348[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.apache.catalina.core.StandardService  [0;39m [2m:[0;39m Stopping service [Tomcat]
[2m2022-12-15 15:10:56.362[0;39m [32m INFO [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mConditionEvaluationReportLoggingListener[0;39m [2m:[0;39m 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2m2022-12-15 15:10:56.375[0;39m [31mERROR [,,][0;39m [35m29058[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'requestListener': Unsatisfied dependency expressed through field 'executor'; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'threadPoolExecutor' is expected to be of type 'java.util.concurrent.ThreadPoolExecutor' but was actually of type 'org.springframework.cloud.sleuth.instrument.async.TraceableExecutorService'
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at com.restapi.SpringbootRabbitMqMultipleListnerApplication.main(SpringbootRabbitMqMultipleListnerApplication.java:14) ~[classes/:na]
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'threadPoolExecutor' is expected to be of type 'java.util.concurrent.ThreadPoolExecutor' but was actually of type 'org.springframework.cloud.sleuth.instrument.async.TraceableExecutorService'
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1401) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656) ~[spring-beans-5.3.23.jar:5.3.23]
	... 20 common frames omitted
```

**Comment by marcingrzejszczak** [comment]
Can you create a simple Java and Maven based project that I can play around with?

**Comment by Cimballi** [comment]
Not being able to access the delegate is also a problem for debugging purposes, the TraceableExecutorService toString method is not printing anything useful.

**Comment by babay182** [comment]
I have progect for example. Problem in version Spring Boot, if version Spring Boot 3+ problem is disappears, but i can't up version Spring Boot. progect with problem https://github.com/babay182/testSleuth . can you fix it?

**Comment by jonatan-ivanov** [comment]
No, Spring Cloud Sleuth reached the end of its OSS support period: https://spring.io/projects/spring-cloud-sleuth#support you should upgrade.
