### ISSUE TITLE
Spring cloud sleuth dependency causes "WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils " after upgrade from Java 8 to 11

### ISSUE THREAD

**Issue by AlFr7** [spring-cloud/spring-cloud-sleuth#2022]
Warning at application start up for Spring Boot 2.5.3, JDK 11, spring-cloud.release.train.version 2020.0.3 👍 

`WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils (file:/C:/Users/myuser/.m2/repository/org/springframework/spring-core/5.3.9/spring-core-5.3.9.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:552)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:585)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:572)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:419)
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:57)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:206)
	at org.springframework.aop.framework.ProxyFactoryBean.getProxy(ProxyFactoryBean.java:370)
	at org.springframework.aop.framework.ProxyFactoryBean.getSingletonInstance(ProxyFactoryBean.java:328)
	at org.springframework.aop.framework.ProxyFactoryBean.getObject(ProxyFactoryBean.java:252)
	at org.springframework.cloud.sleuth.instrument.async.ExecutorInstrumentor.getObject(ExecutorInstrumentor.java:270)
	at org.springframework.cloud.sleuth.instrument.async.ExecutorInstrumentor.getProxiedObject(ExecutorInstrumentor.java:223)
	at org.springframework.cloud.sleuth.instrument.async.ExecutorInstrumentor.createExecutorServiceProxy(ExecutorInstrumentor.java:195)
	at org.springframework.cloud.sleuth.instrument.async.ExecutorInstrumentor.wrapExecutorService(ExecutorInstrumentor.java:153)
	at org.springframework.cloud.sleuth.instrument.async.ExecutorInstrumentor.instrument(ExecutorInstrumentor.java:101)
	at org.springframework.cloud.sleuth.autoconfig.instrument.async.ExecutorBeanPostProcessor.postProcessAfterInitialization(ExecutorBeanPostProcessor.java:62)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:437)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208`

**Maven sample**

` 
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.3</version>
	</parent>

	<properties>
		<java.version>11</java.version>
		<spring-boot.version>2.5.3</spring-boot.version>
		<spring-cloud.release.train.version>2020.0.3</spring-cloud.release.train.version>

		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.build.timestamp.format>yyyy-MM-dd</maven.build.timestamp.format>

		<shedlock.version>4.25.0</shedlock.version>
		<org.mapstruct.version>1.4.2.Final</org.mapstruct.version>
		<quickfixj.spring.boot.starter.version>2.9.0</quickfixj.spring.boot.starter.version>
		<sti.quickfixj.messages.version>1.4.41.2</sti.quickfixj.messages.version>
		<quickfixj.core.dpl.version>2.2.0.DPL</quickfixj.core.dpl.version>
		<springdoc.openapi.version>1.5.10</springdoc.openapi.version>
		<apache.tika.version>2.0.0</apache.tika.version>
		<apache.commons.text.version>1.9</apache.commons.text.version>
		<apache.pdfbox.version>2.0.24</apache.pdfbox.version>
		<jsonwebtoken.jjwt.version>0.11.2</jsonwebtoken.jjwt.version>
		<oracle.ojdbc.version>18.3.0.0</oracle.ojdbc.version>
		<logstash.logback.version>6.6</logstash.logback.version>
		<micrometer.registry.prometheus.version>1.7.3</micrometer.registry.prometheus.version>
		
		<jacoco.version>0.8.7</jacoco.version>
		<sonar.java.coveragePlugin>jacoco</sonar.java.coveragePlugin>
		<sonar.dynamicAnalysis>reuseReports</sonar.dynamicAnalysis>
		<sonar.jacoco.reportPath>${project.basedir}/../target/jacoco.exec</sonar.jacoco.reportPath>
		<sonar.language>java</sonar.language>
	</properties>

...
...
...

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
        <exclusions>
          <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.release.train.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies> 
...
...
...
   <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-bootstrap</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-sleuth</artifactId>
    </dependency>

  <dependencies> 
`

Warning does not appear when dependency to `spring-cloud-starter-sleuth` is removed

**Comment by jonatan-ivanov** [comment]
@AlFr7 Could you please provide a test case or a minimal **Maven** sample written in **Java** that reproduces
the problem?
This makes it much easier for us to diagnose the problem and to verify that we have fixed it.

**Comment by marcingrzejszczak** [comment]
Can you generate a fresh project from start.spring.io and replicate this issue?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
