### ISSUE TITLE
No traceId and spanId in gateway

### ISSUE THREAD

**Issue by igorroman777** [spring-cloud/spring-cloud-sleuth#2034]
**Describe the bug**
In the older version Hoxton.SR1 Spring boot org.springframework.cloud worked: I had traceId in gateway.
After updating to version 2020.0.4 I get nothing:
`[GatewayApplication,,]`

**Comment by igorroman777** [comment]
I have:
- gateway with Spring Boot WebFlux
- Api Server with old spring boot

Tracing with sleuth in api server works.
I gateway does not.
I have made the following changes:
`	@Bean
	NettyServerCustomizer nettyServerCustomizer(ReactorNettyHttpTracing reactorNettyHttpTracing) {
		return reactorNettyHttpTracing::decorateHttpServer;
	}

	@Bean
	ReactorNettyHttpTracing reactorNettyHttpTracing(HttpTracing httpTracing) {
		return ReactorNettyHttpTracing.create(httpTracing);
	}`


Now I see something:

`2021-10-05 12:18:54.345 DEBUG [CustomerGuiApplication,e7925c7dea6ad691,e7925c7dea6ad691] 24895 --- [ctor-http-nio-4] o.s.c.s.instrument.web.TraceWebFilter    : Adding a class tag with value [ResourceWebHandler] to a span LazySpan(e7925c7dea6ad691/e7925c7dea6ad691)
2021-10-05 12:18:54.345 DEBUG [CustomerGuiApplication,e7925c7dea6ad691,e7925c7dea6ad691] 24895 --- [ctor-http-nio-4] o.s.c.s.instrument.web.TraceWebFilter    : Handled send of LazySpan(e7925c7dea6ad691/e7925c7dea6ad691)
2021-10-05 12:18:54.473 ERROR [CustomerGuiApplication,,] 24895 --- [ctor-http-nio-4] reactor.netty.transport.ServerTransport  : [id:85bd3a93, L:/0:0:0:0:0:0:0:1:8080 ! R:/0:0:0:0:0:0:0:1:62245] onUncaughtException(SimpleConnection{channel=[id: 0x85bd3a93, L:/0:0:0:0:0:0:0:1:8080 ! R:/0:0:0:0:0:0:0:1:62245]})

java.lang.NullPointerException: null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770) ~[na:na]
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416) ~[na:na]
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253) ~[na:na]
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134) ~[na:na]
	at org.springframework.cloud.sleuth.brave.instrument.web.SkipPatternSampler.trySample(SkipPatternSampler.java:37) ~[spring-cloud-sleuth-brave-3.0.4.jar:3.0.4]
	at org.springframework.cloud.sleuth.brave.instrument.web.SkipPatternSampler.trySample(SkipPatternSampler.java:30) ~[spring-cloud-sleuth-brave-3.0.4.jar:3.0.4]
	at brave.http.HttpServerHandler.nextSpan(HttpServerHandler.java:150) ~[brave-instrumentation-http-5.13.2.jar:na]
	at brave.http.HttpServerHandler.handleReceive(HttpServerHandler.java:111) ~[brave-instrumentation-http-5.13.2.jar:na]
	at reactor.netty.http.brave.TracingHttpServerDecorator$TracingConnectionObserver.onStateChange(TracingHttpServerDecorator.java:236) ~[reactor-netty-http-brave-1.0.9.jar:1.0.9]
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:654) ~[reactor-netty-core-1.0.9.jar:1.0.9]
	at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:478) ~[reactor-netty-core-1.0.9.jar:1.0.9]
	at reactor.netty.http.server.HttpServerOperations.sendDecodingFailures(HttpServerOperations.java:669) ~[reactor-netty-http-1.0.9.jar:1.0.9]
	at reactor.netty.http.server.HttpTrafficHandler.sendDecodingFailures(HttpTrafficHandler.java:257) ~[reactor-netty-http-1.0.9.jar:1.0.9]
	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:182) ~[reactor-netty-http-1.0.9.jar:1.0.9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.66.Final.jar:4.1.66.Final]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]`

**Comment by marcingrzejszczak** [comment]
Please format the code and preferably upload a sample

**Comment by igorroman777** [comment]
sorry, the formatting does not work

**Comment by igorroman777** [comment]
My change is:

`	@Bean
	NettyServerCustomizer nettyServerCustomizer(ReactorNettyHttpTracing reactorNettyHttpTracing) {
		return reactorNettyHttpTracing::decorateHttpServer;
	}

	@Bean
	ReactorNettyHttpTracing reactorNettyHttpTracing(HttpTracing httpTracing) {
		return ReactorNettyHttpTracing.create(httpTracing);
	}`

But I get **NullPointerException**

**Comment by marcingrzejszczak** [comment]
That's super strange

```java
/**
 * Doesn't sample a span if skip pattern is matched.
 *
 * @author Marcin Grzejszczak
 * @since 2.0.0
 */
abstract class SkipPatternSampler implements SamplerFunction<HttpRequest> {

	private Pattern pattern;

	@Override
	public final Boolean trySample(HttpRequest request) {
		String url = request.path();
		boolean shouldSkip = pattern().matcher(url).matches();
		if (shouldSkip) {
			return false;
		}
		return null;
	}

	abstract Pattern getPattern();

	private Pattern pattern() {
		if (this.pattern == null) {
			this.pattern = getPattern();
		}
		return this.pattern;
	}

}
```

So line 

```
 at org.springframework.cloud.sleuth.brave.instrument.web.SkipPatternSampler.trySample(SkipPatternSampler.java:37) ~[spring-cloud-sleuth-brave-3.0.4.jar:3.0.4]
```

is actually 

```
		boolean shouldSkip = pattern().matcher(url).matches();
```

which means that the URL (`request.path())` is `null`. Can you try to debug this what he `HttpRequest` is within the `SkipPatternSampler` and why the `path()` is returned as `null` ?

**Comment by igorroman777** [comment]
i have built everything new. And it works.
It works in the TokenRefreshRelay, but not in the LoggingServerHttpResponseDecorator:
`
2021-10-05 14:08:39.146  INFO [CustomerGuiApplication,48fed21b25629fb9,48fed21b25629fb9] 26298 --- [tor-http-nio-10] .a.c.a.LoggingServerHttpRequestDecorator : Request GET: /api/product-service/
2021-10-05 14:08:39.189  INFO [CustomerGuiApplication,,] 26298 --- [tor-http-nio-10] a.c.a.LoggingServerHttpResponseDecorator : Response Status Code: 200 OK
`

`
@Slf4j
public class LoggingServerHttpResponseDecorator extends ServerHttpResponseDecorator {

	public LoggingServerHttpResponseDecorator(ServerHttpResponse delegate) {
		super(delegate);
	}

	@Override
	public Mono<Void> writeWith(Publisher<? extends DataBuffer> body) {
		final ByteArrayOutputStream baos = new ByteArrayOutputStream();

		if (body instanceof Flux) {
			Flux<? extends DataBuffer> fluxBody = (Flux<? extends DataBuffer>) body;
			return super.writeWith(fluxBody.map(dataBuffer -> {
				try {
					Channels.newChannel(baos).write(dataBuffer.asByteBuffer().asReadOnlyBuffer());
				} catch (IOException e) {
					log.error("Unable to log input request due to an error", e);
				}
				return dataBuffer;
			}).doOnComplete(() -> flushLog(baos)));
		}
		return super.writeWith(body);
	}

	private void flushLog(ByteArrayOutputStream baos) {
		ServerHttpResponse response = super.getDelegate();
		HttpStatus httpStatus = response.getStatusCode();

		log.info("Response Status Code: {}", httpStatus);
	}

	@Override
	public Mono<Void> writeAndFlushWith(Publisher<? extends Publisher<? extends DataBuffer>> body) {
		return super.writeAndFlushWith(body);
	}

}
`

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Most likely our filter has already closed the span after the response was returned. You can also turn on reactor `ON_EACH` decorator because in Sleuth 3.x the default for the gateway is `MANUAL`.

**Comment by igorroman777** [comment]
formatting `code` works here on mac something buggy ```code```.
How do I do that:
```
ON_EACH
```

**Comment by marcingrzejszczak** [comment]
Please read the docs https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/integrations.html#sleuth-reactor-integration

**Comment by igorroman777** [comment]
ok, sure, thanks 😊

**Comment by igorroman777** [comment]
Yes, with `  sleuth:
    reactor.instrumentation-type: DECORATE_ON_EACH`
works better. But not always. Macncmal trace id is not shown.

**Comment by marcingrzejszczak** [comment]
Please create a **simple sample written in Java and Maven** that replicates the problem. Otherwise it's extremely hard to help you. Maybe you're using a component after the span has already been closed, it's hard to tell without code.

**Comment by igorroman777** [comment]
ok, Thank you

**Comment by blacelle** [comment]
Hello,

We also observe this issue. I read in brave HttpRequest.path():

String brave.http.HttpRequest.path()

```
@Nullable
The absolute http path, without any query parameters. Ex. "/objects/abcd-ff"

Conventionally associated with the key "http.path"

null could mean not applicable to the HTTP method (ex CONNECT).
```

Hence, I feel trySample should handle null path anyway.

	@Override
	public final Boolean trySample(HttpRequest request) {
		String url = request.path();
		boolean shouldSkip = pattern().matcher(url).matches();
		if (shouldSkip) {
			return false;
		}
		return null;
	}

In our case, we have security auditors making various dumb request leading to things like:

> ERROR: Exception Processing ErrorPage[errorCode=0, location=/error] (RequestRejectedException: The request was rejected because the HTTP method "DEBUG" was not included within the list of allowed HTTP methods [HEAD, DELETE, POST, GET, OPTIONS, PATCH, PUT])

Hence, I suppose we encounter a DEBUG http method, hending leading to this null path. @marcingrzejszczak Should I open a different ticket?

**Comment by marcingrzejszczak** [comment]
No need to - it already got fixed for 3.1.1  - https://github.com/spring-cloud/spring-cloud-sleuth/pull/2089/files

**Comment by blacelle** [comment]
For the record, this also happened on request looking like 'GET http://localhost:8085/?name{=3'. Supposedly related with StrictHttpFirewall

**Comment by blacelle** [comment]
@marcingrzejszczak DO you know when is planned 3.1.1? Thanks

**Comment by marcingrzejszczak** [comment]
https://github.com/spring-cloud/spring-cloud-release/milestone/116 according to the current tentative date - tomorrow (17.02)
