### ISSUE TITLE
In unit tests, Consumer function does not work with Sleuth - ClassCastException

### ISSUE THREAD

**Issue by julb** [spring-cloud/spring-cloud-sleuth#2068]
Dear team, 

I have written a simple Consumer<GoogleChatMessageDTO>.
The function works as expected when I execute it through the main class.

However, when I write a unit test for that function, I get a ClassCastException because of Sleuth:

```
java.lang.ClassCastException: class me.julb.library.dto.googlechat.GoogleChatMessageDTO cannot be cast to class org.springframework.messaging.Message (me.julb.library.dto.googlechat.GoogleChatMessageDTO and org.springframework.messaging.Message are in unnamed module of loader 'app')
 at org.springframework.cloud.sleuth.instrument.messaging.TraceFunctionAroundWrapper.doApply(TraceFunctionAroundWrapper.java:99)
 at org.springframework.cloud.function.context.catalog.FunctionAroundWrapper.apply(FunctionAroundWrapper.java:47)
 at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$1.doApply(SimpleFunctionRegistry.java:256)
 at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:550)
 at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.accept(SimpleFunctionRegistry.java:566)
 at me.julb.functions.SendGoogleChatFunctionTest.whenInvokingFunction_thenSendGoogleChat(SendGoogleChatFunctionTest.java:69)
```

From what I understand, it seems that the Sleuth `TraceFunctionAroundWrapper` is invoked before the input is converted to a Message in `FunctionInvocationWrapper#convertInputIfNecessary`.

I'm using : 

- Spring Cloud Function 3.2.1
- Spring Cloud Sleuth 3.1.0.

Workarounds found:

1/ Transform the `Consumer<GoogleChatMessageDTO>` to a `Consumer<Message<GoogleChatMessageDTO>>`
2/ Set property `spring.sleuth.function.enabled: false` for unit tests

**Comment by marcingrzejszczak** [comment]
Can you show your unit test?

**Comment by julb** [comment]
Wow, that was fast!
Thanks a lot @marcingrzejszczak !

**Comment by davidmelia** [comment]
@marcingrzejszczak posted in the other discussion but this is till broken for me

I have updated my prototype https://github.com/davidmelia/spring-boot-webflux-avro-sink-only  to 2021.0.1-SNAPSHOT and can confirm it's still broken :-(

 ```
java.lang.ClassCastException: class reactor.core.publisher.MonoPeekTerminal cannot be cast to class reactor.core.publisher.Flux (reactor.core.publisher.MonoPeekTerminal and reactor.core.publisher.Flux are in unnamed module of loader 'app')
	at org.springframework.cloud.sleuth.instrument.messaging.TraceFunctionAroundWrapper.reactorFluxStream(TraceFunctionAroundWrapper.java:204) ~[spring-cloud-sleuth-instrumentation-3.1.1-SNAPSHOT.jar:3.1.1-SNAPSHOT]
	at org.springframework.cloud.sleuth.instrument.messaging.TraceFunctionAroundWrapper.reactorStream(TraceFunctionAroundWrapper.java:137) ~[spring-cloud-sleuth-instrumentation-3.1.1-SNAPSHOT.jar:3.1.1-SNAPSHOT]
	at org.springframework.cloud.sleuth.instrument.messaging.TraceFunctionAroundWrapper.doApply(TraceFunctionAroundWrapper.java:102) ~[spring-cloud-sleuth-instrumentation-3.1.1-SNAPSHOT.jar:3.1.1-SNAPSHOT]
	at org.springframework.cloud.function.context.catalog.FunctionAroundWrapper.apply(FunctionAroundWrapper.java:47) ~[spring-cloud-function-context-3.2.1.jar:3.2.1]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$1.doApply(SimpleFunctionRegistry.java:256) ~[spring-cloud-function-context-3.2.1.jar:3.2.1]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:550) ~[spring-cloud-function-context-3.2.1.jar:3.2.1]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder.bindFunctionToDestinations(FunctionConfiguration.java:512) ~[spring-cloud-stream-3.2.1.jar:3.2.1]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder.afterPropertiesSet(FunctionConfiguration.java:418) ~[spring-cloud-stream-3.2.1.jar:3.2.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.13.jar:5.3.13]
```
