### ISSUE TITLE
NPE when JDBC instrumentation is on together with TestContainers and p6spy for 3.1.0

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#2076]
```
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.getOrDefault(ConcurrentHashMap.java:1594) ~[na:na]
	at org.springframework.cloud.sleuth.instrument.jdbc.DataSourceNameResolver.resolveDataSourceName(DataSourceNameResolver.java:38) ~[spring-cloud-sleuth-instrumentation-3.1.0.jar:3.1.0]
	at org.springframework.cloud.sleuth.instrument.jdbc.TraceJdbcEventListener.onBeforeGetConnection(TraceJdbcEventListener.java:64) ~[spring-cloud-sleuth-instrumentation-3.1.0.jar:3.1.0]
	at com.p6spy.engine.event.CompoundJdbcEventListener.onBeforeGetConnection(CompoundJdbcEventListener.java:74) ~[p6spy-3.9.1.jar:na]
	at com.p6spy.engine.spy.P6SpyDriver.connect(P6SpyDriver.java:100) ~[p6spy-3.9.1.jar:na]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:na]
	... 102 common frames omitted
```

**Comment by SamD** [comment]
I just encountered this today with v3.1.1 doesn't appear it is fixed
