### ISSUE TITLE
Did not find handler method for [/api/v2/spans] 

### ISSUE THREAD

**Issue by weishaofei** [spring-cloud/spring-cloud-sleuth#2084]
**Describe the bug**

spring cloud version : Finchley.SR1
spring boot version: 2.0.4.RELEASE
zipkin-server version:2.10.4
zipkin-autoconfigure-ui:2.10.4

web server: resin  with version  4.0.55

it can start and I can open the web pages, but it can not accept the data from other service with http call, log as below:

2021-12-21 13:10:53.451 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.WebMvcEndpointHandlerMapping:312] - Looking up handler method for path /api/v2/spans [TraceInfo:-] 
2021-12-21 13:10:53.452 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.WebMvcEndpointHandlerMapping:322] - Did not find handler method for [/api/v2/spans] [TraceInfo:-] 
2021-12-21 13:10:53.453 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.ControllerEndpointHandlerMapping:312] - Looking up handler method for path /api/v2/spans [TraceInfo:-] 
2021-12-21 13:10:53.453 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.ControllerEndpointHandlerMapping:322] - Did not find handler method for [/api/v2/spans] [TraceInfo:-] 
2021-12-21 13:10:53.453 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.m.m.a.RequestMappingHandlerMapping:312] - Looking up handler method for path /api/v2/spans [TraceInfo:-] 
2021-12-21 13:10:53.454 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.m.w.s.WebMvcMetricsFilter:119] - Unable to time request [TraceInfo:-] 
org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported
	at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:197)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:376)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:316)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:62)
	at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:350)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.getHandler(WebMvcMetricsFilter.java:129)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:116)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at com.caucho.server.dispatch.FilterFilterChain.doFilter(FilterFilterChain.java:89)
	at com.caucho.server.webapp.WebAppFilterChain.doFilter(WebAppFilterChain.java:156)
	at com.caucho.server.webapp.AccessLogFilterChain.doFilter(AccessLogFilterChain.java:95)
	at com.caucho.server.dispatch.ServletInvocation.service(ServletInvocation.java:290)
	at com.caucho.server.http.HttpRequest.handleRequest(HttpRequest.java:838)
	at com.caucho.network.listen.TcpSocketLink.dispatchRequest(TcpSocketLink.java:1353)
	at com.caucho.network.listen.TcpSocketLink.handleRequest(TcpSocketLink.java:1309)
	at com.caucho.network.listen.TcpSocketLink.handleRequestsImpl(TcpSocketLink.java:1293)
	at com.caucho.network.listen.TcpSocketLink.handleRequests(TcpSocketLink.java:1201)
	at com.caucho.network.listen.TcpSocketLink.handleAcceptTaskImpl(TcpSocketLink.java:997)
	at com.caucho.network.listen.ConnectionTask.runThread(ConnectionTask.java:117)
	at com.caucho.network.listen.ConnectionTask.run(ConnectionTask.java:93)
	at com.caucho.network.listen.SocketLinkThreadLauncher.handleTasks(SocketLinkThreadLauncher.java:169)
	at com.caucho.network.listen.TcpSocketAcceptThread.run(TcpSocketAcceptThread.java:61)
	at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
	at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
2021-12-21 13:10:53.454 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.w.s.f.OrderedRequestContextFilter:114] - Bound request context to thread: HttpServletRequestImpl[HttpRequest[zipkin-service, 1]] [TraceInfo:-] 
2021-12-21 13:10:53.455 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.DispatcherServlet:891] - DispatcherServlet with name 'dispatcherServlet' processing POST request for [/api/v2/spans] [TraceInfo:-] 
2021-12-21 13:10:53.456 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.WebMvcEndpointHandlerMapping:312] - Looking up handler method for path /api/v2/spans [TraceInfo:-] 
2021-12-21 13:10:53.456 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.WebMvcEndpointHandlerMapping:322] - Did not find handler method for [/api/v2/spans] [TraceInfo:-] 
2021-12-21 13:10:53.457 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.ControllerEndpointHandlerMapping:312] - Looking up handler method for path /api/v2/spans [TraceInfo:-] 
2021-12-21 13:10:53.457 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.ControllerEndpointHandlerMapping:322] - Did not find handler method for [/api/v2/spans] [TraceInfo:-] 
2021-12-21 13:10:53.457 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.m.m.a.RequestMappingHandlerMapping:312] - Looking up handler method for path /api/v2/spans [TraceInfo:-] 
2021-12-21 13:10:53.458 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver:136] - Resolving exception from handler [null]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported [TraceInfo:-] 
2021-12-21 13:10:53.458 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.m.a.ResponseStatusExceptionResolver:136] - Resolving exception from handler [null]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported [TraceInfo:-] 
2021-12-21 13:10:53.459 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.m.s.DefaultHandlerExceptionResolver:136] - Resolving exception from handler [null]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported [TraceInfo:-] 
2021-12-21 13:10:53.459 - [Thread:resin-port-10580-60] - [WARN ] - [o.s.w.s.PageNotFound:255] - Request method 'POST' not supported [TraceInfo:-] 
2021-12-21 13:10:53.459 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.DispatcherServlet:1076] - Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling [TraceInfo:-] 
2021-12-21 13:10:53.460 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.DispatcherServlet:1000] - Successfully completed request [TraceInfo:-] 
2021-12-21 13:10:53.460 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.w.s.f.OrderedRequestContextFilter:104] - Cleared thread-bound request context: HttpServletRequestImpl[HttpRequest[zipkin-service, 1]] [TraceInfo:-] 
2021-12-21 13:10:53.460 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.DispatcherServlet:891] - DispatcherServlet with name 'dispatcherServlet' processing POST request for [/error] [TraceInfo:-] 
2021-12-21 13:10:53.461 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.WebMvcEndpointHandlerMapping:312] - Looking up handler method for path /error [TraceInfo:-] 
2021-12-21 13:10:53.461 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.WebMvcEndpointHandlerMapping:322] - Did not find handler method for [/error] [TraceInfo:-] 
2021-12-21 13:10:53.462 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.ControllerEndpointHandlerMapping:312] - Looking up handler method for path /error [TraceInfo:-] 
2021-12-21 13:10:53.462 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.a.e.w.s.ControllerEndpointHandlerMapping:322] - Did not find handler method for [/error] [TraceInfo:-] 
2021-12-21 13:10:53.462 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.m.m.a.RequestMappingHandlerMapping:312] - Looking up handler method for path /error [TraceInfo:-] 
2021-12-21 13:10:53.463 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.m.m.a.RequestMappingHandlerMapping:319] - Returning handler method [public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)] [TraceInfo:-] 
2021-12-21 13:10:53.463 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.b.f.s.DefaultListableBeanFactory:254] - Returning cached instance of singleton bean 'basicErrorController' [TraceInfo:-] 
2021-12-21 13:10:53.464 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.m.m.a.HttpEntityMethodProcessor:278] - Written [{timestamp=Tue Dec 21 13:10:53 CST 2021, status=405, error=Method Not Allowed, message=Request method 'POST' not supported, path=/api/v2/spans}] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@3f400cf3] [TraceInfo:-] 
2021-12-21 13:10:53.464 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.DispatcherServlet:1076] - Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling [TraceInfo:-] 
2021-12-21 13:10:53.465 - [Thread:resin-port-10580-60] - [DEBUG] - [o.s.w.s.DispatcherServlet:1000] - Successfully completed request [TraceInfo:-]

**Comment by jonatan-ivanov** [comment]
The versions you are using are very old and not supported anymore.
I'm not sure what you are trying to do, are you trying to hit `/api/v2/spans` on your service?

Sleuth does not set that up for you, you need a running and configured Zipkin endpoint that Sleuth can send spans. You can see the spans in Zipkin.

I'm closing this issue please let us know if I misunderstood your issue and you have this problem with supported versions (3.0.x, 3.1.x).
