### ISSUE TITLE
url maybe null

### ISSUE THREAD

**Issue by superccfgithub** [spring-cloud/spring-cloud-sleuth#2087]
https://github.com/spring-cloud/spring-cloud-sleuth/blob/195d853714894a9fb3f98e7662364f754a42a348/spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/instrument/web/SkipPatternSampler.java#L37

2021-12-22 15:50:10.074 ERROR [me-core2,,] 5154 --- [nio-8080-exec-3] o.apache.coyote.http11.Http11Processor   : Error processing request

java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.springframework.cloud.sleuth.brave.instrument.web.SkipPatternSampler.trySample(SkipPatternSampler.java:37)
	at org.springframework.cloud.sleuth.brave.instrument.web.SkipPatternSampler.trySample(SkipPatternSampler.java:30)
	at brave.http.HttpServerHandler.nextSpan(HttpServerHandler.java:150)
	at brave.http.HttpServerHandler.handleReceive(HttpServerHandler.java:111)
	at org.springframework.cloud.sleuth.brave.bridge.BraveHttpServerHandler.handleReceive(BraveHttpServerHandler.java:41)
	at org.springframework.cloud.sleuth.instrument.web.tomcat.TraceValve.invoke(TraceValve.java:61)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by madisparn** [comment]
It happened for me when the request made is actually just a tcp connection that is closed right after without any content sent to server. Access log contained:
`10.220.20.100 - - [25/Dec/2021:02:31:29 +0000] "OPTIONS / HTTP/1.0" 404 431
10.220.20.100 - - [25/Dec/2021:02:31:29 +0000] "-" 400 -
10.220.20.100 - - [25/Dec/2021:02:31:29 +0000] "-" 500 -`

**Comment by superccfgithub** [comment]
In my case,this happens when a HTTPS request was sent to a HTTP service.

**Comment by marcingrzejszczak** [comment]
That seems like an easy fix. Anyone is interested in a PR?

**Comment by sanha** [comment]
I opened a PR for this :)

**Comment by karkum** [comment]
@marcingrzejszczak do you know when the next release of sleuth will be? We are running into this NPE and would like to roll-forward, thanks!

**Comment by marcingrzejszczak** [comment]
https://github.com/spring-cloud/spring-cloud-release/milestone/116 - currently 17.02
