### ISSUE TITLE
WARN message on SkipPatternConfiguration about circular reference

### ISSUE THREAD

**Issue by taxone** [spring-cloud/spring-cloud-sleuth#2243]
Spring Cloud version: 2021.0.2

Spring cloud sleuth and reactor-netty-http-brave are used by the project:

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>

		<dependency>
		    <groupId>io.projectreactor.netty</groupId>
		    <artifactId>reactor-netty-http-brave</artifactId>
		</dependency>
```

The netty HttpClient is instrumented as follows:

```
	@Bean
    ReactorNettyHttpTracing reactorNettyHttpTracing(HttpTracing httpTracing) {
        return ReactorNettyHttpTracing.create(httpTracing);
    }

	@Bean
	public HttpClientCustomizer customizer(ApplicationProperties properties,ReactorNettyHttpTracing tracing) {
		return (c) -> {
			return tracing.decorateHttpClient(c);
		};
	}
```

The application starts, but with the warning below:

```
 WARN [gpp-gateway,,] 3240 --- [  restartedMain] o.s.c.s.a.i.w.SkipPatternConfiguration   : Most likely, there is an actuator endpoint that indirectly references an instrumented HTTP client. An exception was thrown during bean initialization. Will ignore that exception

....
Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'reactorNettyHttpTracing': Requested bean is currently in creation: Is there an unresolvable circular reference?
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.beforeSingletonCreation(DefaultSingletonBeanRegistry.java:355) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:227) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) [spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) [spring-beans-5.3.15.jar:5.3.15]

```

This problem is a new issue, probably caused by the introduction in version 3.1.1 of:

**org.springframework.cloud.gateway.config.HttpClientFactory**

In fact, previously the HttpClient was created by autoconfiguration with the @Bean annotation. 

This is the comment present in **org.springframework.cloud.sleuth.autoconfig.instrument.web.SkipPatternConfiguration**:

```
		// Actuator endpoints are queried to make the default skip pattern. There's an
		// edge case where actuator endpoints indirectly reference the still constructing
		// HttpTracing bean. Ex: an instrumented client could cause a cyclic dep.
		//
		// Below optimizes for the opposite: that custom actuator endpoints are not in
		// use. This allows configuration to be eagerly parsed, allowing any errors to
		// surface earlier. In the case there is a cyclic dep, this parsing becomes lazy,
		// deferring any errors creating the skip pattern.
		//
		// See spring-cloud/spring-cloud-gateway#1679
```

Actually, the problem seems to be related to the HttpTracing bean.

**Comment by marcingrzejszczak** [comment]
We can't do much about it. My suggestion is to do as follows (make the `HttpTracing` resolution lazy)

```java

    private ReactorNettyHttpTracing reactorNettyHttpTracing(HttpTracing httpTracing) {
        return ReactorNettyHttpTracing.create(httpTracing);
    }

	@Bean
	public HttpClientCustomizer customizer(ApplicationProperties properties,ObjectProvider<HttpTracing> tracing) {
		return (c) -> {
			return reactorNettyHttpTracing(tracing.getObject()).decorateHttpClient(c);
		};
	}
```

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
