### ISSUE TITLE
Adding  sleuth  dependency breaking the websocket subscribe flow

### ISSUE THREAD

**Issue by PreetamMyneni** [spring-cloud/spring-cloud-sleuth#279]
MessageHeaderAccessor is checking whether the headers are instanceof **MutableMessageHeaders**
this condition is failing probably sleuth interceptor changing the instanceOf.
Please let me know the alternative

Spring Boot: 1.3.3
Spring Cloud: Brixton.RC1

Also tried with 
<version>1.3.5.RELEASE</version>
<version>Brixton.RELEASE</version>

```
Exception in thread "clientInboundChannel-2" org.springframework.messaging.MessageDeliveryException: Failed to handle GenericMessage [payload=byte[0], headers={simpMessageType=CONNECT, stompCommand=CONNECT, nativeHeaders={accept-version=[1.1,1.0], heart-beat=[10000,10000], X-B3-SpanId=[cb05e82b4a3fe89c], X-B3-Sampled=[0], X-B3-TraceId=[cb05e82b4a3fe89c]}, simpSessionAttributes={}, X-B3-SpanId=cb05e82b4a3fe89c, simpHeartbeat=[J@101cc820, X-B3-Sampled=0, X-B3-TraceId=cb05e82b4a3fe89c, id=4055ce24-b0c8-3340-e099-69c24d9d7d02, X-Current-Span=[Trace: cb05e82b4a3fe89c, Span: cb05e82b4a3fe89c, exportable=false], simpSessionId=m2kccjuq, timestamp=1463599267150}] to org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask@1edb2453 in SimpleBrokerMessageHandler [DefaultSubscriptionRegistry[cache[0 destination(s)], registry[0 sessions]]]; nested exception is java.lang.IllegalStateException: No header accessor (not using the SimpMessagingTemplate?): GenericMessage [payload=byte[0], headers={simpMessageType=CONNECT, stompCommand=CONNECT, nativeHeaders={accept-version=[1.1,1.0], heart-beat=[10000,10000], X-B3-SpanId=[cb05e82b4a3fe89c], X-B3-Sampled=[0], X-B3-TraceId=[cb05e82b4a3fe89c]}, simpSessionAttributes={}, X-B3-SpanId=cb05e82b4a3fe89c, simpHeartbeat=[J@101cc820, X-B3-Sampled=0, X-B3-TraceId=cb05e82b4a3fe89c, id=4055ce24-b0c8-3340-e099-69c24d9d7d02, X-Current-Span=[Trace: cb05e82b4a3fe89c, Span: cb05e82b4a3fe89c, exportable=false], simpSessionId=m2kccjuq, timestamp=1463599267150}]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No header accessor (not using the SimpMessagingTemplate?): GenericMessage [payload=byte[0], headers={simpMessageType=CONNECT, stompCommand=CONNECT, nativeHeaders={accept-version=[1.1,1.0], heart-beat=[10000,10000], X-B3-SpanId=[cb05e82b4a3fe89c], X-B3-Sampled=[0], X-B3-TraceId=[cb05e82b4a3fe89c]}, simpSessionAttributes={}, X-B3-SpanId=cb05e82b4a3fe89c, simpHeartbeat=[J@101cc820, X-B3-Sampled=0, X-B3-TraceId=cb05e82b4a3fe89c, id=4055ce24-b0c8-3340-e099-69c24d9d7d02, X-Current-Span=[Trace: cb05e82b4a3fe89c, Span: cb05e82b4a3fe89c, exportable=false], simpSessionId=m2kccjuq, timestamp=1463599267150}]
	at org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler.handleMessageInternal(SimpleBrokerMessageHandler.java:228)
	at org.springframework.messaging.simp.broker.AbstractBrokerMessageHandler.handleMessage(AbstractBrokerMessageHandler.java:238)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:135)
	... 3 more
```

**Comment by PreetamMyneni** [comment]
Sample: https://github.com/PreetamMyneni/Websocket-sleuth

**Comment by marcingrzejszczak** [comment]
I guess it's related to: https://github.com/spring-cloud/spring-cloud-sleuth/issues/276
