### ISSUE TITLE
Adding sleuth to project breaks @ConfigurationProperties class

### ISSUE THREAD

**Issue by michalkarolik** [spring-cloud/spring-cloud-sleuth#288]
I have some strange issue after adding:

```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-sleuth</artifactId>
                <version>1.0.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
   <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
    </dependency>
```

to my pom.xml. It breaks a class which uses `@ConfigurationProperties`. Exception:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:478)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'loginController': Could not bind properties to LoginController (prefix=myPrefix, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is java.lang.NullPointerException
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:339)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:289)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:100)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:88)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:120)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:1)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
	at org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration.afterSingletonsInstantiated(ConfigurationPropertiesRebinderAutoConfiguration.java:79)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:792)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
	at com.company.myproject.Application.main(Application.java:13)
	... 6 more
Caused by: java.lang.NullPointerException
	at org.springframework.boot.bind.RelaxedDataBinder.extendCollectionIfNecessary(RelaxedDataBinder.java:341)
	at org.springframework.boot.bind.RelaxedDataBinder.initializePath(RelaxedDataBinder.java:291)
	at org.springframework.boot.bind.RelaxedDataBinder.normalizePath(RelaxedDataBinder.java:259)
	at org.springframework.boot.bind.RelaxedDataBinder.modifyProperty(RelaxedDataBinder.java:240)
	at org.springframework.boot.bind.RelaxedDataBinder.modifyProperties(RelaxedDataBinder.java:155)
	at org.springframework.boot.bind.RelaxedDataBinder.doBind(RelaxedDataBinder.java:128)
	at org.springframework.validation.DataBinder.bind(DataBinder.java:715)
	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:269)
	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:241)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:334)
	... 26 more
```

I inject a list of instances using yml:
```
myPrefix.locales:
    -
      code: "en"
      language: "English"
    -
      code: "sv"
      language: "Svenska"
```

```
@Data
@Component
public class Locale {
    private String code;
    private String language;
}
```

and this list is injected despite of error ( I log list values it in `@PostConstruct` method ), but then it fails with above exception.

spring boot version: 1.3.5.RELEASE

it works fine without sleuth.

**Comment by marcingrzejszczak** [comment]
Your setup seems to be wrong...  Check out - http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_adding_to_the_project - to see how to add Sleuth to the project and try again.

**Comment by michalkarolik** [comment]
I've changed it to use 
```
<artifactId>spring-cloud-dependencies</artifactId>
<version>Brixton.RELEASE</version>
```
but still same issue. Im afraid there is some clash between dependencies.

**Comment by marcingrzejszczak** [comment]
Can you post your sample project somewhere so that we can investigate it?

**Comment by michalkarolik** [comment]
Would love to, but I am not available to reproduce it in sample project. Seems its connected with Brixton.RELEASE vs Angel.SR6 not sleuth. Please close this issue, I will create another one when I find more details.

**Comment by murphye** [comment]
Same problem with spring-cloud-starter-feign 1.2.3.RELEASE... problem might be somewhere else in Spring Cloud dependencies

**Comment by marcingrzejszczak** [comment]
Are you using the release train or just bumping versions yourself @murphye ?

**Comment by michalkarolik** [comment]
hi @murphye what I did is just create another service:


```@Component
@ConfigurationProperties(prefix="myPrefix", ignoreInvalidFields = true)
public class LocaleService {
    private List<Locale> locales = new ArrayList<Locale>(10);
    public List<Locale> getLocales() {
        return locales;
    }
    public void setLocales(List<Locale> locales) {
        this.locales = locales;
    }
}
```



with properties as in original post + Locale bean:
```@Data
@Component
public class Locale {
    private String code;
    private String language;
}
```


and autowire service in a place where I needed this list of locales. Then just call `getLocales` from service. For some unknown reason it didnt want to work by injecting list of locales directly to class which is using them - (in my case it is abstract class, but it wasnt a root of this issue if I remember correctly).
