### ISSUE TITLE
"Retries exhausted for message" when I hit a service

### ISSUE THREAD

**Issue by vigohe** [spring-cloud/spring-cloud-sleuth#357]
Hi,

I did a server with the "@EnableZipkinStreamServer" annotation ( https://github.com/vigohe/zipkin-server ) and when I hit an api the zipkin server send me this stack trace.

```
2016-07-28 16:06:48.035  WARN [-,,,] 7312 --- [sleuth.sleuth-1] o.s.a.r.r.RejectAndDontRequeueRecoverer  : Retries exhausted for message (Body:'[B@616d2c29(byte[423])'MessageProperties [headers={X-B3-SpanId=758b4392500aab48, X-B3-Sampled=0, X-Message-Sent=true, X-B3-TraceId=758b4392500aab48, X-Current-Span=[Trace: 758b4392500aab48, Span: 758b4392500aab48, exportable=false], contentType=application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans, originalContentType=application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans}, timestamp=null, messageId=null, userId=null, appId=null, clusterId=null, type=null, correlationId=null, replyTo=null, contentType=application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans, contentEncoding=null, contentLength=0, deliveryMode=null, expiration=null, priority=0, redelivered=false, receivedExchange=sleuth, receivedRoutingKey=sleuth, deliveryTag=1, messageCount=0])

org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Listener threw exception
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:865) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:760) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:680) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:93) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:183) ~[spring-rabbit-1.5.6.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) ~[spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:74) ~[spring-retry-1.1.3.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276) [spring-retry-1.1.3.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:172) [spring-retry-1.1.3.RELEASE.jar:na]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:98) [spring-retry-1.1.3.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) [spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at com.sun.proxy.$Proxy102.invokeListener(Unknown Source) [na:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1358) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:661) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1102) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1086) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1100(SimpleMessageListenerContainer.java:93) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1203) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [sleuth.sleuth.convert.bridge]; nested exception is com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 113, Size: 7
Serialization trace:
parents (org.springframework.cloud.sleuth.Span)
spans (org.springframework.cloud.sleuth.stream.Spans)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:139) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:392) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) ~[spring-messaging-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) ~[spring-messaging-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) ~[spring-messaging-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:105) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$400(AmqpInboundChannelAdapter.java:45) ~[spring-integration-amqp-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$1.onMessage(AmqpInboundChannelAdapter.java:93) ~[spring-integration-amqp-4.2.9.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:757) [spring-rabbit-1.5.6.RELEASE.jar:na]
	... 24 common frames omitted
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 113, Size: 7
Serialization trace:
parents (org.springframework.cloud.sleuth.Span)
spans (org.springframework.cloud.sleuth.stream.Spans)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686) ~[kryo-shaded-3.0.3.jar:na]
	at org.springframework.integration.codec.kryo.PojoCodec.doDecode(PojoCodec.java:97) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.codec.kryo.AbstractKryoCodec$3.execute(AbstractKryoCodec.java:96) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61) ~[kryo-shaded-3.0.3.jar:na]
	at org.springframework.integration.codec.kryo.AbstractKryoCodec.decode(AbstractKryoCodec.java:93) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.codec.kryo.AbstractKryoCodec.decode(AbstractKryoCodec.java:79) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayload(AbstractBinder.java:288) ~[spring-cloud-stream-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayload(AbstractBinder.java:263) ~[spring-cloud-stream-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayloadIfNecessary(AbstractBinder.java:243) ~[spring-cloud-stream-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayloadIfNecessary(AbstractBinder.java:237) ~[spring-cloud-stream-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.access$700(RabbitMessageChannelBinder.java:102) ~[spring-cloud-stream-binder-rabbit-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder$ReceivingHandler.handleRequestMessage(RabbitMessageChannelBinder.java:637) ~[spring-cloud-stream-binder-rabbit-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:99) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	... 37 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index: 113, Size: 7
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_91]
	at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_91]
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:834) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:706) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:na]
	... 58 common frames omitted

2016-07-28 16:06:48.037  WARN [-,,,] 7312 --- [sleuth.sleuth-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.

org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Retry Policy Exhausted
	at org.springframework.amqp.rabbit.retry.RejectAndDontRequeueRecoverer.recover(RejectAndDontRequeueRecoverer.java:44) ~[spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.config.StatelessRetryOperationsInterceptorFactoryBean$1.recover(StatelessRetryOperationsInterceptorFactoryBean.java:59) ~[spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.config.StatelessRetryOperationsInterceptorFactoryBean$1.recover(StatelessRetryOperationsInterceptorFactoryBean.java:53) ~[spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$ItemRecovererCallback.recover(RetryOperationsInterceptor.java:124) ~[spring-retry-1.1.3.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.handleRetryExhausted(RetryTemplate.java:473) ~[spring-retry-1.1.3.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:333) ~[spring-retry-1.1.3.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:172) ~[spring-retry-1.1.3.RELEASE.jar:na]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:98) ~[spring-retry-1.1.3.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at com.sun.proxy.$Proxy102.invokeListener(Unknown Source) ~[na:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1358) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:661) ~[spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1102) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1086) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1100(SimpleMessageListenerContainer.java:93) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1203) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Listener threw exception
	... 18 common frames omitted
Caused by: org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Listener threw exception
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:865) ~[spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:760) ~[spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:680) ~[spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:93) [spring-rabbit-1.5.6.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:183) ~[spring-rabbit-1.5.6.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) ~[spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:74) ~[spring-retry-1.1.3.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276) ~[spring-retry-1.1.3.RELEASE.jar:na]
	... 12 common frames omitted
Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [sleuth.sleuth.convert.bridge]; nested exception is com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 113, Size: 7
Serialization trace:
parents (org.springframework.cloud.sleuth.Span)
spans (org.springframework.cloud.sleuth.stream.Spans)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:139) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:392) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) ~[spring-messaging-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) ~[spring-messaging-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) ~[spring-messaging-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:105) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$400(AmqpInboundChannelAdapter.java:45) ~[spring-integration-amqp-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$1.onMessage(AmqpInboundChannelAdapter.java:93) ~[spring-integration-amqp-4.2.9.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:757) ~[spring-rabbit-1.5.6.RELEASE.jar:na]
	... 24 common frames omitted
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 113, Size: 7
Serialization trace:
parents (org.springframework.cloud.sleuth.Span)
spans (org.springframework.cloud.sleuth.stream.Spans)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686) ~[kryo-shaded-3.0.3.jar:na]
	at org.springframework.integration.codec.kryo.PojoCodec.doDecode(PojoCodec.java:97) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.codec.kryo.AbstractKryoCodec$3.execute(AbstractKryoCodec.java:96) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61) ~[kryo-shaded-3.0.3.jar:na]
	at org.springframework.integration.codec.kryo.AbstractKryoCodec.decode(AbstractKryoCodec.java:93) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.codec.kryo.AbstractKryoCodec.decode(AbstractKryoCodec.java:79) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayload(AbstractBinder.java:288) ~[spring-cloud-stream-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayload(AbstractBinder.java:263) ~[spring-cloud-stream-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayloadIfNecessary(AbstractBinder.java:243) ~[spring-cloud-stream-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayloadIfNecessary(AbstractBinder.java:237) ~[spring-cloud-stream-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.access$700(RabbitMessageChannelBinder.java:102) ~[spring-cloud-stream-binder-rabbit-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder$ReceivingHandler.handleRequestMessage(RabbitMessageChannelBinder.java:637) ~[spring-cloud-stream-binder-rabbit-1.0.3.BUILD-20160718.221710-5.jar:1.0.3.BUILD-SNAPSHOT]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:99) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.2.9.RELEASE.jar:na]
	... 37 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index: 113, Size: 7
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_91]
	at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_91]
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:834) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:706) ~[kryo-shaded-3.0.3.jar:na]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-shaded-3.0.3.jar:na]
	... 58 common frames omitted
```

**Comment by marcingrzejszczak** [comment]
@mbogoevici does it ring any bells? I have never seen this `com.esotericsoftware.kryo.Kryo` as a serializer. Maybe that's the issue?

**Comment by marcingrzejszczak** [comment]
@mbogoevici told me the following

> it means that they're not sent as JSON
> something is wrong with the configuration and since the framework doesn't know how to serialize the data it sends it using the default serialization which is Kryo
> it seems like the classes on the other end do not match, but that's not the problem to solve
> the real issue is that data is not sent as JSON for whatever reason

Most likely you're client app is sending Spans in a wrong format. Can you show us / post somewhere your client app?

**Comment by marcingrzejszczak** [comment]
ping @vigohe

**Comment by marcingrzejszczak** [comment]
ping @vigohe

**Comment by vigohe** [comment]
I will try tomorrow

**Comment by renpengben** [comment]
I am the same question, Spans is the default。no set of anything。

```

@EnableFeignClients
@SpringCloudApplication
public class FeignApplication {
         public static void main(String[] args) {
        SpringApplication.run(FeignApplication.class, args);
    }
    @Bean
    AlwaysSampler alwaysSampler(){
        return new AlwaysSampler();
    }
}
```

**Comment by marcingrzejszczak** [comment]
Yeah the best thing will be to post the whole sample. Props, code, Pom.

**Comment by renpengben** [comment]
hi @marcingrzejszczak  this is the code 
https://github.com/renpengben/spring-cloud-study-demo
```
Zipkin Server
http://localhost:9999/add?a=1&b=2

service-1
http://localhost:6868/add?a=1&b=2

service-2
http://localhost:7777/add?a=1&b=2

when request  http://localhost:7777/add?a=1&b=2 ,Zipkin Service error
```

**Comment by marcingrzejszczak** [comment]
Ok I've checked your sample. It's working fine - your setup is really wrong.

In client apps you have added

```

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
        </dependency>
```

^^ this is a dependency for the Zipkin Collector only! http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_zipkin_consumer

I'm attaching a patch to your project that should make things work. You have to update `spring.rabbitmq.host` from my docker-machine ip to localhost.

[make_this_work.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/406814/make_this_work.txt)
