### ISSUE TITLE
NullpointerException in TraceFeignRetryer when using Retryer

### ISSUE THREAD

**Issue by thyzzv** [spring-cloud/spring-cloud-sleuth#362]
I'm trying to implement a custom ErrorDecoder that forces a retry on a specific Errorcode.
While trying some options I run into a Nullpointer in TraceFeignRetryer

See [thyzzv:sleuthspan-test](https://github.com/thyzzv/sleuthspan-test) latest master
Run the example "mvn spring-boot:run"

You will see:
`java.lang.NullPointerException: null
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignRetryer.continueOrPropagate(TraceFeignRetryer.java:56)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy100.exp(Unknown Source)
	at net.test.sleuth.controllers.SleuthTestController.notOk(SleuthTestController.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

**Comment by marcingrzejszczak** [comment]
I think it's high time to do this - https://github.com/spring-cloud/spring-cloud-sleuth/issues/202 cc @spencergibb @adriancole . I'll have to sit down and think on how to add the pre and post process hooks to Feign

**Comment by marcingrzejszczak** [comment]
Related PR - spring-cloud/spring-cloud-sleuth#367

**Comment by marcingrzejszczak** [comment]
Should be fixed thanks to https://github.com/spring-cloud/spring-cloud-sleuth/pull/372
