### ISSUE TITLE
Java Heap Space OOM

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#415]
_From @teamenergy on September 28, 2016 14:30_

Hi, 
We are running zipkin:latest on docker 1.2.1 in swarm mode. The server zipkin is running on has more than sufficient memory.
Periodically, zipkin will report a channel shutdown connection error, throw a Java Heap OOM, then tie up all the available cpu on the node. There is no recovery other than stopping the service and restarting it. There are no logs before the initial OOM. 
Any thoughts?

typical log output:
### 2016-09-28 09:16:33.673  INFO [zipkin-server,,,] 1 --- [           main] c.t.c.m.ZipkinServerApplication          : Started ZipkinServerApplication in 11.568 seconds (JVM running for 12.116)
2016-09-28 13:44:04.908 ERROR [zipkin-server,,,] 1 --- [.168.99.18:5672] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: connection error
2016-09-28 13:45:10.150  WARN [zipkin-server,,,] 1 --- [ask-scheduler-8] o.s.i.c.MessagePublishingErrorHandler    : Error message was not delivered.

java.lang.OutOfMemoryError: Java heap space
        at org.springframework.integration.channel.MessagePublishingErrorHandler.handleError(MessagePublishingErrorHandler.java:85) ~[spring-integration-core-4.2.5.RELEASE.jar!/:na]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:60) [spring-context-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_92]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_92]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

2016-09-28 13:45:10.152 ERROR [zipkin-server,,,] 1 --- [-ClientPoller-0] org.apache.tomcat.util.net.NioEndpoint   : 

java.lang.OutOfMemoryError: Java heap space

2016-09-28 13:45:10.152 ERROR [zipkin-server,,,] 1 --- [-ClientPoller-1] org.apache.tomcat.util.net.NioEndpoint   : 

java.lang.OutOfMemoryError: Java heap space

2016-09-28 13:45:10.152 ERROR [zipkin-server,,,] 1 --- [ndardContext[]]] org.apache.catalina.core.ContainerBase   : Unexpected death of background thread ContainerBackgroundProcessor[StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]

java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.ConcurrentHashMap$ValuesView.iterator(ConcurrentHashMap.java:4683) ~[na:1.8.0_92]
        at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[na:1.8.0_92]
        at java.util.TreeSet.addAll(TreeSet.java:312) ~[na:1.8.0_92]
        at org.apache.catalina.webresources.Cache.backgroundProcess(Cache.java:190) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
        at org.apache.catalina.webresources.StandardRoot.backgroundProcess(StandardRoot.java:595) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
        at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5627) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1377) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1349) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

Exception in thread "ContainerBackgroundProcessor[StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]" java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.ConcurrentHashMap$ValuesView.iterator(ConcurrentHashMap.java:4683)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
2016-09-28 13:45:47.125  WARN [zipkin-server,,,] 1 --- [sleuth.sleuth-1] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it

com.rabbitmq.client.ShutdownSignalException: connection error
        at com.rabbitmq.client.impl.AMQConnection.startShutdown(AMQConnection.java:723) ~[amqp-client-3.5.7.jar!/:na]
        at com.rabbitmq.client.impl.AMQConnection.shutdown(AMQConnection.java:713) ~[amqp-client-3.5.7.jar!/:na]
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:571) ~[amqp-client-3.5.7.jar!/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_92]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_92]
        at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_92]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_92]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_92]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_92]
        at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[na:1.8.0_92]
        at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95) ~[amqp-client-3.5.7.jar!/:na]
        at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139) ~[amqp-client-3.5.7.jar!/:na]
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:536) ~[amqp-client-3.5.7.jar!/:na]
        ... 1 common frames omitted

        at java.util.TreeSet.addAll(TreeSet.java:312)
2016-09-28 13:46:04.911 ERROR [zipkin-server,,,] 1 --- [-ClientPoller-0] org.apache.tomcat.util.net.NioEndpoint   : 

java.lang.OutOfMemoryError: Java heap space

        at org.apache.catalina.webresources.Cache.backgroundProcess(Cache.java:190)
        at org.apache.catalina.webresources.StandardRoot.backgroundProcess(StandardRoot.java:595)
2016-09-28 13:49:05.183  INFO [zipkin-server,,,] 1 --- [sleuth.sleuth-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer: tags=[{amq.ctag-QKEr3Ah-JjhllOcXGVn8mg=sleuth.sleuth}], channel=Cached Rabbit Channel: AMQChannel(amqp://guest@192.168.99.18:5672/,1), conn: Proxy@559dc2c1 Shared Rabbit Connection: SimpleConnection@54191b31 [delegate=amqp://guest@192.168.99.18:5672/], acknowledgeMode=AUTO local queue size=0
        at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5627)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1377)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1349)
        at java.lang.Thread.run(Thread.java:745)

_Copied from original issue: openzipkin/docker-zipkin#120_

**Comment by adriancole** [comment]
Just looking at the output, it appears sleuth and rabbitmq are in use. I'm not sure, but it could possibly be using the stream component in this repository.

@teamenergy so do you have any way to identify the layers of this docker image?

**Comment by teamenergy** [comment]
My very thought - trying to get that info now.

**Comment by adriancole** [comment]
another way to get more info could be to do get the info endpoint and the beans list.. `curl -s localhost:9411/info` `curl -s localhost:9411/beans`

anyway, if you are indeed running the stock zipkin image, you should be able to adjust the memory via the `JAVA_OPTS` variable. Maybe the VM isn't using what the container has available. ex. `JAVA_OPTS=-Xms1024m -Xmx1024m` for 1 gig

**Comment by adriancole** [comment]
not localhost of course :)

I'm punching out as late my time. if this is sleuth related and not solvable with config, you can try pinging here, too https://gitter.im/spring-cloud/spring-cloud-sleuth

**Comment by marcingrzejszczak** [comment]
Actually that does ring a bell. Are you guys using Sleuth Stream < 1.0.9 ? @teamenergy

**Comment by marcingrzejszczak** [comment]
If that's the case there was a bug with repeated headers appending that could be endless. Try bumping to 1.0.9 (a.k.a. Brixton.SR6 / Camden.RELEASE)

**Comment by marcingrzejszczak** [comment]
ping?

**Comment by marcingrzejszczak** [comment]
@teamenergy last ping before we close it due to inactivity

**Comment by teamenergy** [comment]
Apols – please close – priority shift so couldn’t follow up at this time.
