### ISSUE TITLE
Dependency glitch between 1.1.0.RELEASE and 1.1.1.RELEASE

### ISSUE THREAD

**Issue by adriancole** [spring-cloud/spring-cloud-sleuth#511]
A project with the following dependencies fails to load after bumping from 1.1.0 to 1.1.1 (or 1.1.2)

```
  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-sleuth</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-sleuth-zipkin</artifactId>
    </dependency>
  </dependencies>
```

Here's the failure
```
Caused by: java.lang.IllegalStateException: Failed to introspect bean class [org.springframework.cloud.sleuth.zipkin.ZipkinAutoConfiguration$DefaultEndpointLocatorConfiguration$$EnhancerBySpringCGLIB$$bebc40f6] for resource metadata: could not find class that it depends on
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.findResourceMetadata(CommonAnnotationBeanPostProcessor.java:344)
--snip--
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.commons.util.InetUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 83 more
```

**Comment by adriancole** [comment]
looks like in 1.1.0, spring-cloud-starter-sleuth had a dep on spring-cloud-starter, which in turn had a dep on spring-cloud-commons

**Comment by adriancole** [comment]
I'm guessing that class was missing in spring-cloud-commons 1.1.7.RELEASE, as adding the following fixes the bug:
```
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-commons</artifactId>
      <version>1.1.8.BUILD-SNAPSHOT</version>
    </dependency>
```

**Comment by adriancole** [comment]
actually that class is there in spring-cloud-commons 1.1.7.. I don't know why updating the dep works.

I suspect we should cut 1.1.8 and then a release of sleuth that uses it quickly? wdyt @marcingrzejszczak @ryanjbaxter

**Comment by adriancole** [comment]
here's an example project that breaks unless the snapshot version is present https://github.com/openzipkin/sleuth-webmvc-example#starting-the-services

**Comment by marcingrzejszczak** [comment]
Can't replicate this :( I removed the added dependency and everything works fine - https://circleci.com/gh/marcingrzejszczak/sleuth-webmvc-example/14

**Comment by adriancole** [comment]
nuking ~/.m2/repository/org/springframework/cloud fixed it. Maybe there was a messed up release in there somehow.

thanks @marcingrzejszczak
