### ISSUE TITLE
Absent ErrorController produce exception in TraceHandlerInterceptor

### ISSUE THREAD

**Issue by zeldigas** [spring-cloud/spring-cloud-sleuth#512]
TraceHandlerInterceptor explicitly tightly depends on ErrorController - although it's injection is not required it's loaded without exception handling:
```java
       private ErrorController getErrorController() {
		if (this.errorController == null) {
			this.errorController = this.beanFactory.getBean(ErrorController.class);
		}
		return this.errorController;
	}
```
I think it should be explicitly stated in docs that the instance of ErrorController is required, or exception handling should be added.

Steps to reproduce.
1. Create boot project with attached sleuth and sample controller
2. Exclude ErrorMvcAutoConfiguration and don't create ErrorController instance manually
3. call sample controller

Expected result: all is fine, response from controller
Actual result: exception
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.boot.autoconfigure.web.ErrorController] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:374) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:371) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:334) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.cloud.sleuth.instrument.web.TraceHandlerInterceptor.getErrorController(TraceHandlerInterceptor.java:192) ~[spring-cloud-sleuth-core-1.0.11.RELEASE.jar:1.0.11.RELEASE]
	at org.springframework.cloud.sleuth.instrument.web.TraceHandlerInterceptor.isErrorControllerRelated(TraceHandlerInterceptor.java:89) ~[spring-cloud-sleuth-core-1.0.11.RELEASE.jar:1.0.11.RELEASE]
	at org.springframework.cloud.sleuth.instrument.web.TraceHandlerInterceptor.preHandle(TraceHandlerInterceptor.java:65) ~[spring-cloud-sleuth-core-1.0.11.RELEASE.jar:1.0.11.RELEASE]
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:134) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:958) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.4.jar:8.5.4]
```

**Comment by zeldigas** [comment]
it's present in 1.0.x as well

**Comment by marcingrzejszczak** [comment]
Thanks for showing this! Really good catch :) 

As for 1.0.x - we no longer support this branch that's why I've set the `1.1.3`.

**Comment by marcingrzejszczak** [comment]
@zeldigas ^^ fixed caching - https://github.com/spring-cloud/spring-cloud-sleuth/commit/694b929db376b675a3c5f1904ca5cee7ae234a35

**Comment by zeldigas** [comment]
@marcingrzejszczak cool, thank you!
