### ISSUE TITLE
Correct versions of spring-cloud-sleuth-stream, spring-boot, and spring-cloud-stream-binder-kafka?

### ISSUE THREAD

**Issue by dmmx** [spring-cloud/spring-cloud-sleuth#571]
I am trying to get a very simple spring boot application to send trace data to a zipkin-server listening on a kafka topic.

I have tried numerous configuration all producing different exceptions. 

My latest gradle.build files looks like this:

```groovy
buildscript {
  repositories {
	mavenCentral()
  }
  dependencies {
	classpath("org.springframework.boot:spring-boot-gradle-plugin:1.5.2.RELEASE")
	classpath "io.spring.gradle:dependency-management-plugin:0.5.2.RELEASE"
  }
}

// Apply the java plugin to add support for Java
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: "io.spring.dependency-management"

jar {
  baseName = 'sleuth-test-app'
  version  = '0.1.0'
  manifest {
    attributes(
	  'Main-Class': 'hello.Application'
    )
  }
}


repositories {
    mavenCentral()
}


sourceCompatibility = 1.8
targetCompatibility = 1.8

// In this section you declare the dependencies for your production and test code
dependencies {
    // The production code uses the SLF4J logging API at compile time
    compile 'org.slf4j:slf4j-api:1.7.21'

    // tag::jetty[]
    compile("org.springframework.boot:spring-boot-starter-web:1.4.4.RELEASE") {
        exclude module: "spring-boot-starter-tomcat"
    }
    compile("org.springframework.boot:spring-boot-starter-jetty:1.4.4.RELEASE")
    // end::jetty[]
    // tag::actuator[]
    compile("org.springframework.boot:spring-boot-starter-actuator:1.4.4.RELEASE")
    // end::actuator[]


	compile("org.springframework.cloud:spring-cloud-starter-sleuth:1.2.0.RELEASE")
        compile "org.springframework.cloud:spring-cloud-sleuth-stream:1.2.0.RELEASE"
	compile "org.springframework.cloud:spring-cloud-stream-binder-kafka:1.2.0.RELEASE"

    testCompile("junit:junit")
}
```

With this configuration, the last thing to appear in the application log comes from Kafka

```
2017-04-21 13:55:39,594  INFO main o.a.k.c.p.ProducerConfig:180 - ProducerConfig values:
        acks = 1
        batch.size = 16384
        block.on.buffer.full = false
        bootstrap.servers = [kafka:9092]
        buffer.memory = 33554432
        client.id = producer-1
        compression.type = none
        connections.max.idle.ms = 540000
        interceptor.classes = null
        key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
        linger.ms = 0
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 5
        max.request.size = 1048576
        metadata.fetch.timeout.ms = 60000
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 0
        retry.backoff.ms = 100
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        timeout.ms = 30000
        value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer

2017-04-21 13:55:39,680  WARN main o.a.k.c.p.ProducerConfig:188 - The configuration 'key.deserializer' was supplied but isn't a known config.
2017-04-21 13:55:39,680  WARN main o.a.k.c.p.ProducerConfig:188 - The configuration 'value.deserializer' was supplied but isn't a known config.
```

But my application does not start.

My application is dead simple. It is based on the Spring Boot and Sleuth examples:

```java
package hello;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class Application {

	static Logger logger = LoggerFactory.getLogger(Application.class);

	@RequestMapping("/")
	public String home() {
		logger.info("Handling home");
		return "Hello World";
	}

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
```

My `application.properties` contains the config for Kafka
```properties
spring.application.name=sleuth-test-app
spring.cloud.stream.kafka.binder.zkNodes=broker
spring.cloud.stream.kafka.binder.brokers=broker
spring.cloud.stream.default.contentType=application/json
spring.cloud.stream.bindings.output.destination=topic.name
```

I have also tried several different mavenBom settings:

- `mavenBom 'org.springframework.cloud:spring-cloud-sleuth:1.2.0.RELEASE'`
- `mavenBom "org.springframework.cloud:spring-cloud-dependencies:Camden.SR6"`
- `mavenBom "org.springframework.cloud:spring-cloud-dependencies:Camden.RELEASE"`
- `mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.BUILD-SNAPSHOT"`
- `mavenBom 'org.springframework.cloud:spring-cloud-stream-dependencies:Chelsea.SR1'`

I feel like this is a dependency configuration issue, but I cannot seem to determine the correct configuration. Can someone help?

**Comment by marcingrzejszczak** [comment]
@dmmx please use a Spring Cloud Release Train BOM like presented here - https://projects.spring.io/spring-cloud/ . Then you don't have to provide any versions - they are provided for you. If you don't want to do that you have to reverse engineer the versions that we pass in the BOM https://github.com/spring-cloud/spring-cloud-release/blob/vDalston.RELEASE/spring-cloud-dependencies/pom.xml#L18-L31 .

**Comment by adiskp** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/43291655/58229817-43cee900-7d50-11e9-920f-e6770676d2c2.png)

i am using jmeter to create kafka topics, but it gives nullPointer Exception.

2019-05-23 10:13:49,110 WARN o.a.k.c.p.ProducerConfig: The configuration sasl.mechanism = GSSAPI was supplied but isn't a known config.
2019-05-23 10:13:49,111 INFO o.a.k.c.u.AppInfoParser: Kafka version : 0.9.0.1
2019-05-23 10:13:49,111 INFO o.a.k.c.u.AppInfoParser: Kafka commitId : 23c69d62a0cabf06
2019-05-23 10:13:49,208 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2019-05-23 10:13:49,208 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2019-05-23 10:13:49,208 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2019-05-23 10:13:49,208 INFO o.a.k.c.p.KafkaProducer: Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2019-05-23 10:13:49,218 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)
2019-05-23 11:42:01,312 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2019-05-23 11:42:01,318 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-05-23 11:42:01,319 INFO o.a.j.p.j.t.JavaTest: Created class: com.gslab.pepper.sampler.PepperBoxKafkaSampler. Uses tearDownTest: 
2019-05-23 11:42:01,320 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2019-05-23 11:42:01,707 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2019-05-23 11:42:01,707 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2019-05-23 11:42:01,707 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2019-05-23 11:42:01,707 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2019-05-23 11:42:01,707 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2019-05-23 11:42:01,707 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2019-05-23 11:42:01,707 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2019-05-23 11:42:01,863 INFO o.a.z.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=10000 watcher=null
2019-05-23 11:42:01,878 INFO o.a.z.ClientCnxn: Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2019-05-23 11:42:01,878 INFO o.a.z.ClientCnxn: Socket connection established to 127.0.0.1/127.0.0.1:2181, initiating session
2019-05-23 11:42:02,019 INFO o.a.z.ClientCnxn: Session establishment complete on server 127.0.0.1/127.0.0.1:2181, sessionid = 0x100048f202c0004, negotiated timeout = 10000
2019-05-23 11:42:02,019 ERROR o.a.z.ClientCnxn: Error while calling watcher 
java.lang.NullPointerException: null
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522) [pepper-box-1.0.jar:?]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) [pepper-box-1.0.jar:?]
2019-05-23 11:42:02,019 INFO o.a.k.c.p.ProducerConfig: ProducerConfig values: 
	compression.type = none
	metric.reporters = []
	metadata.max.age.ms = 300000
	metadata.fetch.timeout.ms = 60000
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	bootstrap.servers = [D-313071501.wipro.com:9092]
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.keystore.type = JKS
	ssl.trustmanager.algorithm = PKIX
	block.on.buffer.full = false
	ssl.key.password = null
	max.block.ms = 60000
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	ssl.truststore.password = null
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	client.id = 
	ssl.endpoint.identification.algorithm = null
	ssl.protocol = TLS
	request.timeout.ms = 30000
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	acks = 1
	batch.size = 16384
	ssl.keystore.location = null
	receive.buffer.bytes = 32768
	ssl.cipher.suites = null
	ssl.truststore.type = JKS
	security.protocol = PLAINTEXT
	retries = 0
	max.request.size = 1048576
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer
	ssl.truststore.location = null
	ssl.keystore.password = null
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	send.buffer.bytes = 131072
	linger.ms = 0

**Comment by marcingrzejszczak** [comment]
Please use the BOM. You can find all the versions of the latest release train here https://github.com/spring-cloud/spring-cloud-release/blob/vGreenwich.SR1/spring-cloud-dependencies/pom.xml
