### ISSUE TITLE
Spring Cloud Sleuth to Zipkin via Kafka not working

### ISSUE THREAD

**Issue by dmmx** [spring-cloud/spring-cloud-sleuth#578]
I am having trouble configuring a Spring Boot application to have Spring Cloud Sleuth send data to Zipkin using Kafka.

I orginally thought this might be a versioning issue. See issue #571. For that issue @marcingrzejszczak suggested I use the Spring Cloud Release Train BOM (Dalston.RELEASE). Based on that suggestion here is my latest `build.gradle` file:

```groovy
buildscript {
  ext {
	springBootVersion = '1.5.2.RELEASE'
  }
  repositories {
	mavenCentral()
  }
  dependencies {
	classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	classpath "io.spring.gradle:dependency-management-plugin:0.5.2.RELEASE"
  }
}

// Apply the java plugin to add support for Java
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: "io.spring.dependency-management"

jar {
  baseName = 'sleuth-test-app'
  version  = '0.1.0'
  manifest {
    attributes(
	  'Main-Class': 'hello.Application'
    )
  }
}


repositories {
    mavenCentral()
}


sourceCompatibility = 1.8
targetCompatibility = 1.8


dependencyManagement {
     imports {
	   mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.RELEASE"
     }
}


// In this section you declare the dependencies for your production and test code
dependencies {
    // The production code uses the SLF4J logging API at compile time
    compile 'org.slf4j:slf4j-api:1.7.21'

    // tag::jetty[]
    compile("org.springframework.boot:spring-boot-starter-web") {
        exclude module: "spring-boot-starter-tomcat"
    }
    compile("org.springframework.boot:spring-boot-starter-jetty")
    // end::jetty[]
    // tag::actuator[]
    compile("org.springframework.boot:spring-boot-starter-actuator")
    // end::actuator[]

	compile("org.springframework.cloud:spring-cloud-starter-sleuth")
	
	compile "org.springframework.cloud:spring-cloud-sleuth-stream"
	compile "org.springframework.cloud:spring-cloud-stream-binder-kafka"

    testCompile("junit:junit")
}
```

Unfortunately this did not solve the issue I am running into.

My application is very simple. It is based of of the Spring Boot and Spring Cloud Sleuth examples:

```java
package hello;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class Application {

	static Logger logger = LoggerFactory.getLogger(Application.class);

	@RequestMapping("/")
	public String home() {
		logger.info("Handling home");
		return "Hello World";
	}

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
```

And here is the properties file I am using to configure the application:
```properties
spring.application.name=sleuth-test-app
spring.cloud.stream.kafka.binder.zkNodes=brokername
spring.cloud.stream.kafka.binder.brokers=brokername
spring.cloud.stream.default.contentType=application/json
spring.cloud.stream.bindings.output.destination=topicname
```

When I start the app, I don't get any errors but I am unable to reach the app. The last thing to show up in the logs in the `ProducerConfig values`:

```
2017-04-25 10:36:37,064  INFO main o.a.k.c.p.ProducerConfig:180 - ProducerConfig values:
        acks = 1
        batch.size = 16384
        block.on.buffer.full = false
        bootstrap.servers = [brokername:9092]
        buffer.memory = 33554432
        client.id = producer-1
        compression.type = none
        connections.max.idle.ms = 540000
        interceptor.classes = null
        key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
        linger.ms = 0
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 5
        max.request.size = 1048576
        metadata.fetch.timeout.ms = 60000
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 0
        retry.backoff.ms = 100
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        timeout.ms = 30000
        value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer

2017-04-25 10:36:37,148  WARN main o.a.k.c.p.ProducerConfig:188 - The configuration 'key.deserializer' was supplied but isn't a known config.
2017-04-25 10:36:37,148  WARN main o.a.k.c.p.ProducerConfig:188 - The configuration 'value.deserializer' was supplied but isn't a known config.
2017-04-25 10:36:37,151  INFO main o.a.k.c.u.AppInfoParser:83 - Kafka version : 0.10.1.1
2017-04-25 10:36:37,151  INFO main o.a.k.c.u.AppInfoParser:84 - Kafka commitId : f10ef2720b03b247
```

Any help would be greatly appreciated.

**Comment by marcingrzejszczak** [comment]
You're not able to reach which app? What does it mean that it's not reachable?

**Comment by dmmx** [comment]
I mean I am not able to access the app (`hello.Application` from above) at  http://localhost:8080/.

This all seems to work fine if I try to send data to Zipkin via http, but stops working when I switch to using Kafka.

**Comment by marcingrzejszczak** [comment]
And you have no exceptions or anything in the logs?

**Comment by ilayaperumalg** [comment]
@dmmx Just to double check on these configuration properties:

```
spring.cloud.stream.kafka.binder.zkNodes=brokername
spring.cloud.stream.kafka.binder.brokers=brokername

```

Have you configured the correct host names and port for `zkNodes` and `brokers`.

**Comment by dmmx** [comment]
@marcingrzejszczak The logs look clean. there are no errors or exceptions.

**Comment by marcingrzejszczak** [comment]
A stupid question - do you have anything to show at `localhost:8080/` is there an endpoint there or sth? If you check `localhost:8080/health` do you get anything there?

**Comment by dmmx** [comment]
@ilayaperumalg Thanks for asking about this. After fiddling with these settings a bit I was able to produce this error:

```
2017-04-25 14:37:13,051 ERROR kafka-producer-network-thread | producer-1 o.a.k.c.p.i.Sender:137 - Uncaught error in kafka producer I/O thread:
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'brokers': Error reading field 'host': Error reading string of length 25199, only 132 bytes available
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73) ~[kafka-clients-0.10.1.1.jar!/:na]
        at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:380) ~[kafka-clients-0.10.1.1.jar!/:na]
        at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:449) ~[kafka-clients-0.10.1.1.jar!/:na]
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:269) ~[kafka-clients-0.10.1.1.jar!/:na]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:236) ~[kafka-clients-0.10.1.1.jar!/:na]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:135) ~[kafka-clients-0.10.1.1.jar!/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
```

Does this indicate that my kafka client is at .10 and the broker I am trying to connect to is at .9?

If so, is there a way I can figure the sleuth/cloud stream client to use .9?

I am not able to change the version of the broker.

**Comment by dmmx** [comment]
@marcingrzejszczak Yes, when things are working correctly (accessing Zipkin via HTTP) the end point returns `Hello World`

**Comment by mbogoevici** [comment]
@dmmx  You can find some configuration examples for downgrading the client library here: http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Chelsea.SR1/reference/htmlsingle/#_using_the_binder_with_apache_kafka_0_10.

**Comment by dmmx** [comment]
I was able to find out from our Kafka admin that our broker is at version .8.2 not .9 as I previously thought.

Does anyone know how to configure spring-cloud-sleuth and spring-cloud-stream to use a kafka .8.2. client?

I've tried many different combinations and haven't had any luck.

**Comment by dmmx** [comment]
Decided to take a different approach for the integration.
