### ISSUE TITLE
Sleuth + Reactor. SpanSubscriber cannot be cast to reactor.core.Fuseable$QueueSubscription

### ISSUE THREAD

**Issue by msymonov** [spring-cloud/spring-cloud-sleuth#646]
We use Sleuth and Spring Reactor on our project. Official support hasn't been added yet, however i can see that some changes were done on both sides.
I have tried using Reactor `Bismuth-M3(3.1.0-SNAPSHOT)` and latest `Sleuth(1.3.0.BUILD-SNAPSHOT)` which has now 'spring-cloud-sleuth-reactor' module.

See the stacktrace:

```
java.lang.ClassCastException: org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber cannot be cast to reactor.core.Fuseable$QueueSubscription
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:172)
	at org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber.onSubscribe(SpanSubscriber.java:60)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:58)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2769)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:169)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:53)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2769)
	at reactor.core.publisher.MonoWhen$WhenCoordinator.subscribe(MonoWhen.java:177)
	at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:127)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:148)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1010)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:142)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1010)
	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:288)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	at rx.internal.reactivestreams.SingleAsPublisher$SingleAsPublisherSubscriber.onSuccess(SingleAsPublisher.java:86)
	at rx.Single$18.onNext(Single.java:1911)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.Single$1$1.onSuccess(Single.java:80)
	at rx.internal.operators.OnSubscribeSingle$1.onCompleted(OnSubscribeSingle.java:55)
	at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
	at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
	at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onCompleted(OperatorOnErrorResumeNextViaFunction.java:101)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$2.onCompleted(AbstractCommand.java:1185)
	at rx.internal.operators.OperatorSubscribeOn$1$1.onCompleted(OperatorSubscribeOn.java:68)
	at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onCompleted(AbstractCommand.java:1423)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onCompleted(AbstractCommand.java:1356)
	at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
	at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:285)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
	at rx.Subscriber.setProducer(Subscriber.java:209)
	at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixConcurrencyStrategy$HystrixTraceCallable.call(SleuthHystrixConcurrencyStrategy.java:154)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

**Comment by marcingrzejszczak** [comment]
Thanks so much for trying it out!! We'll look into that ASAP :)

**Comment by msymonov** [comment]
Hi, the issue is still reproducible on Spring Cloud Edgware.SR2(Sleuth 1.3.2). The stack trace is still the same. For now we see as specific scenario details only using of Hystrix with RxJava 1.2. So the scenario is as follows: Reactor-driven microservice accepts incoming HTTP request, does some business logic in Reactor environment, and then calls thirdparty service which is wrapped into Feign client returning RxJava Completable which is then transformed into Mono and sent back to Reactor pipeline.

See the stacktrace below:
```
java.lang.ClassCastException: org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber cannot be cast to reactor.core.Fuseable$QueueSubscription
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:89)
        at org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber.onSubscribe(SpanSubscriber.java:61)
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:54)
        at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46)
        at reactor.core.publisher.Mono.subscribe(Mono.java:3008)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:169)
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:53)
        at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
        at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
        at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:198)
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:198)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1092)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1092)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:142)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.ignoreDone(MonoIgnoreThen.java:185)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreInner.onComplete(MonoIgnoreThen.java:234)
        at org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber.onComplete(SpanSubscriber.java:135)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:245)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:245)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:1327)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:245)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:245)
        at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:96)
        at rx.internal.reactivestreams.CompletableAsPublisher$CompletableAsPublisherSubscriber.onCompleted(CompletableAsPublisher.java:70)
        at rx.observers.SafeCompletableSubscriber.onCompleted(SafeCompletableSubscriber.java:49)
        at rx.Completable$19$1.onCompleted(Completable.java:1378)
        at rx.Completable$10$1.onCompleted(Completable.java:576)
        at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
        at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
        at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
        at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onCompleted(OperatorOnErrorResumeNextViaFunction.java:101)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
        at rx.internal.operators.OperatorSubscribeOn$1$1.onCompleted(OperatorSubscribeOn.java:68)
        at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
        at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
        at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onCompleted(AbstractCommand.java:1423)
        at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onCompleted(AbstractCommand.java:1356)
        at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
        at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
        at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:285)
        at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
        at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.setProducer(OperatorOnErrorResumeNextViaFunction.java:159)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
        at rx.Observable.unsafeSubscribe(Observable.java:10151)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10151)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
        at rx.Observable.unsafeSubscribe(Observable.java:10151)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10151)
        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
        at org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixConcurrencyStrategy$HystrixTraceCallable.call(SleuthHystrixConcurrencyStrategy.java:188)
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by marcingrzejszczak** [comment]
Can you setup a sample that we can use to replicate this problem?

**Comment by msymonov** [comment]
See https://github.com/msymonov/sleuth-reactor-class-cast-exception please.
BugTest contains the simplified flow which triggers the aforementioned exception, but in short it seems that the flow could be described as:
1) we have a long execution pipeline
2) in the middle it has a statement which returns Mono.empty()
3) later on, after this statement, we have some mapping/flatmapping operators
4) in the end we have switchIfEmpty which switches the flow to the normal processing

My observation is that steps 2-3 are the cause, i.e. if any operators are following the step where empty Mono is returned, i.e. they are supposed to be skipped, then BANG!!!

**Comment by msymonov** [comment]
i think i have another observation, the case could simplified even more. And the output is that it is not about Mono.empty(), but rather because of "then(...)" statement, so as soon as you're switching the execution flow to another Mono, then the issue is reproduced

**Comment by msymonov** [comment]
Workaround was found. We are now using "flatMap" instead of "then"

**Comment by msymonov** [comment]
I have spotted an interesting fact, or actually there two of them:

```
public static <T> Function<? super Publisher<T>, ? extends Publisher<T>> spanOperator(Tracer tracer) {
		return Operators.lift(POINTCUT_FILTER, ((scannable, sub) -> {
			//do not trace fused flows
			if(scannable instanceof Fuseable && sub instanceof Fuseable.QueueSubscription){
				return sub;
			}
			return new SpanSubscriber<>(
					sub,
					sub.currentContext(),
					tracer,
					scannable.name());
		}));
	}
```

As is seen in a comment so-called fuseable flows shouldn't be traced. However the exception is thrown from FluxMapFuseable$MapFuseableSubscriber, so it seems that we're hitting the place where SpanSubscriber shouldn't be used at all.

Another interesting fact is that it all happens for "then" operator which is internally represented by MonoIgnoreThen class(probably not only by this one, but i can see that this one is involved in the flow), and what is important here is that this class doesn't implement Fuseable interface. I am not sure if this is the reason, and if it is an issue at all, but it could happen that the discussed issue is not a bug of Sleuth, but rather a bug of Reactor.
Do you have any thoughts on these items? Thanks in advance.

**Comment by msymonov** [comment]
I've done some experiments. As soon as i added implements Scannable and implemented one single method scanUnsafe everything finally started to work as expected:
`final class MonoIgnoreThen<T> extends Mono<T> implements Scannable, Fuseable {`

@smaldini, @marcingrzejszczak 
Could you please take a look? Thanks

**Comment by marcingrzejszczak** [comment]
Thanks, @msymonov for the great analysis. Thanks to it @simonbasle had less work in analyzing the root cause of the problem, and I had almost no work in fixing it :)
