### ISSUE TITLE
Dropped 2 spans due to IllegalArgumentException(URI is not absolute)

### ISSUE THREAD

**Issue by wpzym1125** [spring-cloud/spring-cloud-sleuth#666]
When I was using zipkin, I looked at the log and found that it was now and then with the following warming. It didn't affect the use. It seemed to be missing a few spans. I wonder why this happened? Is there any way to avoid it?

```
2017-08-02 23:43:07,154 WARN [zipkin.reporter.AsyncReporter$BoundedAsyncReporter] [] []- Dropped 2 spans due to IllegalArgumentException(URI is not absolute)
java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088)
	at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:137)
	at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:85)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:648)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:590)
	at org.springframework.cloud.sleuth.zipkin.RestTemplateSender.post(RestTemplateSender.java:73)
	at org.springframework.cloud.sleuth.zipkin.RestTemplateSender.sendSpans(RestTemplateSender.java:46)
	at zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:228)
	at zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:153)
	at zipkin.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by adriancole** [comment]
seems like the zipkin url validation could be moved up a bit, so that it
causes the server to fail at bootstrap vs later?

**Comment by wpzym1125** [comment]
here is sleuth server's application.yml:
security:
  basic:
    enabled: true
  user:
    name: server-sleuth
    password: 35446Q3QJS7UvVdN
server:
  port: 6050
spring:
  application:
    name: yjy-server-sleuth
logging:
  config: classpath:logback.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://server-eureka:2lvoHcfXbXmTBvQm@localhost:6000/eureka,http://server-eureka:2lvoHcfXbXmTBvQm@localhost:6001/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

and the client's application.yml:
spring:
  application:
    name: yjy-provider-user
  zipkin:
    locator:
      discovery:
        enabled: true
    base-url: yjy-server-sleuth
so i don't know why this happened and can't understant you well,can you description detaily?thank you.

**Comment by adriancole** [comment]
>
> zipkin:
> locator:
> discovery:
> enabled: true
> base-url: yjy-server-sleuth
>
I suspect this is it @marcingrzejszczak?

**Comment by wpzym1125** [comment]
I find the configure from the offical document：

If you have the discovery client enabled and prefer to retrieve the host address from the registered instance in a service registry then you have to set the property (it’s applicable for both HTTP and Stream based span reporting).
spring.zipkin.locator.discovery.enabled: true
is this something wrong?

**Comment by marcingrzejszczak** [comment]
`base-url: yjy-server-sleuth` - are you using SNAPSHOTS? These feature is currently only available in `1.3.0.BUILD-SNAPSHOT` (https://github.com/spring-cloud/spring-cloud-sleuth/issues/640)

**Comment by wpzym1125** [comment]
here is my configure:
<groupId>cn.medtap.yjy.server</groupId>
	<artifactId>yjy-server-sleuth</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>
so I couldn't use 1.0-SNAPSHOT for version?  Replaced 1.0-SNAPSHOT with 1.0-RELEASE?
@marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
@wpzym1125 I'm not talking about the version of your application. I'm saying that this feature is only available starting from Sleuth version `1.3.0.BUILD-SNAPSHOT`. Are you using a BOM (`dependencyManagement` section in your POM) ? If that's the case you have to use `Edgware.BUILD-SNAPSHOT` to use this feature

**Comment by wpzym1125** [comment]
so i should use Edgware to Instead of Dalston.SR1?
@marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Yes. `Edgware.BUILD-SNAPSHOT`

**Comment by wpzym1125** [comment]
Edgware's spring-boot-starter-parent's version is 1.2.8.RELEASE,but Dalston.SR1's is 1.5.2.RELEASE, would this couse other questions?
@marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
yes please update boot

**Comment by wpzym1125** [comment]
ok, i know,let me have a try,thang you very much!
@marcingrzejszczak

**Comment by wpzym1125** [comment]
i change spring cloud to Edgware,bus still has exception,the full stack information is:
2017-08-03 22:44:33,749 WARN [zipkin.reporter.AsyncReporter$BoundedAsyncReporter] [] []- Dropped 2 spans due to IllegalArgumentException(Supplied VIP Address cannot be null)
java.lang.IllegalArgumentException: Supplied VIP Address cannot be null
	at com.netflix.discovery.DiscoveryClient.getInstancesByVipAddress(DiscoveryClient.java:670)
	at com.netflix.discovery.DiscoveryClient.getInstancesByVipAddress(DiscoveryClient.java:653)
	at com.netflix.discovery.DiscoveryClient$$FastClassBySpringCGLIB$$a84c8cb4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cloud.context.config.StandardBeanLifecycleDecorator$2.invoke(StandardBeanLifecycleDecorator.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.springframework.cloud.netflix.eureka.CloudEurekaClient$$EnhancerBySpringCGLIB$$55761b33.getInstancesByVipAddress(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy125.getInstancesByVipAddress(Unknown Source)
	at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClient.getInstances(EurekaDiscoveryClient.java:96)
	at org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient.getInstances(CompositeDiscoveryClient.java:47)
	at org.springframework.cloud.sleuth.zipkin.ZipkinAutoConfiguration$DiscoveryClientZipkinUrlExtractorConfiguration$1.zipkinUrl(ZipkinAutoConfiguration.java:108)
	at org.springframework.cloud.sleuth.zipkin.ZipkinRestTemplateWrapper.doExecute(ZipkinAutoConfiguration.java:245)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:590)
	at org.springframework.cloud.sleuth.zipkin.RestTemplateSender.post(RestTemplateSender.java:78)
	at org.springframework.cloud.sleuth.zipkin.RestTemplateSender.sendSpans(RestTemplateSender.java:51)
	at zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:245)
	at zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:166)
	at zipkin.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
@marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Let's start with the fact that it's no longer the issue that was initially described. Please try to debug this problem by yourself cause, unfortunately, I can't focus fully only on this issue. Please read the documentation, analyze the stacktrace first. You can also write a message here https://gitter.im/spring-cloud/spring-cloud-sleuth and maybe someone will be able to assist you.

If you read the stacktrace it's quite obvious what is going on. You have discovery client on your classpath so the IP is being taken from discovery service. For some reason your address with which you register is null. You can disable this functionality via `spring.zipkin.locator.discovery.enabled: false` .
