### ISSUE TITLE
Zipkin bringing the application down

### ISSUE THREAD

**Issue by jprateekvmware** [spring-cloud/spring-cloud-sleuth#670]
Hi All,
We have got an issue where if the zipkin-collector is throwing 500 errors due to slowness or huge load, it getting the spring boot application down. Calls are async but application is crashing when there are lot of 500 errors.

```
Chrome/59.0.3071.115 Safari/537.36" 10.148.232.3:51037 x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:b10dd514-fc80-4806-58c3-d14e726fe154 response_time:1.157678941 app_id:9aa98259-a95e-461b-921e-035f7ad41ef8
2017-08-03T14:17:49.96-0700 [RTR/3] OUT 
2017-08-03T14:17:52.68-0700 [APP/1] OUT org.springframework.web.client.HttpServerErrorException: 500 null
2017-08-03T14:17:52.68-0700 [APP/1] OUT     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:66)
2017-08-03T14:17:52.68-0700 [APP/1] OUT     at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
2017-08-03T14:17:52.68-0700 [APP/1] OUT     at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628)
2017-08-03T14:17:52.68-0700 [APP/1] OUT     at org.springframework.cloud.sleuth.zipkin.RestTemplateSender.post(RestTemplateSender.java:73)
2017-08-03T14:17:52.68-0700 [APP/1] OUT     at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
2017-08-03T14:17:52.68-0700 [APP/1] OUT     at java.lang.Thread.run(Thread.java:745)
2017-08-03T14:17:52.68-0700 [APP/1] OUT     at org.springframework.cloud.sleuth.zipkin.RestTemplateSender.sendSpans(RestTemplateSender.java:46)
2017-08-03T14:17:52.68-0700 [APP/1] OUT     at zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:228)
2017-08-03T14:17:52.68-0700 [APP/1] OUT     at zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:153)
2017-08-03T14:17:52.68-0700 [APP/1] OUT 2017-08-03 14:17:52.682 [AsyncReporter(org.springframework.cloud.sleuth.zipkin.RestTemplateSender@50554539)] WARN  [,,] z.r.AsyncReporter$BoundedAsyncReporter - :[onError]: - Dropped 3 spans due to HttpServerErrorException(500 null)
```

**Comment by jprateekvmware** [comment]
We testing the application by bringing the zipkin node downs, till now the calls are good and application is up. will test for another hour and if no issues are observed will close the issue.

**Comment by marcingrzejszczak** [comment]
Is it really bringing the application down? The async reporter just throws an exception and that's it, right? We have a bounded queue so at some point the spans will get dropped.

**Comment by adriancole** [comment]
Raised https://github.com/openzipkin/zipkin-reporter-java/issues/55 as I
think we shouldn't be logging a warning like this (as we're already
incrementing a counter and a surge could fill logs)

**Comment by jprateekvmware** [comment]
Looks good after the testing
