### ISSUE TITLE
Sleuth with different actuator port changes HTTP status codes on errors

### ISSUE THREAD

**Issue by WennySoft** [spring-cloud/spring-cloud-sleuth#697]
I'm running sleuth (Dalston.SR3) together with actuator (1.5.7.RELEASE).
Actuator port is changed and some endpoints are disabled. 

When running on an own  port HTTP 500 is returned on each error instead of e.g. 405. When running on the same port as the application codes are fine.

Interestingly sleuth also changes a HEAD request to the deactivated endpoint from 404 to 405
[demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/1302160/demo.zip)

I've set up a simple test project which just changes the actuator port and disables the env endpoint.

different ports without sleuth:

    $ curl -I http://localhost:8081/env
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0   107    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 404
    Content-Type: application/json;charset=UTF-8
    Content-Length: 107
    Date: Thu, 14 Sep 2017 07:16:55 GMT

Adding sleuth-starter as dependency changes the http code:

    $ curl -I http://localhost:8081/env
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0   211    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 500
    Content-Type: application/json;charset=UTF-8
    Content-Length: 211
    Date: Thu, 14 Sep 2017 07:33:11 GMT
    Connection: close

Removing the actuator port property (and running on main port) is fine but code is now 405 instead of 404:

    $ curl -I http://localhost:8080/env
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:--  1:11:35 --:--:--     0HTTP/1.1 405
    X-Application-Context: application
    Allow: POST
    Content-Type: application/json;charset=UTF-8
    Transfer-Encoding: chunked
    Date: Thu, 14 Sep 2017 07:39:24 GMT
    

This is very annoying as we are also using spring boot admin which does HEAD requests which leads to errors in our application logs reagarding unsupported Request Methods (which then trigggers our monitoring)

I attached the simple test project
[demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/1302167/demo.zip)

**Comment by marcingrzejszczak** [comment]
Can you also post the stacktraces of errors that you get whtn 500 is there? Most likely it's a bug related to management properties. Interesting...

**Comment by WennySoft** [comment]
Yes of course (from our application, not the test project):


    2017-09-12 18:27:47,082 ERROR [http-nio-8101-exec-9] b4584b9765fa4fcb o.a.c.c.C.[.[.[.[dispatcherServlet] [DirectJDKLog.java:181] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request method 'HEAD' not supported] with root cause
    org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'HEAD' not supported
        at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:207)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:374)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:314)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:61)
        at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:352)
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcChildContextConfiguration$CompositeHandlerMapping.getHandler(EndpointWebMvcChildContextConfiguration.java:232)
        at org.springframework.web.servlet.DispatcherServlet.getHandler(DispatcherServlet.java:1160)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:940)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.doHead(HttpServlet.java:245)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
`

I see no connection to sleuth here so I tried to dig down checking each dependencies

**Comment by WennySoft** [comment]
running on same port with sleuth only puts a log line:
`2017-09-14 10:00:27.612  WARN [bootstrap,6c91db6b681509e0,6c91db6b681509e0,false] 7576 --- [nio-8080-exec-1] o.s.web.servlet.PageNotFound             : Request method 'HEAD' not supported`

running on same port without sleuth does not log anything

running on different ports leads to the stacktrace above

**Comment by marcingrzejszczak** [comment]
Yeah, I don't see any connection to Sleuth either... Interesting

**Comment by WennySoft** [comment]
>Yeah, I don't see any connection to Sleuth either... Interesting
Yes it is - I also tried in full debug mode but did not see anything notable.
Fortunately the test project is very simple.

**Comment by Begro** [comment]
> Removing the actuator port property (and running on main port) is fine but code is now 405 instead of 404:

You can see the log at startup:
`o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/env],methods=[POST]}" onto public java.lang.Object org.springframework.cloud.context.environment.EnvironmentManagerMvcEndpoint.value(java.util.Map<java.lang.String, java.lang.String>`
So,the response is 405 :method not allowed

**Comment by WennySoft** [comment]
> So,the response is 405 :method not allowed
OK - that is an explanation. 

But interesting why the endpoint is mapped at all when using the same port - it is should be deactivated in both szenarios. Did you check if the endpoint is working? 
But if 404 or 405 is not relevant in our set up (and for sleuth) - we only have problems with the HTTP 500 and the logged exception. For the moment I filter out the exception by a logback filter to not trigger the monitoring (we are starting acceptance test tomorrow).

**Comment by Begro** [comment]
>  HTTP 500 

I debug the code,I found  something very interesting .When endpoint is enable,actuator has  its own handlerExceptionResolvers.
`org.springframework.boot.actuate.autoconfigure.EndpointWebMvcChildContextConfiguration$CompositeHandlerExceptionResolver`.
You can found this in class `DispatcherServlet` , the method `processHandlerException` .
and the variable `handlerExceptionResolvers` hash only one .

When you disable actuator,the variable `handlerExceptionResolvers` hash two, the default spring created.

My English is not very good,so you can see it by yourself.
If you can not figure it out,let me kown,I will try my best.

**Comment by marcingrzejszczak** [comment]
Does this happen only when you add Sleuth or if you add any other Spring Cloud project? BTW can you upload the project as a Github project? Thanks!

**Comment by WennySoft** [comment]
> Does this happen only when you add Sleuth or if you add any other Spring Cloud project? BTW can you upload the project as a Github project? Thanks!

Indeed it also happens if I add starter-consul instead of starter.sleuth

The simple example project is attached to this issue (demo.zip)

**Comment by marcingrzejszczak** [comment]
I know that it is attached, that's why I asked you to publish it on Github. Could you do that please?

**Comment by dsyer** [comment]
I think you need to set `endpoints.env.post.enabled=false` as well. It's nothing to do with Sleuth. Arguably a bug in Spring Cloud Commons.

**Comment by marcingrzejszczak** [comment]
So I'll close it for now
