### ISSUE TITLE
IllegalStateException Exception in TraceHttpServletResponse

### ISSUE THREAD

**Issue by indrabasak** [spring-cloud/spring-cloud-sleuth#709]
I am encountering an exception in`TraceHttpServletResponse`  while Zuul tries to send a response back from one of its internal endpoints. Using version `1.2.4.RELEASE`. Here is the stack trace,

```
Caused by: java.lang.IllegalStateException: WRITER
	at org.eclipse.jetty.server.Response.getOutputStream(Response.java:917) ~[jetty-server-9.4.6.v20170531.jar:9.4.6.v20170531]
	at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:100) ~[tomcat-embed-core-8.5.16.jar:8.5.16]
	at org.springframework.cloud.sleuth.instrument.web.TraceHttpServletResponse.getOutputStream(TraceHttpServletResponse.java:54) ~[spring-cloud-sleuth-core-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:100) ~[tomcat-embed-core-8.5.16.jar:8.5.16]
	at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:100) ~[tomcat-embed-core-8.5.16.jar:8.5.16]
	at org.springframework.cloud.netflix.zuul.filters.post.SendResponseFilter.writeResponse(SendResponseFilter.java:136) ~[spring-cloud-netflix-core-1.3.4.RELEASE.jar:1.3.4.RELEASE]
	at org.springframework.cloud.netflix.zuul.filters.post.SendResponseFilter.run(SendResponseFilter.java:117) ~[spring-cloud-netflix-core-1.3.4.RELEASE.jar:1.3.4.RELEASE]
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112) ~[zuul-core-1.3.0.jar:1.3.0]
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193) ~[zuul-core-1.3.0.jar:1.3.0]
```

**Comment by marcingrzejszczak** [comment]
Do you get the same exception when Sleuth is disabled / is not on the classpath?

**Comment by marcingrzejszczak** [comment]
Ping @indrabasak ? Can you share a sample cause without it it will be very hard to help you?

**Comment by marcingrzejszczak** [comment]
Closing due to inactivity
