### ISSUE TITLE
sprong-cloud-sleuth && zipkin occurs "Unable to deserialize"

### ISSUE THREAD

**Issue by 1073886891qq** [spring-cloud/spring-cloud-sleuth#766]
```
Environment:
     spring-cloud-sleuth-core: 1.2.1.RELEASE
     spring-cloud-sleuth-stream: 1.2.1.RELEASE
     spring-cloud-sleuth--zipkin-stream: 1.2.1.RELEASE
     zipkin : 1.23.2
```

One more hour after zipkin Server launching, there are some errors in zipkin server logs:

```
2017-10-31 15:22:19.004  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [nio-9401-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2017-10-31 15:22:19.045  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [nio-9401-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 41 ms
2017-10-31 15:27:14.472  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-10-31 15:32:14.474  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-10-31 15:37:14.475  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-10-31 15:42:14.476  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-10-31 15:47:14.477  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-10-31 15:52:14.478  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-10-31 15:57:14.478  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-10-31 16:02:14.479  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-10-31 16:07:14.480  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-10-31 16:12:14.481  INFO [sleuth-stream-zipkin-server,,,] 17572 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2017-10-31 16:16:01.279 ERROR [sleuth-stream-zipkin-server,,,] 17572 --- [sleuth.sleuth-1] o.s.c.s.b.r.RabbitMessageChannelBinder   : Unable to deserialize [org.springframework.cloud.sleuth.stream.Spans] using the contentType [application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans] Encountered unregistered class ID: 108
Serialization trace:
tags (org.springframework.cloud.sleuth.Span)
spans (org.springframework.cloud.sleuth.stream.Spans)
2017-10-31 16:16:02.283 ERROR [sleuth-stream-zipkin-server,,,] 17572 --- [sleuth.sleuth-1] o.s.c.s.b.r.RabbitMessageChannelBinder   : Unable to deserialize [org.springframework.cloud.sleuth.stream.Spans] using the contentType [application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans] Encountered unregistered class ID: 108
Serialization trace:
tags (org.springframework.cloud.sleuth.Span)
spans (org.springframework.cloud.sleuth.stream.Spans)
2017-10-31 16:16:04.285 ERROR [sleuth-stream-zipkin-server,,,] 17572 --- [sleuth.sleuth-1] o.s.c.s.b.r.RabbitMessageChannelBinder   : Unable to deserialize [org.springframework.cloud.sleuth.stream.Spans] using the contentType [application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans] Encountered unregistered class ID: 108
Serialization trace:
tags (org.springframework.cloud.sleuth.Span)
spans (org.springframework.cloud.sleuth.stream.Spans)
2017-10-31 16:16:04.290  WARN [sleuth-stream-zipkin-server,,,] 17572 --- [sleuth.sleuth-1] o.s.a.r.r.RejectAndDontRequeueRecoverer  : Retries exhausted for message (Body:'[B@2435581d(byte[1000])' MessageProperties [headers={spanTraceId=ceb6ba5ff0251d67, spanId=ceb6ba5ff0251d67, messageSent=true, spanSampled=0, contentType=application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans}, timestamp=null, messageId=null, userId=null, receivedUserId=null, appId=null, clusterId=null, type=null, correlationId=null, correlationIdString=null, replyTo=null, contentType=application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans, contentEncoding=null, contentLength=0, deliveryMode=null, receivedDeliveryMode=PERSISTENT, expiration=null, priority=0, redelivered=false, receivedExchange=sleuth, receivedRoutingKey=sleuth, receivedDelay=null, deliveryTag=11840, messageCount=0, consumerTag=amq.ctag-F1jUG1Q4SgZcfaIrZYNeHw, consumerQueue=sleuth.sleuth])

org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Listener threw exception
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:915)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:825)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:745)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:97)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:189)
	at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:91)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:286)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:179)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:115)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy155.invokeListener(Unknown Source)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1276)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:726)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1219)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1189)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1500(SimpleMessageListenerContainer.java:97)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1421)
	at java.lang.Thread.run(Thread.java:745)
```

What's problems??

**Comment by marcingrzejszczak** [comment]
Can you check if the problem persists with latest boot and latest Sleuth? It seems as if you had some jdk version related problem. Without a sample that replicates this it will be very hard to help you.

**Comment by 1073886891qq** [comment]
@marcingrzejszczak   Please refer to Issue#767. I have  combined it to Issue#767.

Thanks a lot,
Steven
