### ISSUE TITLE
Sleuth + Reactor. SpanSubscriber cannot be cast to reactor.core.Fuseable$QueueSubscription

### ISSUE THREAD

**Issue by vbychkovskyi** [spring-cloud/spring-cloud-sleuth#770]
An issue with Reactor `Bismuth-SR3 3.1.1-RELEASE` and Sleuth `1.3.0.RC1`.
Could be related to #646 however they have different stacktrace.

```
java.lang.ClassCastException: org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber cannot be cast to reactor.core.Fuseable$QueueSubscription
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:89)
	at org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber.onSubscribe(SpanSubscriber.java:61)
	at org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber.onSubscribe(SpanSubscriber.java:61)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.MonoCollectList$MonoBufferAllSubscriber.onSubscribe(MonoCollectList.java:88)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:331)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:129)
	at reactor.core.publisher.MonoCollectList$MonoBufferAllSubscriber.onSubscribe(MonoCollectList.java:88)
	at reactor.core.publisher.FluxSubscribeOn.subscribe(FluxSubscribeOn.java:66)
	at reactor.core.publisher.MonoCollectList.subscribe(MonoCollectList.java:59)
	at reactor.core.publisher.MonoFlatMapMany.subscribe(MonoFlatMapMany.java:49)
	at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:97)
	at reactor.core.publisher.MonoCollectList.subscribe(MonoCollectList.java:59)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2913)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:169)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:53)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2913)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:370)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:176)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:146)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:332)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:91)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:55)
	at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:97)
	at reactor.core.publisher.MonoReduce.subscribe(MonoReduce.java:46)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46)
	at reactor.core.publisher.Mono.block(Mono.java:1160)

**Comment by bychkovskyi** [comment]
The issue reproduces in a bunch of our SpringBoot tests.
If I understand correctly the reason that
`Hooks.onLastOperator(ReactorSleuth.spanOperator(this.tracer));` was called twice or more.

```
    at org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber.onSubscribe(SpanSubscriber.java:61)
    at org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber.onSubscribe(SpanSubscriber.java:61)
```

We have a workaround for this:

```
    @BeforeClass
    public static void setUp() {
        Hooks.resetOnLastOperator();
    }
```

**Comment by vbychkovskyi** [comment]
The issue reproduces in a bunch of our SpringBoot tests and it doesn't reproduces when run one particular failed test.
If I understand correctly the reason that
`Hooks.onLastOperator(ReactorSleuth.spanOperator(this.tracer));` was called twice or more.

```
    at org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber.onSubscribe(SpanSubscriber.java:61)
    at org.springframework.cloud.sleuth.instrument.reactor.SpanSubscriber.onSubscribe(SpanSubscriber.java:61)
```

We have a workaround for this:

```
    @BeforeClass
    public static void setUp() {
        Hooks.resetOnLastOperator();
    }
```

**Comment by marcingrzejszczak** [comment]
Do you have those problems with production code too? Can you write a test to isolate this issue? Maybe it's just a problem in your tests not with production code really?

**Comment by vbychkovskyi** [comment]
No, in production it haven't appeared yet.
The issue could be closed for now.
If we face this issue in production I'll attach a test and reopen it.
