### ISSUE TITLE
Exception when use sleuth with service discovery

### ISSUE THREAD

**Issue by enderculha** [spring-cloud/spring-cloud-sleuth#805]
I am using spring-cloud-sleuth with eureka service discovery. I set my application yaml as
```
spring:
  zipkin:
    locator:
      discovery:
        enabled: true
    baseUrl: http://zipkin-server/`
```

where my serviceId is zipkin-server. But, when I use like that services give exception as below when they try to send spans
When I specified the port number in the application yaml as
`baseUrl: http://zipkin-server:9411/`  it works. I am using spring-cloud-starter-zipkin:1.2.2.RELEASE and pom version 4.0. 

Exception:

```
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://zipkin-server/api/v1/spans": zipkin-server; nested exception is java.net.UnknownHostException: zipkin-server
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666) ~[spring-web-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628) ~[spring-web-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:590) ~[spring-web-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.cloud.sleuth.zipkin.RestTemplateSender.post(RestTemplateSender.java:73) ~[spring-cloud-sleuth-zipkin-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.sleuth.zipkin.RestTemplateSender.sendSpans(RestTemplateSender.java:46) ~[spring-cloud-sleuth-zipkin-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:245) [zipkin-reporter-1.0.0.jar:na]
	at zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:166) [zipkin-reporter-1.0.0.jar:na]
	at zipkin.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source) [zipkin-reporter-1.0.0.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: java.net.UnknownHostException: zipkin-server
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_74]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_74]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_74]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_74]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_74]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_74]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_74]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_74]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_74]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_74]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_74]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169) ~[na:1.8.0_74]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_74]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_74]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933) ~[na:1.8.0_74]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78) ~[spring-web-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652) ~[spring-web-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	... 8 common frames omitted
```

**Comment by marcingrzejszczak** [comment]
Could you please upload an example somewhere on Github? That will be much easier to debug

**Comment by marcingrzejszczak** [comment]
Can you also try to use the `1.3.0` version and see if the problem is still there? I'm pretty sure that Sleuth in Edgware only supports this feature. So if you use Dalston (1.2.x) then no wonder that it doesn't work.

**Comment by enderculha** [comment]
Upgrading spring-cloud version to Edgeware from Dalston solved the problem. Thanks
