### ISSUE TITLE
ClassNotFoundException when using Feign without Spring Cloud Open Feign

### ISSUE THREAD

**Issue by imberda** [spring-cloud/spring-cloud-sleuth#903]
There seems to be an issue when using Spring Cloud Sleuth in conjunction with Feign but without also using Spring Cloud Open Feign. 

I found this issue using version 2.0.0.M7

When I start my application I see the following exception in the logs:

```
...
Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/openfeign/FeignContext
	at org.springframework.cloud.sleuth.instrument.web.client.feign.FeignContextBeanPostProcessor.postProcessBeforeInitialization(FeignContextBeanPostProcessor.java:43)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
	... 23 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.openfeign.FeignContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 common frames omitted
```

The issue seems to stem from the fact that I have open feign (`io.github.openfeign:feign-core`) on the class path. However I do not have spring-cloud-open-feign (`org.springframework.cloud:spring-cloud-openfeign-core`.  So I am a user of both Sleuth and (vanilla) Feign, but not a user of Spring Cloud Open Feign.

Digging a bit deeper, it seems that [TraceFeignClientAutoConfiguration](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClientAutoConfiguration.java) is `@ConditionalOnClass(Client.class)`, and when this condition is met it creates [FeignContextBeanPostProcessor](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/FeignContextBeanPostProcessor.java). This expects class [FeignContext](https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignContext.java) to be present on the runtime classpath.

The fix to this _could_ be as simple as adding `@ConditionalOnClass(FeignContextBeanPostProcessor.class)` to the `FeignBeanPostProcessorConfiguration` class

**Comment by marcingrzejszczak** [comment]
I see. From what I see in the code, we only support Spring Cloud Open Feign integration. I'll update the conditional on the whole `TraceFeignClientAutoConfiguration` to become `@ConditionalOnClass(FeignContext.class)`. WDYT?

**Comment by spencergibb** [comment]
Shouldn't it be both?
