### ISSUE TITLE
WebClient - NullPointerException in case socket error

### ISSUE THREAD

**Issue by Delorien84** [spring-cloud/spring-cloud-sleuth#916]
Hi,
 we got following exception, when using `WebClient` with `Sleuth`. This happened when the HTTP request unexceptionally failed due to network failure (socket error) - (in reality we forcefully shut down target services to test `Hystrix` behavior while there were active HTTP connections).

Tested on:
* Spring Boot 2.0.0
* Spring Cloud Finchley.M9

```
2018-03-28 12:42:12.261  WARN [dcm,,,] 13787 --- [reactor-http-nio-1] io.netty.util.concurrent.DefaultPromise  : An exception was thrown by reactor.ipc.netty.channel.PooledClientContextHandler.operationComplete()

reactor.core.Exceptions$BubblingException: java.lang.NullPointerException
	at reactor.core.Exceptions.bubble(Exceptions.java:154)
	at reactor.core.publisher.Operators.onErrorDropped(Operators.java:256)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:284)
	at reactor.core.publisher.Operators.error(Operators.java:175)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1069)
	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:241)
	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:323)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:74)
	at org.springframework.cloud.sleuth.instrument.reactor.LazySpanSubscriber.onNext(LazySpanSubscriber.java:52)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1626)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1440)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:68)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:80)
	at org.springframework.cloud.sleuth.instrument.reactor.LazySpanSubscriber.onError(LazySpanSubscriber.java:56)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:80)
	at org.springframework.cloud.sleuth.instrument.reactor.LazySpanSubscriber.onError(LazySpanSubscriber.java:56)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:80)
	at org.springframework.cloud.sleuth.instrument.reactor.LazySpanSubscriber.onError(LazySpanSubscriber.java:56)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:207)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:80)
	at org.springframework.cloud.sleuth.instrument.reactor.LazySpanSubscriber.onError(LazySpanSubscriber.java:56)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:207)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:80)
	at org.springframework.cloud.sleuth.instrument.reactor.LazySpanSubscriber.onError(LazySpanSubscriber.java:56)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:207)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:80)
	at org.springframework.cloud.sleuth.instrument.reactor.LazySpanSubscriber.onError(LazySpanSubscriber.java:56)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:80)
	at org.springframework.cloud.sleuth.instrument.reactor.LazySpanSubscriber.onError(LazySpanSubscriber.java:56)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:80)
	at org.springframework.cloud.sleuth.instrument.reactor.LazySpanSubscriber.onError(LazySpanSubscriber.java:56)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onError(FluxRetryPredicate.java:100)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:160)
	at reactor.ipc.netty.channel.ContextHandler.fireContextError(ContextHandler.java:272)
	at reactor.ipc.netty.channel.PooledClientContextHandler.operationComplete(PooledClientContextHandler.java:152)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction.lambda$null$1(TraceWebClientBeanPostProcessor.java:149)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:280)
	... 54 common frames omitted
```

**Comment by marcingrzejszczak** [comment]
Thanks for the report! I've added a NPE check. You can wait 15 minutes and try again with snapshots.
