### ISSUE TITLE
spring cloud zipkin no such method error

### ISSUE THREAD

**Issue by kganger** [spring-cloud/spring-cloud-sleuth#920]
Getting no such method error using sleuth and zipkin 

This is a kotlin / gradle project 
I am using spring boot 2.0.0.RELEASE
spring cloud Finchley.M9 

it works ok with spring-cloud-starter-sleuth when I include spring-cloud-starter-zipkin I get the following error on every few requests 

```
java.lang.NoSuchMethodError: zipkin2.Span$Builder.timestamp(J)Lzipkin2/Span$Builder;
	at brave.internal.recorder.MutableSpan.start(MutableSpan.java:40) ~[brave-4.18.2.jar:na]
	at brave.internal.recorder.MutableSpan.start(MutableSpan.java:31) ~[brave-4.18.2.jar:na]
	at brave.internal.recorder.Recorder.start(Recorder.java:53) ~[brave-4.18.2.jar:na]
	at brave.RealSpan.start(RealSpan.java:23) ~[brave-4.18.2.jar:na]
	at brave.http.HttpServerHandler.handleReceive(HttpServerHandler.java:88) ~[brave-instrumentation-http-4.18.2.jar:na]
	at brave.http.HttpServerHandler.handleReceive(HttpServerHandler.java:69) ~[brave-instrumentation-http-4.18.2.jar:na]
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:67) ~[brave-instrumentation-servlet-4.18.2.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.28.jar:8.5.28]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]

```

**Comment by kganger** [comment]
Sorry I was out of the office.  We have a lot of things extracted into common "starters / plugins" so I ma not sure it will be totally helpful.  I attached a full dependency tree which may be more helpful.  
[dependency report.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/1871820/dependency.report.txt)
 
```
buildscript {

    apply from: "https://sscgit.ast.lmco.com/projects/DT/repos/dte-boot-gradle-plugin/raw/repos.gradle?at=${dteBootScriptsVersion}"
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}")
        classpath("org.jetbrains.kotlin:kotlin-allopen:${kotlinVersion}")
        classpath "org.jetbrains.kotlin:kotlin-noarg:${kotlinVersion}"
        classpath("ssc.dte:dte-boot:${dteBootVersion}")
        classpath("gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:${detektVersion}")

    }
    repositories {
        mavenCentral()
    }
}
apply plugin: 'ssc.dte-boot'
apply plugin: 'kotlin'
apply plugin: 'kotlin-jpa'
apply from: "https://sscgit.ast.lmco.com/projects/DT/repos/dte-boot-gradle-plugin/raw/dte-boot-kotlin.gradle?at=${dteBootScriptsVersion}"

group = 'ssc.datahub'
version = "${appVersion}"

dependencies {
    compile('ssc.datahub:spring-boot-starter-svc')
    compile('ssc.datahub:spring-boot-starter-graphql')
    compile "org.jetbrains.kotlinx:kotlinx-coroutines-core:0.22.3"
    testCompile('com.h2database:h2:1.4.196')
    testCompile 'org.skyscreamer:jsonassert:1.5.0'
}

kotlin { experimental { coroutines 'enable' } }


graphqlImport {
    defaultPackage = "datahub.frontend.model"

    graphQlFile = [name: "supplier", project: "svc.supply-chain"]

    graphQlFile = [name: 'caddoc', project: 'svc.engineering']
    graphQlFile = [name: 'doc', project: 'svc.engineering']
    graphQlFile = [name: 'part', project: 'svc.engineering']

    graphQlFile = [name: 'producitonOrder', project: 'svc.manufacturing']

}
repositories {
    mavenCentral()
}
compileKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
compileTestKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

**Comment by marcingrzejszczak** [comment]
You have a very custom build setup, with custom plugins. If you go to start.spring.io you can generate a project that doesn't have these kinds of issues. Please generate such a project and compare what's wrong with your setup.
