### ISSUE TITLE
NullPointerException with reactor-core 3 on Connection refused/Connection timed out

### ISSUE THREAD

**Issue by ati90ati** [spring-cloud/spring-cloud-sleuth#955]
I've using spring-cloud-sleuth 2.0.0.M9, spring boot webflux (2.0.0.RELEASE).
Spring boot gets the reactore-core version 3.1.5.RELEASE.
I've many microservices.
When one microservice calling another microservice and there are no response (ex: Connection refused/Connection timed out) I've got this exception:

    2018-04-24 09:42:15.988  WARN [EMS,,] 30760 --- [ctor-http-nio-2] io.netty.util.concurrent.DefaultPromise  : An exception was thrown by 
    reactor.ipc.netty.channel.PooledClientContextHandler.operationComplete()
    reactor.core.Exceptions$BubblingException: java.lang.NullPointerException
        at reactor.core.Exceptions.bubble(Exceptions.java:154)
    Caused by: java.lang.NullPointerException: null
        at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction.lambda$null$1(TraceWebClientBeanPostProcessor.java:149)
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:280)

The clientResponse (first) parameter will be null (`parent.onAfterTerminateCall.accept(null, t);`) because there is no request, just exception.
I've using reactive java with Mono/Flux.

**Comment by marcingrzejszczak** [comment]
Can you check latest snapshots? 

```
if (clientResponse == null || clientResponse.statusCode() == null) {
									if (log.isDebugEnabled()) {
										log.debug(
												"No response was returned. Will close the span ["
														+ clientSpan + "]");
									}
									handleReceive(clientSpan, ws, clientResponse, throwable);
									return;
								}
```

line 149 is 

`if (clientResponse == null || clientResponse.statusCode() == null) {`

we have a NPE check

**Comment by marcingrzejszczak** [comment]
Ping @ati90ati ?

**Comment by marcingrzejszczak** [comment]
Closing due to inactivity

**Comment by ati90ati** [comment]
Hey,
sorry but I was very busy the last weeks.
I've tried the new version RC1 and it's working like a charm now!
Thank you for the fix!
