### ISSUE TITLE
Spring Sleuth Correlating Messages

### ISSUE THREAD

**Issue by englishbreeze** [spring-cloud/spring-cloud-sleuth#96]
Hi,
 I have a service that sends messages to another service and would like to correlate them together. The problem is that Spring Sleuth does not correlate the two services together (i.e. Set the parent trace id of the receiver to the trace id of the sender) I'm using Spring Integration MessageChannel to send message from one service to another. Here is my channel configuration for the outbound channel:

        @Bean
	@ServiceActivator(inputChannel = "amqpOutboundChannel")
	public AmqpOutboundEndpoint amqpOutbound(AmqpTemplate amqpTemplate) {
		AmqpOutboundEndpoint outbound = new AmqpOutboundEndpoint(amqpTemplate);
		outbound.setRoutingKey("myQueue"); // default exchange - route to queue
										// 'foo'
		return outbound;
	}

	@Bean
	public MessageChannel amqpOutboundChannel() {
		return new DirectChannel();
	}
sending the Message using this code:
MessagingTemplate template = new MessagingTemplate();
template.send(channel, new GenericMessage<String>("blahblah"));

Here is my channel configuration for the input channel:

        @Bean
	public MessageChannel amqpInputChannel() {
		return new DirectChannel();
	}

	@Bean
	public AmqpInboundChannelAdapter inbound(SimpleMessageListenerContainer listenerContainer,
			@Qualifier("amqpInputChannel") MessageChannel channel) {
		AmqpInboundChannelAdapter adapter = new AmqpInboundChannelAdapter(listenerContainer);
		adapter.setOutputChannel(channel);
		return adapter;
	}

	@Bean
	public SimpleMessageListenerContainer container(ConnectionFactory connectionFactory) {
		SimpleMessageListenerContainer container = new SimpleMessageListenerContainer(connectionFactory);
		container.setQueueNames("myQueue");
		// ...
		return container;
	}

	@Bean
	@ServiceActivator(inputChannel = "amqpInputChannel")
	public MessageHandler handler() {
		return new MessageHandler() {

			@Override
			public void handleMessage(Message<?> message) throws MessagingException {
				System.out.println(message.getPayload());
			}

		};

Can you guys let me know how I'm suppose to correlate the two services using Messaging?

**Comment by marcingrzejszczak** [comment]
Try using the annotation based approach instead of direct calling of
messagetemplate. Then it should work.

**Comment by marcingrzejszczak** [comment]
Also here you have an example of usage of Spring Cloud Stream to make apps
talk to each other. This is the sender
https://github.com/spring-cloud-samples/brewery/blob/master/common/src/main/java/io/spring/cloud/samples/brewery/common/events/EventGateway.java.
and this is the receiver
https://github.com/spring-cloud-samples/brewery/blob/master/brewing/src/main/java/io/spring/cloud/samples/brewery/reporting/EventListener.java
.

**Comment by gauravrmazra** [comment]
In your DirectChannel bean, set following two interceptors

**Comment by marcingrzejszczak** [comment]
@gauravrmazra thank you for your feedback and support. That's highly appreciated.

However the thing is we want users not to need to add any interceptors manually. We would like them use approaches that will set things automatically for them.

My example is exactly showing that case.

First enable binding (@englishbreeze - you'll have one binding on the sender and one on the receiver side - in this example I have both in one place)

https://github.com/spring-cloud-samples/brewery/blob/master/brewing/src/main/java/io/spring/cloud/samples/brewery/Application.java#L18

Then use the approaches mentioned in my comment below.

Using Spring Cloud Stream is the suggested way of making applications talk to each other indirectly via messaging.

**Comment by gauravrmazra** [comment]
@marcingrzejszczak  Agreed. 
But at times, user will be writing their in their own way using messaging components (as OP). May be using spring-integration-java-dsl for integration. In that case, It will be nice if they know what they are missing in their component for tracing.

**Comment by marcingrzejszczak** [comment]
@gauravrmazra you are right but I guess what @englishbreeze was asking about is how to do things properly.

https://github.com/spring-cloud/spring-cloud-sleuth/commit/3b6b49fc878bd36fb78f4912d66bbe339b65ba14 - I think that this proves that it's enough to register `MessagingTemplate` as a bean and Sleuth's autowiring will work properly in terms of intercepting channels. If that's not the case then we'll have to fix it so it does work out of the box

We can't support all possible scenarios of manual creation of things. But thanks for your support @gauravrmazra . We really appreciate it!!

**Comment by englishbreeze** [comment]
Thank you for the reply @marcingrzejszczak and @gauravrmazra . If I wanted to use AMQP to send messages from one service to another via some broker (e.g. RabbitMQ), how do I set it up such that spring sleuth will correlate the sender and the receiver. I tried @gauravrmazra 's suggestion of adding TraceChannelInterptor in my DirectChannel bean but it still does not correlate them together.

**Comment by marcingrzejszczak** [comment]
@englishbreeze check out the brewery sample as I told you in the previous comments.

First enable binding (@englishbreeze - you'll have one binding on the sender and one on the receiver side - in this example I have both in one place)

https://github.com/spring-cloud-samples/brewery/blob/master/brewing/src/main/java/io/spring/cloud/samples/brewery/Application.java#L18

 This is the sender
https://github.com/spring-cloud-samples/brewery/blob/master/common/src/main/java/io/spring/cloud/samples/brewery/common/events/EventGateway.java.

and this is the receiver
https://github.com/spring-cloud-samples/brewery/blob/master/brewing/src/main/java/io/spring/cloud/samples/brewery/reporting/EventListener.java

IN your dependencies add https://github.com/spring-cloud-samples/brewery/blob/master/build.gradle#L118 and https://github.com/spring-cloud-samples/brewery/blob/master/build.gradle#L119

Can we close this issue and maybe move this discussion to https://gitter.im/spring-cloud/spring-cloud ?

**Comment by englishbreeze** [comment]
Thanks for your help @marcingrzejszczak . Do you know how to resolve this error?

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import     candidates for configuration class [com.Application]; nested exception is java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.sleuth.stream.SleuthStreamAutoConfiguration
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:518) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:454) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:185) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:321) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at com.fincad.simpleProxy.Application.main(Application.java:37) [classes/:na]
Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.sleuth.stream.SleuthStreamAutoConfiguration
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:203) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:509) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 15 common frames omitted
Caused by: java.lang.IllegalStateException: The name or value attribute of @ConditionalOnProperty must be specified
	at org.springframework.util.Assert.state(Assert.java:392) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnPropertyCondition.getNames(OnPropertyCondition.java:101) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnPropertyCondition.getMatchOutcome(OnPropertyCondition.java:55) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	... 18 common frames omitted

**Comment by marcingrzejszczak** [comment]
Hmm at the first glance it seems like a mismatch in versions of Spring, Spring Boot and Sleuth - can we close this issue and move to Gitter with further explanations?

**Comment by englishbreeze** [comment]
Yes

**Comment by gauravrmazra** [comment]
@dsyer 

TraceChannelInterceptor can't trace Stomp protocol based messages sent using Spring. Also it has different message headers[normal headers + native headers] than the usual JMS message.

e.g. https://spring.io/guides/gs/messaging-stomp-websocket/
e.g. https://dzone.com/articles/easy-messaging-stomp-over

**Comment by dsyer** [comment]
There is nothing in Sleuth specific to JMS: it is all using the spring messaging APIs (which is the same as the STOMP support in Spring). So I don't really understand the issue yet.

**Comment by gauravrmazra** [comment]
JMS and STOMP message use different message builder. They have different header accessors and different type of MessageHeaders.
e.g. JMS message Builder => org.springframework.integration.support.MessageBuilder
STOMP message builder => org.springframework.messaging.support.MessageBuilder

jms header accessor => IntegrationMessageHeaderAccessor
STOMP header accessor => org.springframework.messaging.support.MessageHeaderAccessor.MessageHeaderAccessor(Message<?>)

**Comment by dsyer** [comment]
Yes, but a) it's not JMS, it's Spring Integration and b) they both use the same core API for `Message`, `MessageChannel`, interceptors etc. so I still think we other to be able to use the same interceptor.

In any case can we stop discussing this here, in an unrelated, closed issue?
