### ISSUE TITLE
Spring Cloud Sleuth no longer works without Spring Integration on the classpath

### ISSUE THREAD

**Issue by JaroKuruc** [spring-cloud/spring-cloud-sleuth#976]
Bug report
Spring Boot version: 1.5.12.RELEASE
Spring Cloud version: Edgware.SR3

Description:
Below change introduced runtime dependency between Spring Cloud Sleuth and Spring Integration, which was not there before.
https://github.com/spring-cloud/spring-cloud-sleuth/compare/v1.3.2.RELEASE...v1.3.3.RELEASE#diff-9739172424d58d30d491370b7a33b121R132

Above change causes runtime error (`java.lang.NoClassDefFoundError`) when using Spring Cloud Sleuth without Spring Integration libraries on the classpath.
```
org.springframework.messaging.MessageDeliveryException: Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; nested exception is java.lang.NoClassDefFoundError: org/springframework/integration/channel/DirectChannel
        at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:130)
        at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:104)
        at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageFromClient(StompSubProtocolHandler.java:299)
        at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:309)
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75)
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56)
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58)
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.delegateMessages(AbstractSockJsSession.java:380)
        at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.handleMessage(WebSocketServerSockJsSession.java:194)
        at org.springframework.web.socket.sockjs.transport.handler.SockJsWebSocketHandler.handleTextMessage(SockJsWebSocketHandler.java:92)
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:110)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:42)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:81)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:78)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:394)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/springframework/integration/channel/DirectChannel
        at org.springframework.cloud.sleuth.instrument.messaging.TraceChannelInterceptor.isDirectChannel(TraceChannelInterceptor.java:132)
        at org.springframework.cloud.sleuth.instrument.messaging.TraceChannelInterceptor.preSend(TraceChannelInterceptor.java:125)
        at org.springframework.messaging.support.AbstractMessageChannel$ChannelInterceptorChain.applyPreSend(AbstractMessageChannel.java:158)
        at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:113)
        ... 32 common frames omitted
```

**Comment by marcingrzejszczak** [comment]
The link you've provided doesn't work. Can you show again what exactly introduced that change?

**Comment by JaroKuruc** [comment]
@marcingrzejszczak Please see below diff
![image](https://user-images.githubusercontent.com/149371/39708017-4ce43466-5216-11e8-97c8-eb49eb3364cb.png)

**Comment by marcingrzejszczak** [comment]
Wat? `DirectChannel` comes from `spring-integration-core`. Don't you have it on the classpath, or am I missing something?

**Comment by marcingrzejszczak** [comment]
Ah, **without** you said... Oh yeah, that's bad :|

**Comment by marcingrzejszczak** [comment]
@JaroKuruc can you check the latest snapshots?

**Comment by chocho01** [comment]
Same issue with spring boot 1.5.9.RELEASE
