### ISSUE TITLE
@SpanTag annotation does not work with Spring Boot 2

### ISSUE THREAD

**Issue by jbrmg** [spring-cloud/spring-cloud-sleuth#990]
Hi, 

I am currently trying to migrate our Spring Boot 1 projects to Spring Boot 2. We aim to use the versions spring-cloud-starter-sleuth 2.0.0.RC1 with Spring Boot 2.0.2.RELEASE. Unfortunately, we face some problems during the migration because of the `SpanTag` annotation.

The problems seems to be that Spring now requires `@AliasFor` to be set on both ends of the alias, but `@SpanTag` only has it once.

```java
public @interface SpanTag {

	/**
	 * The name of the key of the tag which should be created.
	 */
        // @AliasFor("key") is missing here
	String value() default "";

	/**
	 * The name of the key of the tag which should be created.
	 */
	@AliasFor("value")
	String key() default "";
```

This is in constrast to `@NewSpan`, which has it on both ends of the alias:

```java
public @interface NewSpan {

	/**
	 * The name of the span which will be created. Default is the annotated method's name separated by hyphens.
	 */
	@AliasFor("value")
	String name() default "";

	/**
	 * The name of the span which will be created. Default is the annotated method's name separated by hyphens.
	 */
	@AliasFor("name")
	String value() default "";
```

Having only one `@AliasFor` annotation results in the following exception during runtime:

```
Caused by: org.springframework.core.annotation.AnnotationConfigurationException: Attribute 'value' in annotation [org.springframework.cloud.sleuth.annotation.SpanTag] must be declared as an @AliasFor [key].
	at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.validate(AnnotationUtils.java:2141)
	at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.from(AnnotationUtils.java:2089)
	at org.springframework.core.annotation.AnnotationUtils.getAttributeAliasNames(AnnotationUtils.java:1748)
	at org.springframework.core.annotation.AnnotationUtils.isSynthesizable(AnnotationUtils.java:1708)
	at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotation(AnnotationUtils.java:1499)
	at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotationArray(AnnotationUtils.java:1595)
	at org.springframework.core.annotation.SynthesizingMethodParameter.adaptAnnotationArray(SynthesizingMethodParameter.java:104)
	at org.springframework.core.MethodParameter.getParameterAnnotations(MethodParameter.java:540)
	at springfox.documentation.service.ResolvedMethodParameter.<init>(ResolvedMethodParameter.java:39)
	at springfox.documentation.spring.web.readers.operation.HandlerMethodResolver$3.apply(HandlerMethodResolver.java:169)
	at springfox.documentation.spring.web.readers.operation.HandlerMethodResolver$3.apply(HandlerMethodResolver.java:163)
	at com.google.common.base.Present.transform(Present.java:77)
	at springfox.documentation.spring.web.readers.operation.HandlerMethodResolver.methodParameters(HandlerMethodResolver.java:78)
	at springfox.documentation.spring.web.WebMvcRequestHandler.getParameters(WebMvcRequestHandler.java:128)
	at springfox.documentation.spring.web.plugins.PathAndParametersEquivalence.doHash(PathAndParametersEquivalence.java:61)
	at springfox.documentation.spring.web.plugins.PathAndParametersEquivalence.doHash(PathAndParametersEquivalence.java:32)
	at com.google.common.base.Equivalence.hash(Equivalence.java:113)
	at com.google.common.base.Equivalence$Wrapper.hashCode(Equivalence.java:229)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.LinkedHashMap.get(LinkedHashMap.java:440)
	at com.google.common.collect.AbstractMapBasedMultimap.put(AbstractMapBasedMultimap.java:192)
	at com.google.common.collect.AbstractListMultimap.put(AbstractListMultimap.java:106)
	at com.google.common.collect.ImmutableMultimap$Builder.put(ImmutableMultimap.java:169)
	at com.google.common.collect.ImmutableListMultimap$Builder.put(ImmutableListMultimap.java:242)
	at com.google.common.collect.Multimaps.index(Multimaps.java:1637)
	at com.google.common.collect.Multimaps.index(Multimaps.java:1590)
	at springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner.combined(DefaultRequestHandlerCombiner.java:59)
	at springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner.combine(DefaultRequestHandlerCombiner.java:49)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.defaultContextBuilder(DocumentationPluginsBootstrapper.java:106)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.buildContext(DocumentationPluginsBootstrapper.java:91)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:154)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
	... 14 common frames omitted
```

**Comment by ethanbishop** [comment]
This bug also affects use with Spring Boot 1.

I've reproduced the same runtime error above using spring-boot-starter-web:1.5.17.RELEASE and spring-cloud-starter-sleuth:1.3.5.RELEASE. Downgrading spring-cloud-start-sleuth to 1.3.0.RELEASE (before https://github.com/spring-cloud/spring-cloud-sleuth/issues/800 was introduced) fixes the issue. I can provide a minimal reproduction project if needed.

Is there any plan to continue backporting fixes to Spring Boot 1?

**Comment by marcingrzejszczak** [comment]
We backport pretty much only critical issues. We encourage everybody to upgrade to the newest release trains.

**Comment by marcingrzejszczak** [comment]
Although this one is so simple that if you provide a PR we will merge it

**Comment by ethanbishop** [comment]
Fair enough, I'll make a PR shortly.

**Comment by marcingrzejszczak** [comment]
Awesome, create a PR to 1.3.x branch

**Comment by ethanbishop** [comment]
See above. I suppose this affects 1.2.x as well but I'll leave that as an exercise for anyone who wants it.
